// German catalog: normalized English source -> German.
// Du throughout, the register Signal uses in German. Native-speaker review
// is welcome and rough edges deserve bug reports. Regenerate the key list
// with: node tools/extract-strings.mjs
// Missing entries fall back to English by design.
export const de = {
  "Scan a code": "Code scannen",
  "Scan an invite code": "Einladungscode scannen",
  "Point the camera at the invite code on their screen.": "Richte die Kamera auf den Einladungscode auf dem anderen Bildschirm.",
  "That is a safety number code, not an invite.": "Das ist ein Code für eine Sicherheitsnummer, keine Einladung.",
  "That is not a Starling invite code.": "Das ist kein Starling-Einladungscode.",
  "Remind me if sharing stays off": "Erinnere mich, wenn Teilen aus bleibt",
  "If you stop sharing and do not turn it back on, this phone shows a notification after that long. Nothing goes to your circle.": "Wenn du das Teilen beendest und nicht wieder einschaltest, zeigt dieses Handy nach dieser Zeit eine Benachrichtigung. An deinen Kreis geht nichts.",
  "Never": "Nie",
  "1 h": "1 Std.",
  "4 h": "4 Std.",
  "12 h": "12 Std.",
  "SOS and Do Not Disturb": "SOS und „Bitte nicht stören“",
  "An SOS from your circle rings through Do Not Disturb when alarms are allowed. To let it through total silence too, turn on Override Do Not Disturb for Emergency alerts.": "Ein SOS aus deinem Kreis klingelt trotz „Bitte nicht stören“, wenn Alarme erlaubt sind. Damit es auch bei völliger Stille durchkommt, schalte bei Notfall-Hinweise „Bitte nicht stören“ ignorieren ein.",
  "Open emergency alert settings": "Einstellungen für Notfall-Hinweise öffnen",
  "{dist} to the {way} of you": "{dist} Richtung {way}",
  "{failed} of {total} members did not get the new keys yet.": "{failed} von {total} Mitgliedern haben die neuen Schlüssel noch nicht bekommen.",
  "{n} members' keys changed": "Schlüssel von {n} Mitgliedern geändert",
  "{n} sets of keys besides yours can decrypt what you send: {checked} checked by a person, {unchecked} trusted on first use.": "{n} Schlüsselsätze außer deinem können entschlüsseln, was du sendest: {checked} von einer Person geprüft, {unchecked} beim ersten Kontakt ungeprüft übernommen.",
  "{name} radius": "Radius von {name}",
  "{name} saved. Only this phone knows it exists.": "{name} gespeichert. Nur dieses Handy weiß, dass es diesen Ort gibt.",
  "{who} arrived at {place}": "{who} ist angekommen: {place}",
  "{who} can read nothing this circle sends from now on. Everyone still here got new keys.": "Alles, was dieser Kreis ab jetzt sendet, bleibt für {who} unlesbar. Alle, die noch da sind, haben neue Schlüssel.",
  "{who} changed the keys": "{who} hat die Schlüssel geändert",
  "{who} changed the keys.": "{who} hat die Schlüssel geändert.",
  "{who} checked in": "{who} hat sich gemeldet",
  "{who} is answering with different keys. That is a reinstall, or somebody else in their place, and this phone cannot tell which. Their location stays off your map until you accept.": "{who} antwortet mit anderen Schlüsseln. Entweder eine Neuinstallation, oder jemand anderes steckt dahinter, und dieses Handy kann das nicht unterscheiden. Der Standort erscheint nicht auf deiner Karte, bis du die neuen Schlüssel annimmst.",
  "{who} is now pinned to the new keys.": "{who} ist jetzt an die neuen Schlüssel gebunden.",
  "{who} is out. Everyone else has new keys.": "{who} ist raus. Alle anderen haben neue Schlüssel.",
  "{who} joined. Everyone got new keys.": "{who} ist beigetreten. Alle haben neue Schlüssel.",
  "{who} left {place}": "{who} ist gegangen: {place}",
  "{who} made new keys, but your list of members does not match theirs.": "{who} hat neue Schlüssel erzeugt, aber eure Mitgliederlisten stimmen nicht überein.",
  "{who} removed {gone}": "{who} hat {gone} entfernt",
  "{who} removed {gone}.": "{who} hat {gone} entfernt.",
  "{who} removed {n} people": "{who} hat {n} Personen entfernt",
  "{who} removed {n} people from the circle.": "{who} hat {n} Personen aus dem Kreis entfernt.",
  "{who} wants to join": "{who} möchte beitreten",
  "{who} wants to join. Check their safety number.": "{who} möchte beitreten. Prüf die Sicherheitsnummer.",
  "{who}'s keys changed": "Schlüssel von {who} geändert",
  "{who}'s keys changed. Their location is hidden until you accept it.": "Die Schlüssel von {who} haben sich geändert. Der Standort bleibt verborgen, bis du sie annimmst.",
  "{who}'s phone is at {pct}%": "Das Handy von {who} ist bei {pct} %",
  "1 hr": "1 Std.",
  "1 min": "1 Min.",
  "5 min": "5 Min.",
  "A circle holds {n} people and yours is full. Remove somebody before letting anyone else in.": "Ein Kreis fasst {n} Personen, und deiner ist voll. Entferne jemanden, bevor du noch jemanden reinlässt.",
  "A few words your circle sees next to your name. It is encrypted like everything else, and it clears when you stop sharing.": "Ein paar Worte, die dein Kreis neben deinem Namen sieht. Verschlüsselt wie alles andere, und sie verschwinden, wenn du aufhörst zu teilen.",
  "a member": "ein Mitglied",
  "A member": "Ein Mitglied",
  "A member's keys changed": "Die Schlüssel eines Mitglieds haben sich geändert",
  "A newly admitted key can also read back {window} of history. That window is yours to set in Settings.": "Ein neu zugelassener Schlüssel kann auch den Verlauf der letzten {window} lesen. Wie weit zurück, legst du in den Einstellungen fest.",
  "A place with the privacy fence on shares only its center while you are inside it, never your exact spot within. Your circle still sees you are there; what they stop seeing is where in there. An SOS always sends your real position.": "Ein Ort mit Sichtschutz teilt nur seinen Mittelpunkt, solange du drin bist, nie deine genaue Stelle darin. Dein Kreis sieht weiter, dass du dort bist; nur nicht mehr, wo genau. Ein SOS sendet immer deine echte Position.",
  "A relay must be an https URL, like https://relay.example.org": "Ein Relay muss eine https-URL sein, etwa https://relay.example.org",
  "A second passcode for a moment when someone makes you open Starling. Entering it on the lock screen erases everything on this device, instantly and silently, and shows a fresh install. There is no undo and no way back in. It only guards the passcode path: biometric unlock still opens the app normally, so if a forced unlock is in your threat model, turn biometrics off too.": "Ein zweiter Passcode für den Moment, in dem dich jemand zwingt, Starling zu öffnen. Gibst du ihn auf dem Sperrbildschirm ein, wird alles auf diesem Gerät gelöscht, sofort und ohne Hinweis, und es erscheint eine frische Installation. Es gibt kein Zurück und keinen Weg wieder rein. Er schützt nur den Weg über den Passcode: Die biometrische Entsperrung öffnet die App weiter ganz normal. Wenn also ein erzwungenes Entsperren zu deinem Bedrohungsmodell gehört, schalte auch die Biometrie aus.",
  "A tracker ID goes out as tid with each position, so a forwarder or Home Assistant can tell this phone apart.": "Eine Tracker-ID geht als tid mit jeder Position raus, damit eine Weiterleitung oder Home Assistant dieses Handy von anderen unterscheiden kann.",
  "A welcome arrived that did not match the person this link came from, and it was refused. That can be an interception attempt, or just a stale retry or a network hiccup. Your request is still waiting for the person who actually invited you; check with them before using the link again.": "Eine Willkommensnachricht kam an, die nicht zu der Person passte, von der dieser Link stammt, und wurde abgelehnt. Das kann ein Abfangversuch sein, oder nur ein alter Wiederholungsversuch oder ein kurzer Netzwerkaussetzer. Deine Anfrage wartet weiter auf die Person, die dich wirklich eingeladen hat; sprich mit ihr, bevor du den Link noch mal benutzt.",
  "A welcome that did not match the link's sender was refused. That can be an interception attempt, or just a stale retry. Check with whoever gave you the link before you use it again.": "Eine Willkommensnachricht, die nicht zum Absender des Links passte, wurde abgelehnt. Das kann ein Abfangversuch sein, oder nur ein alter Wiederholungsversuch. Sprich mit der Person, die dir den Link gegeben hat, bevor du ihn noch mal benutzt.",
  "Accept the new keys": "Neue Schlüssel annehmen",
  "Accepting gives the whole circle new keys and lets them see everyone's location from then on. They cannot read anything sent before.": "Annehmen gibt dem ganzen Kreis neue Schlüssel und lässt die Person ab dann den Standort aller sehen. Was vorher gesendet wurde, kann sie nicht lesen.",
  "Add Starling to your home screen": "Starling zum Startbildschirm hinzufügen",
  "ahead": "vor",
  "Allow": "Erlauben",
  "Allow background running": "Im Hintergrund laufen lassen",
  "also to {host}": "auch an {host}",
  "Android had stopped your share in the background. It is back on.": "Android hatte deine Freigabe im Hintergrund gestoppt. Sie läuft wieder.",
  "Android kept Starling from running in the background, so your circle stopped getting your location and the share ended. Nobody did this by hand.": "Android hat Starling nicht im Hintergrund laufen lassen, deshalb bekam dein Kreis deinen Standort nicht mehr und die Freigabe endete. Das hat niemand von Hand gemacht.",
  "Android may pause Starling to save battery while your screen is off, and your circle would stop seeing you move. Letting Starling run in the background stops that. It only makes a difference while you share.": "Android kann Starling bei ausgeschaltetem Bildschirm pausieren, um Akku zu sparen, und dein Kreis sieht dann nicht mehr, wie du dich bewegst. Starling im Hintergrund laufen zu lassen verhindert das. Es macht nur einen Unterschied, während du teilst.",
  "Android shut down the part of Starling that sends your position, so the share stopped. Nobody did this by hand.": "Android hat den Teil von Starling beendet, der deine Position sendet, deshalb ist die Freigabe gestoppt. Das hat niemand von Hand gemacht.",
  "Android stopped Starling in the background because its battery use is set to Restricted, and that ends every share a minute after you leave the app. Set it to Unrestricted in the app's settings.": "Android hat Starling im Hintergrund gestoppt, weil die Akkunutzung auf Eingeschränkt steht, und das beendet jede Freigabe eine Minute, nachdem du die App verlässt. Stell sie in den App-Einstellungen auf Uneingeschränkt.",
  "Android stopped Starling in the background, so the share ended. Nobody did this by hand.": "Android hat Starling im Hintergrund gestoppt, deshalb endete die Freigabe. Das hat niemand von Hand gemacht.",
  "Android will stop this share when you leave the app": "Android stoppt diese Freigabe, wenn du die App verlässt",
  "Another link, for one more person": "Noch ein Link, für eine weitere Person",
  "Anyone who checks this phone's storage can see that a duress code exists, though not what it is. What they cannot do is tell it apart from your real passcode while typing.": "Wer den Speicher dieses Handys durchsucht, kann sehen, dass es einen Zwangscode gibt, aber nicht, wie er lautet. Was nicht geht: ihn beim Eintippen von deinem echten Passcode zu unterscheiden.",
  "Anyone you send one of these to can watch your live location on any phone or computer, with no app and no account. A link shows this emergency only, never your circle, and never the other links.": "Wem du so einen Link schickst, der kann deinen Live-Standort auf jedem Handy oder Computer verfolgen, ohne App und ohne Konto. Ein Link zeigt nur diesen Notfall, nie deinen Kreis und nie die anderen Links.",
  "App lock is off.": "App-Sperre ist aus.",
  "App lock is on.": "App-Sperre ist an.",
  "Arrive and leave alerts": "Ankommen und Gehen melden",
  "Ask {who} to read out the number on their screen. If it is the new one, accept it. If it is the old one, or they did not reinstall, remove them.": "Bitte {who}, dir die Nummer auf dem eigenen Bildschirm vorzulesen. Ist es die neue, nimm sie an. Ist es die alte, oder gab es keine Neuinstallation, entferne die Person.",
  "Ask to join": "Beitritt anfragen",
  "At {place}": "{place}",
  "Auto": "Automatisch",
  "Auto-lock": "Automatisch sperren",
  "Avatar": "Avatar",
  "Avatar {em}": "Avatar {em}",
  "Basemap": "Grundkarte",
  "Battery {pct} percent": "Akku {pct} Prozent",
  "Battery Saver is turning off your location": "Der Energiesparmodus schaltet deinen Standort ab",
  "behind": "nach",
  "Biometric unlock did not work. Use your passcode.": "Biometrisches Entsperren hat nicht geklappt. Nimm deinen Passcode.",
  "Biometric unlock is off.": "Biometrisches Entsperren ist aus.",
  "Cancel": "Abbrechen",
  "Cancel SOS and check in with your circle": "SOS abbrechen und dich bei deinem Kreis melden",
  "Cancel the request": "Anfrage zurückziehen",
  "Cancel this link": "Diesen Link zurückziehen",
  "Cancel your join request first.": "Zieh zuerst deine Beitrittsanfrage zurück.",
  "Center the map on me": "Karte auf mich zentrieren",
  "Change passcode": "Passcode ändern",
  "Changing where your position goes needs your passcode.": "Um zu ändern, wohin deine Position geht, brauchst du deinen Passcode.",
  "Check": "Prüfen",
  "Check {who}'s number": "Nummer prüfen: {who}",
  "Check again": "Noch mal prüfen",
  "Check in with your circle": "Dich bei deinem Kreis melden",
  "Check the numbers": "Nummern prüfen",
  "Check their safety number with them first. Accepting is what lets them see everyone's location.": "Prüf zuerst gemeinsam die Sicherheitsnummer. Erst das Annehmen lässt die Person den Standort aller sehen.",
  "Check-in delivered. Your circle sees it now.": "Meldung zugestellt. Dein Kreis sieht sie jetzt.",
  "Check-in not delivered yet. Starling keeps trying.": "Meldung noch nicht zugestellt. Starling versucht es weiter.",
  "Check-in queued. Starling keeps trying...": "Meldung wartet. Starling versucht es weiter...",
  "Checked in": "Gemeldet",
  "Choose a passcode to lock Starling on this device. There is no reset: if you forget it, you have to erase this device and rejoin from an invite.": "Wähle einen Passcode, um Starling auf diesem Gerät zu sperren. Es gibt kein Zurücksetzen: Wenn du ihn vergisst, musst du dieses Gerät löschen und mit einer Einladung neu beitreten.",
  "Circle name": "Name des Kreises",
  "Clear status": "Status löschen",
  "Close": "Schließen",
  "Close member card": "Mitgliedskarte schließen",
  "Closing the app stops a share again.": "Die App zu schließen beendet eine Freigabe wieder.",
  "Closing the app will not stop a share now.": "Die App zu schließen beendet eine Freigabe jetzt nicht mehr.",
  "Compare in person": "Persönlich vergleichen",
  "Connected": "Verbunden",
  "Continue": "Weiter",
  "Coordinates copied": "Koordinaten kopiert",
  "Copied. Paste it anywhere you keep your records.": "Kopiert. Füg es ein, wo du deine Unterlagen aufbewahrst.",
  "Copy": "Kopieren",
  "Copy coordinates": "Koordinaten kopieren",
  "Copy failed": "Kopieren fehlgeschlagen",
  "Copy failed. Long-press the link instead.": "Kopieren fehlgeschlagen. Halte stattdessen den Link gedrückt.",
  "Copy it all": "Alles kopieren",
  "Copy link": "Link kopieren",
  "Copy sharing report": "Freigabebericht kopieren",
  "Could not cancel the link. Try again.": "Der Link ließ sich nicht zurückziehen. Versuch es noch mal.",
  "Could not change that setting.": "Diese Einstellung ließ sich nicht ändern.",
  "Could not change the Orbot setting.": "Die Orbot-Einstellung ließ sich nicht ändern.",
  "Could not copy the report.": "Der Bericht ließ sich nicht kopieren.",
  "Could not join. Try again.": "Beitreten hat nicht geklappt. Versuch es noch mal.",
  "Could not leave. Try again.": "Verlassen hat nicht geklappt. Versuch es noch mal.",
  "Could not let them in. Try again.": "Reinlassen hat nicht geklappt. Versuch es noch mal.",
  "Could not make an invite link. Try again.": "Es ließ sich kein Einladungslink erstellen. Versuch es noch mal.",
  "Could not make another link.": "Es ließ sich kein weiterer Link erstellen.",
  "Could not make new keys right now. Try again in a moment.": "Gerade ließen sich keine neuen Schlüssel erzeugen. Versuch es gleich noch mal.",
  "Could not make new keys. Try again.": "Es ließen sich keine neuen Schlüssel erzeugen. Versuch es noch mal.",
  "Could not reach anyone with the new keys. Nothing changed.": "Niemand war mit den neuen Schlüsseln erreichbar. Nichts wurde geändert.",
  "Could not reach the relay to check the time.": "Das Relay war nicht erreichbar, um die Uhrzeit zu prüfen.",
  "Could not reach them to send the keys, so nobody was let in. Try again in a moment.": "Die Person war nicht erreichbar, um die Schlüssel zu senden, also wurde niemand reingelassen. Versuch es gleich noch mal.",
  "Could not remove them. Nothing changed.": "Entfernen hat nicht geklappt. Nichts wurde geändert.",
  "Could not save. Try again.": "Speichern hat nicht geklappt. Versuch es noch mal.",
  "Could not send {who} the keys, and could not undo letting them in. Remove them from the circle before you try again.": "Die Schlüssel ließen sich nicht an {who} senden, und das Reinlassen ließ sich nicht rückgängig machen. Entferne die Person aus dem Kreis, bevor du es noch mal versuchst.",
  "Could not send them the keys, so nobody was let in. Your link still works, so try again.": "Die Schlüssel ließen sich nicht senden, also wurde niemand reingelassen. Dein Link funktioniert noch, versuch es also noch mal.",
  "Could not switch. Try again.": "Wechseln hat nicht geklappt. Versuch es noch mal.",
  "Create a circle": "Einen Kreis erstellen",
  "Create circle": "Kreis erstellen",
  "Current": "Aktuell",
  "Dark": "Dunkel",
  "Demo circle": "Demo-Kreis",
  "Demo flight - nothing is real": "Demo-Flug, nichts hier ist echt",
  "Directions": "Route",
  "Done": "Fertig",
  "Download as a file": "Als Datei herunterladen",
  "Duress passcode removed.": "Zwangs-Passcode entfernt.",
  "Duress passcode saved.": "Zwangs-Passcode gespeichert.",
  "east": "Osten",
  "Encrypts your circle secret on this device. Nobody can open Starling, or read the secret from storage, without your passcode.": "Verschlüsselt dein Kreisgeheimnis auf diesem Gerät. Ohne deinen Passcode kann niemand Starling öffnen oder das Geheimnis aus dem Speicher lesen.",
  "End to end encrypted. This page can read this one emergency share and nothing else.": "Ende-zu-Ende-verschlüsselt. Diese Seite kann diese eine Notfall-Freigabe lesen und sonst nichts.",
  "End-to-end encrypted. No accounts. Open protocol.": "Ende-zu-Ende-verschlüsselt. Keine Konten. Offenes Protokoll.",
  "End-to-end encrypted. The relay sees ciphertext only.": "Ende-zu-Ende-verschlüsselt. Das Relay sieht nur Chiffretext.",
  "English is the app's source language. Translations come from the community; rough edges are worth reporting.": "Englisch ist die Ausgangssprache der App. Übersetzungen kommen aus der Community; holprige Stellen sind eine Meldung wert.",
  "Enter your passcode": "Gib deinen Passcode ein",
  "Enter your passcode to open your circle.": "Gib deinen Passcode ein, um deinen Kreis zu öffnen.",
  "Enter your passcode to stop encrypting the circle secret at rest.": "Gib deinen Passcode ein, um das Kreisgeheimnis auf diesem Gerät nicht mehr verschlüsselt zu speichern.",
  "Erase and start over": "Löschen und neu anfangen",
  "Erases the circle secret, your identity, and all Starling data from this device, then reloads. One residual: street-map tiles your browser cached may remain in its own cache. The Off-grid basemap never loads any. There is no undo. Hold the button to confirm.": "Löscht das Kreisgeheimnis, deine Identität und alle Starling-Daten von diesem Gerät und lädt dann neu. Ein Rest bleibt: Straßenkarten-Kacheln, die dein Browser zwischengespeichert hat, können in seinem eigenen Cache bleiben. Die Grundkarte Ohne Netz lädt nie welche. Es gibt kein Zurück. Halte den Knopf gedrückt, um zu bestätigen.",
  "Every link stops updating and shows that the session ended. A new SOS makes new links.": "Jeder Link hört auf, sich zu aktualisieren, und zeigt an, dass die Sitzung beendet ist. Ein neues SOS erzeugt neue Links.",
  "Everyone else gets new keys. {who} can read nothing this circle sends from now on, and is not told. What they already saw, they keep.": "Alle anderen bekommen neue Schlüssel. {who} kann ab jetzt nichts mehr lesen, was dieser Kreis sendet, und erfährt davon nichts. Was schon gesehen wurde, bleibt gesehen.",
  "Everyone here is checked": "Alle hier sind geprüft",
  "Everyone in the circle gets a fresh key and the old one stops working, so anybody holding a copy of the old one goes dark. Do this if a phone in the circle was taken, unlocked, or handed over. Nobody is removed and nothing on your map disappears.": "Alle im Kreis bekommen einen frischen Schlüssel, und der alte funktioniert nicht mehr, also sieht jeder mit einer Kopie des alten nichts mehr. Mach das, wenn ein Handy im Kreis weggenommen, entsperrt oder weitergegeben wurde. Niemand wird entfernt, und nichts verschwindet von deiner Karte.",
  "Everyone in this circle, their safety numbers, and who you have checked.": "Alle in diesem Kreis, ihre Sicherheitsnummern und wen du geprüft hast.",
  "Everything Starling keeps about you, on this device and nowhere else. Positions are absent because they are never stored; keys are absent on purpose.": "Alles, was Starling über dich speichert, auf diesem Gerät und nirgends sonst. Positionen fehlen, weil sie nie gespeichert werden; Schlüssel fehlen mit Absicht.",
  "Exit": "Beenden",
  "Exit the demo first.": "Beende zuerst die Demo.",
  "Exit the demo to edit your places.": "Beende die Demo, um deine Orte zu bearbeiten.",
  "Exit the demo to invite your people.": "Beende die Demo, um deine Leute einzuladen.",
  "Exit the demo to see your circle's keys.": "Beende die Demo, um die Schlüssel deines Kreises zu sehen.",
  "Exit the demo to set a status.": "Beende die Demo, um einen Status zu setzen.",
  "Expand or collapse the circle sheet": "Kreis-Leiste auf- oder zuklappen",
  "Expires in {left}": "Läuft ab in {left}",
  "for {t}": "seit {t}",
  "For a bug report: versions, permissions, battery settings and counts. It has no locations, no keys and no names in it.": "Für einen Fehlerbericht: Versionen, Berechtigungen, Akku-Einstellungen und Zähler. Keine Standorte, keine Schlüssel und keine Namen drin.",
  "Forgot passcode": "Passcode vergessen",
  "Get help from outside your circle": "Hilfe von außerhalb deines Kreises holen",
  "Get outside help": "Hilfe von außen holen",
  "Get told when your people arrive": "Erfahre, wenn deine Leute ankommen",
  "Give the place a name first.": "Gib dem Ort zuerst einen Namen.",
  "Got it": "Verstanden",
  "Help link": "Hilfe-Link",
  "Help links switched off": "Hilfe-Links abgeschaltet",
  "Hold on, still finishing the last circle change.": "Moment, die letzte Änderung am Kreis wird noch abgeschlossen.",
  "Hold the phones side by side. Every group has to match.": "Haltet die Handys nebeneinander. Jede Gruppe muss übereinstimmen.",
  "Hold to erase everything": "Halten, um alles zu löschen",
  "Hold to erase this device": "Halten, um dieses Gerät zu löschen",
  "Hold to send SOS": "Halten, um SOS zu senden",
  "Holds the screen on while the map is open": "Hält den Bildschirm wach, solange die Karte offen ist",
  "Home": "Zuhause",
  "How far back you can see": "Wie weit du zurückschauen kannst",
  "How you appear to the people you invite. This never leaves your circle.": "So erscheinst du den Leuten, die du einlädst. Das verlässt nie deinen Kreis.",
  "I have an invite": "Ich habe eine Einladung",
  "Invite link": "Einladungslink",
  "Invite link cleared from your clipboard.": "Einladungslink aus der Zwischenablage entfernt.",
  "Invite people": "Leute einladen",
  "Invite QR code": "Einladungs-QR-Code",
  "Invite someone": "Jemanden einladen",
  "Invite your people": "Lade deine Leute ein",
  "It is about {n} minutes {dir}.": "Sie geht etwa {n} Minuten {dir}.",
  "It is back on now that the app is open.": "Die Freigabe läuft wieder, jetzt wo die App offen ist.",
  "Its keys are out of memory and nothing you send arrives any more, but this device could not delete them from its own storage, most likely because there is no room left. They are still on the disk. Free some space and open Starling again to finish clearing it, or use Panic to erase everything now.": "Seine Schlüssel sind aus dem Arbeitsspeicher raus, und nichts, was du sendest, kommt noch an, aber dieses Gerät konnte sie nicht aus seinem eigenen Speicher löschen, sehr wahrscheinlich weil kein Platz mehr frei ist. Sie liegen noch auf dem Datenträger. Schaff etwas Platz und öffne Starling erneut, um das Aufräumen abzuschließen, oder nutze die Panik-Löschung, um jetzt alles zu löschen.",
  "Join a circle": "Einem Kreis beitreten",
  "Join with a link": "Mit Link beitreten",
  "Join with invite": "Mit Einladung beitreten",
  "Just you here so far": "Bisher nur du hier",
  "Keep screen awake": "Bildschirm wach halten",
  "Keep sharing": "Weiter teilen",
  "Keep sharing when the app is closed": "Weiter teilen, wenn die App geschlossen ist",
  "Keep sharing with the screen off": "Weiter teilen bei ausgeschaltetem Bildschirm",
  "Keep this screen on": "Diesen Bildschirm anlassen",
  "Keys changed": "Schlüssel geändert",
  "Keys changed. Check before you trust it.": "Schlüssel geändert. Prüf, bevor du ihnen traust.",
  "Keys older than this window are destroyed on this device and cannot be brought back, by you or by anyone holding the phone.": "Schlüssel, die älter sind als dieses Fenster, werden auf diesem Gerät vernichtet und lassen sich nicht zurückholen, weder von dir noch von jemandem, der das Handy in der Hand hat.",
  "Language": "Sprache",
  "Language saved. Reopen settings to see them translated too.": "Sprache gespeichert. Öffne die Einstellungen neu, dann sind sie auch übersetzt.",
  "Last seen": "Zuletzt gesehen",
  "last sent {ago} ago": "zuletzt gesendet: {ago}",
  "Last update {ago}": "Letztes Update: {ago}",
  "Leave circle": "Kreis verlassen",
  "Leave this circle": "Diesen Kreis verlassen",
  "Light": "Hell",
  "Link cancelled. It cannot be used now.": "Link zurückgezogen. Er lässt sich jetzt nicht mehr benutzen.",
  "Live": "Live",
  "Live · Neighborhood": "Live · Umgebung",
  "Live · Precise": "Live · Genau",
  "Load map": "Karte laden",
  "Locating...": "Ortung läuft...",
  "Location is blocked": "Standort ist blockiert",
  "Location is not available in this browser.": "Standort ist in diesem Browser nicht verfügbar.",
  "Location is off on this phone. Turn it on to keep sharing.": "Der Standort ist auf diesem Handy aus. Schalte ihn ein, um weiter zu teilen.",
  "Location needs HTTPS. Open the deployed app or localhost.": "Standort braucht HTTPS. Öffne die veröffentlichte App oder localhost.",
  "Location permission is off for Starling. Open the app's settings, allow location, then come back and tap Start sharing.": "Die Standortberechtigung für Starling ist aus. Öffne die App-Einstellungen, erlaube den Standort, komm dann zurück und tipp auf Teilen starten.",
  "Location stopped: {reason}": "Standort gestoppt: {reason}",
  "Locked": "Gesperrt",
  "Low battery alerts": "Warnung bei niedrigem Akku",
  "Made by {name}": "Entwickelt von {name}",
  "made it": "angekommen",
  "Make another link": "Noch einen Link erstellen",
  "Make new keys": "Neue Schlüssel erzeugen",
  "Map": "Karte",
  "Mark not verified": "Als nicht verifiziert markieren",
  "Mark verified": "Als verifiziert markieren",
  "Member": "Mitglied",
  "Member details": "Details zum Mitglied",
  "Name the spots that matter and hear about arrivals. Places never leave this phone.": "Benenne die Orte, die zählen, und erfahre von Ankünften. Orte verlassen dieses Handy nie.",
  "Name the spots that matter, like Home or School, and Starling tells you when someone in your circle arrives or leaves. Places are stored only on this phone. They are never sent anywhere, and the relay cannot learn they exist.": "Benenne die Orte, die zählen, etwa Zuhause oder Schule, und Starling sagt dir, wenn jemand aus deinem Kreis ankommt oder geht. Orte werden nur auf diesem Handy gespeichert. Sie werden nirgendwohin gesendet, und das Relay kann nicht erfahren, dass es sie gibt.",
  "Neighborhood": "Umgebung",
  "Neighborhood rounds your position to about 1 km on your device before it is encrypted": "Umgebung rundet deine Position auf deinem Gerät auf etwa 1 km, bevor sie verschlüsselt wird",
  "never": "nie",
  "New circle": "Neuer Kreis",
  "New keys now": "Jetzt neue Schlüssel",
  "New keys were made while this device could not be reached, and they cannot be worked out from the old ones. Nothing you send now arrives. Ask somebody in the circle for a fresh invite link.": "Neue Schlüssel wurden erzeugt, während dieses Gerät nicht erreichbar war, und sie lassen sich nicht aus den alten herleiten. Nichts, was du jetzt sendest, kommt an. Bitte jemanden im Kreis um einen frischen Einladungslink.",
  "New link ready to send.": "Neuer Link bereit zum Senden.",
  "No location fix yet. Still trying...": "Noch keine Ortung. Starling versucht es weiter...",
  "No location yet. Start sharing to place yourself.": "Noch kein Standort. Starte das Teilen, um dich auf die Karte zu setzen.",
  "no position yet": "noch keine Position",
  "No position yet. Start sharing first, or pick the spot on the map.": "Noch keine Position. Starte zuerst das Teilen, oder wähle die Stelle auf der Karte.",
  "No update from anyone in over {n} minutes. Usually that just means phones are asleep. But if others say they are sharing right now, this phone may have missed the circle's new keys; ask any member for a fresh invite to be sure.": "Seit über {n} Minuten kein Update von irgendwem. Meist heißt das nur, dass die Handys schlafen. Aber wenn andere sagen, dass sie gerade teilen, hat dieses Handy vielleicht die neuen Schlüssel des Kreises verpasst; bitte sicherheitshalber ein Mitglied um eine frische Einladung.",
  "Nobody else in this circle yet": "Noch niemand sonst in diesem Kreis",
  "Nobody else is in this circle yet. Invite someone from the map.": "Noch ist niemand sonst in diesem Kreis. Lade jemanden von der Karte aus ein.",
  "Nobody has been heard from in a while": "Von niemandem war eine Weile etwas zu hören",
  "Nobody has told you the circle's real name yet (names travel encrypted, like everything else), so pick whatever you will recognize. Rename it any time in settings.": "Noch hat dir niemand den echten Namen des Kreises gesagt (Namen reisen verschlüsselt, wie alles andere), also nimm, was du wiedererkennst. Umbenennen kannst du ihn jederzeit in den Einstellungen.",
  "north": "Norden",
  "northeast": "Nordosten",
  "northwest": "Nordwesten",
  "not available": "nicht verfügbar",
  "Not connected": "Nicht verbunden",
  "Not now": "Jetzt nicht",
  "Not reaching the relay": "Relay nicht erreichbar",
  "Not reaching your circle": "Kreis nicht erreichbar",
  "not ready yet": "noch nicht bereit",
  "Not sharing": "Teilen aus",
  "Not verified": "Nicht verifiziert",
  "Not visible: this phone's clock is wrong": "Nicht sichtbar: Die Uhr dieses Handys geht falsch",
  "nothing sent yet": "noch nichts gesendet",
  "now": "jetzt",
  "Now": "Jetzt",
  "Numbers match, let them in": "Nummern stimmen überein, reinlassen",
  "Off-grid": "Ohne Netz",
  "omw to the fountain": "unterwegs zum Brunnen",
  "One of your circles expired while this phone was away": "Einer deiner Kreise ist abgelaufen, während dieses Handy weg war",
  "One readable file: profile, settings, places, circle names, who you trust. No positions, because Starling stores none, and no keys, ever.": "Eine lesbare Datei: Profil, Einstellungen, Orte, Kreisnamen, wem du vertraust. Keine Positionen, weil Starling keine speichert, und keine Schlüssel, niemals.",
  "One use only, and it expires in {left}. Accepting somebody uses it up.": "Nur einmal nutzbar, und er läuft ab in {left}. Jemanden anzunehmen verbraucht ihn.",
  "Only if you run a relay yourself. Everyone in your circle has to use the same one, and the invite links you send carry it.": "Nur, wenn du selbst ein Relay betreibst. Alle in deinem Kreis müssen dasselbe nutzen, und die Einladungslinks, die du verschickst, tragen es mit.",
  "Only your own keys can decrypt what you send. The relay stores ciphertext it cannot open.": "Nur deine eigenen Schlüssel können entschlüsseln, was du sendest. Das Relay speichert Chiffretext, den es nicht öffnen kann.",
  "Open app settings": "App-Einstellungen öffnen",
  "Open members": "Mitglieder öffnen",
  "Open Starling to check their number and let them in.": "Öffne Starling, um die Nummer zu prüfen und die Person reinzulassen.",
  "Open Starling to see their live position.": "Öffne Starling, um die Live-Position zu sehen.",
  "Optimized. Android may pause Starling to save battery while the screen is off, which can stop your circle seeing you move. Allowing it to run in the background prevents that.": "Optimiert. Android kann Starling bei ausgeschaltetem Bildschirm pausieren, um Akku zu sparen, und dein Kreis sieht dann womöglich nicht mehr, wie du dich bewegst. Es im Hintergrund laufen zu lassen verhindert das.",
  "Or your own words": "Oder deine eigenen Worte",
  "Panic wipe": "Panik-Löschung",
  "Passcode": "Passcode",
  "Passcode changed.": "Passcode geändert.",
  "Paste the invite link someone sent you. The circle secret stays in the link fragment and never touches a server.": "Füg den Einladungslink ein, den dir jemand geschickt hat. Das Kreisgeheimnis bleibt im Link-Fragment und berührt nie einen Server.",
  "Paused while Tor mode is on, so nothing leaves this phone outside Tor.": "Pausiert, solange der Tor-Modus an ist, damit nichts dieses Handy außerhalb von Tor verlässt.",
  "People and keys": "Personen und Schlüssel",
  "Pick an avatar": "Avatar wählen",
  "Pick on the map": "Auf der Karte wählen",
  "Place name": "Ortsname",
  "Places": "Orte",
  "Point Starling at your own relay if you run one. The relay source ships with the app, so anyone can host it. Leave this empty for the default. A change applies the next time Starling starts.": "Richte Starling auf dein eigenes Relay, wenn du eins betreibst. Der Relay-Quellcode kommt mit der App, also kann es jeder hosten. Lass das Feld leer für den Standard. Eine Änderung gilt beim nächsten Start von Starling.",
  "Precise": "Genau",
  "Precision": "Genauigkeit",
  "Privacy fence": "Sichtschutz",
  "Privacy fence for {name}": "Sichtschutz für {name}",
  "Probably just quiet": "Wahrscheinlich einfach still",
  "Read this out to {who} on a call or in person. The same digits on both screens means nobody is in between.": "Lies {who} das am Telefon oder persönlich vor. Dieselben Ziffern auf beiden Bildschirmen heißen: Niemand sitzt dazwischen.",
  "Real map": "Echte Karte",
  "Recenter": "Zentrieren",
  "Reconnecting": "Verbinde neu",
  "Reconnecting...": "Verbinde neu...",
  "Reject": "Ablehnen",
  "Relay": "Relay",
  "Relay saved. It applies the next time Starling starts.": "Relay gespeichert. Gilt beim nächsten Start von Starling.",
  "Relock after the app has been in the background this long. Locking ends a share unless Keep sharing when the app is closed is on.": "Erneut sperren, wenn die App so lange im Hintergrund war. Sperren beendet eine Freigabe, es sei denn, „Weiter teilen, wenn die App geschlossen ist“ ist an.",
  "Remove": "Entfernen",
  "Remove {name}": "{name} entfernen",
  "Remove duress passcode": "Zwangs-Passcode entfernen",
  "Remove them": "Person entfernen",
  "Request sent. Someone in the circle has to accept it from their phone.": "Anfrage gesendet. Jemand im Kreis muss sie auf seinem Handy annehmen.",
  "Require passcode": "Passcode verlangen",
  "Restricted. Android stops Starling about a minute after you leave it, and a share stops with it. Set battery use to Unrestricted in the app's settings.": "Eingeschränkt. Android stoppt Starling etwa eine Minute, nachdem du es verlässt, und eine Freigabe stoppt mit. Stell die Akkunutzung in den App-Einstellungen auf Uneingeschränkt.",
  "Review the request": "Anfrage ansehen",
  "Revoke": "Widerrufen",
  "Revoked": "Widerrufen",
  "Route through Orbot": "Über Orbot leiten",
  "Running in the background": "Läuft im Hintergrund",
  "Safety number {digits}": "Sicherheitsnummer {digits}",
  "Safety number loading": "Sicherheitsnummer wird geladen",
  "Save": "Speichern",
  "Save duress passcode": "Zwangs-Passcode speichern",
  "Save my current spot": "Meinen aktuellen Standort speichern",
  "Saved. Your circle sees it once you start sharing.": "Gespeichert. Dein Kreis sieht es, sobald du teilst.",
  "See everything Starling has": "Alles sehen, was Starling hat",
  "See who is here": "Sehen, wer hier ist",
  "Send": "Senden",
  "Send it through something you already trust, like Signal. Whoever opens it can ask to join; they are not in until you check their number and accept.": "Schick ihn über etwas, dem du schon vertraust, etwa Signal. Wer ihn öffnet, kann um Beitritt bitten; drin ist die Person erst, wenn du ihre Nummer geprüft und angenommen hast.",
  "Send on the timer even when you have not moved. The relay cannot read a position either way, but a burst of updates while you walk and silence while you sit is a movement trail made of timing alone. This hides that, and costs a little battery.": "Nach Zeitplan senden, auch wenn du dich nicht bewegt hast. Das Relay kann so oder so keine Position lesen, aber viele Updates beim Gehen und Stille beim Sitzen ergeben eine Bewegungsspur allein aus dem Timing. Das verbirgt sie und kostet etwas Akku.",
  "Send the link": "Link senden",
  "Sends relay and map traffic through Orbot's Tor proxy on this device. Needs Orbot installed with Power User Mode on. Orbot's per-app VPN mode also covers Starling with this off.": "Schickt Relay- und Kartenverkehr durch den Tor-Proxy von Orbot auf diesem Gerät. Braucht Orbot mit eingeschaltetem Power User Mode. Der Per-App-VPN-Modus von Orbot deckt Starling auch ab, wenn das hier aus ist.",
  "Sends your own position in OwnTracks format to a server you run, like Reitti, Dawarich or Home Assistant, only while you share. It goes straight from this phone, never through the relay, and your circle's positions never go there. The server gets your precise position whatever the precision setting. With the app lock on, changing it needs your passcode.": "Sendet deine eigene Position im OwnTracks-Format an einen Server, den du betreibst, etwa Reitti, Dawarich oder Home Assistant, nur während du teilst. Sie geht direkt von diesem Handy, nie über das Relay, und die Positionen deines Kreises gehen nie dorthin. Der Server bekommt deine genaue Position, egal wie die Genauigkeit eingestellt ist. Bei eingeschalteter App-Sperre braucht eine Änderung deinen Passcode.",
  "Sent it to the wrong person?": "An die falsche Person geschickt?",
  "Sent with the tracker ID {tid}.": "Gesendet mit der Tracker-ID {tid}.",
  "service error": "Dienstfehler",
  "Session ended": "Sitzung beendet",
  "Set a passcode": "Passcode festlegen",
  "Set a status for your circle": "Setz einen Status für deinen Kreis",
  "Set status": "Status setzen",
  "Set tracker ID": "Tracker-ID festlegen",
  "Settings": "Einstellungen",
  "Share timer": "Zeitlimit fürs Teilen",
  "Shares now keep running while Starling is closed or locked.": "Freigaben laufen jetzt weiter, während Starling geschlossen oder gesperrt ist.",
  "Sharing (pretend)": "Teilst (simuliert)",
  "Sharing live": "Teilst live",
  "Sharing normally stops when you swipe Starling out of recents, because the keys that encrypt each position live in the app. With this on, Starling stays loaded in the background until the share ends, so closing it does not stop it. Anyone holding your unlocked phone can see the app is still running, and it is still holding your keys, so the app lock cannot protect them until the share ends.": "Normalerweise endet das Teilen, wenn du Starling aus den letzten Apps wischst, weil die Schlüssel, die jede Position verschlüsseln, in der App leben. Mit dieser Option bleibt Starling im Hintergrund geladen, bis die Freigabe endet, also beendet das Schließen sie nicht. Wer dein entsperrtes Handy in der Hand hat, sieht, dass die App noch läuft, und sie hält noch deine Schlüssel, also kann die App-Sperre sie nicht schützen, bis die Freigabe endet.",
  "Sharing report copied. It has no locations and no keys in it.": "Freigabebericht kopiert. Keine Standorte und keine Schlüssel drin.",
  "Sharing was on when the app closed, so it is back on.": "Das Teilen war an, als die App geschlossen wurde, also läuft es wieder.",
  "Sharing was stopped from the notification.": "Das Teilen wurde über die Benachrichtigung gestoppt.",
  "Sharing{run}, and this screen has to stay on": "Teilst{run}, und dieser Bildschirm muss anbleiben",
  "Show recent paths on the map": "Letzte Wege auf der Karte zeigen",
  "Show the demo on a real map? Tiles of its Central Park stage load from openstreetmap.org - the demo's only network use.": "Die Demo auf einer echten Karte zeigen? Die Kacheln ihrer Central-Park-Bühne laden von openstreetmap.org, der einzige Netzwerkzugriff der Demo.",
  "Show this safety number large for comparing in person": "Diese Sicherheitsnummer groß anzeigen, um sie persönlich zu vergleichen",
  "Signal lost": "Signal verloren",
  "Somebody already in that circle has to accept your request. Read them your number: {digits}{jumped}": "Jemand, der schon in dem Kreis ist, muss deine Anfrage annehmen. Lies der Person deine Nummer vor: {digits}{jumped}",
  "Somebody else is jamming that invite link, so it cannot be used any more. Nobody was let in. Make a new link and send it again.": "Jemand anderes blockiert diesen Einladungslink, also lässt er sich nicht mehr benutzen. Niemand wurde reingelassen. Erstell einen neuen Link und schick ihn noch mal.",
  "Someone": "Jemand",
  "Someone shared this emergency link with you. Their live position appears here the moment it arrives. Keep this page open.": "Jemand hat diesen Notfall-Link mit dir geteilt. Die Live-Position erscheint hier, sobald sie ankommt. Lass diese Seite offen.",
  "Someone tapped Stop on the sharing notification. If that was not you, check who has access to this phone.": "Jemand hat in der Teilen-Benachrichtigung auf Stopp getippt. Wenn das nicht du warst, prüf, wer Zugriff auf dieses Handy hat.",
  "Someone wants to join": "Jemand möchte beitreten",
  "SOS": "SOS",
  "SOS active": "SOS aktiv",
  "SOS armed · Locating...": "SOS scharf · Ortung läuft...",
  "SOS armed · Location is off": "SOS scharf · Standort ist aus",
  "SOS armed · Not reaching your circle": "SOS scharf · Kreis nicht erreichbar",
  "SOS armed · Sharing live": "SOS scharf · Teilst live",
  "SOS delivered to your circle.": "SOS an deinen Kreis zugestellt.",
  "SOS from {who}": "SOS von {who}",
  "SOS is armed": "SOS ist scharf",
  "SOS not delivered yet. Starling keeps trying.": "SOS noch nicht zugestellt. Starling versucht es weiter.",
  "SOS queued. Starling keeps trying...": "SOS wartet. Starling versucht es weiter...",
  "SOS sent to your circle. Tap the check mark to cancel.": "SOS an deinen Kreis gesendet. Tipp auf das Häkchen, um abzubrechen.",
  "Source code": "Quellcode",
  "south": "Süden",
  "southeast": "Südosten",
  "southwest": "Südwesten",
  "starling": "starling",
  "Starling cannot recover a forgotten passcode. Nothing about your circle leaves your device unencrypted, so there is no reset link. You can erase this device and rejoin your circle from a fresh invite. Hold the button to erase everything on this device.": "Starling kann einen vergessenen Passcode nicht wiederherstellen. Nichts über deinen Kreis verlässt dein Gerät unverschlüsselt, also gibt es keinen Link zum Zurücksetzen. Du kannst dieses Gerät löschen und deinem Kreis mit einer frischen Einladung neu beitreten. Halte den Knopf gedrückt, um alles auf diesem Gerät zu löschen.",
  "Starling hit a problem while starting.": "Starling hatte beim Start ein Problem.",
  "Starling locked itself while you were away, and a locked Starling holds no keys, so the lock ended your share.": "Starling hat sich gesperrt, während du weg warst, und ein gesperrtes Starling hält keine Schlüssel, also hat die Sperre deine Freigabe beendet.",
  "Starling locks itself after a while in the background, and a locked Starling holds no keys, so the lock would end this share.": "Starling sperrt sich nach einer Weile im Hintergrund, und ein gesperrtes Starling hält keine Schlüssel, also würde die Sperre diese Freigabe beenden.",
  "Starling only gets good when your people are on the map. Send them your invite link.": "Starling wird erst gut, wenn deine Leute auf der Karte sind. Schick ihnen deinen Einladungslink.",
  "Starling only has your approximate location": "Starling hat nur deinen ungefähren Standort",
  "Starling throws a circle's keys away rather than carry them for weeks, and that circle passed the point where this device could still read it, so it was erased from this phone. {kept} Ask somebody in that circle for a fresh invite link if you want back in.": "Starling wirft die Schlüssel eines Kreises weg, statt sie wochenlang mitzuschleppen, und dieser Kreis hat den Punkt überschritten, bis zu dem dieses Gerät ihn noch lesen konnte, also wurde er von diesem Handy gelöscht. {kept} Bitte jemanden aus dem Kreis um einen frischen Einladungslink, wenn du wieder rein willst.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this device passed that point while it was away. Its keys are gone from memory and from storage, and so is this phone's own identity in that circle, so nothing you send arrives and nothing sent to you can be read. Ask somebody in the circle for a fresh invite link.": "Starling wirft die Schlüssel eines Kreises weg, statt sie wochenlang mitzuschleppen, und dieses Gerät hat diesen Punkt überschritten, während es weg war. Seine Schlüssel sind aus Arbeitsspeicher und Speicher verschwunden, und mit ihnen die eigene Identität dieses Handys in dem Kreis, also kommt nichts an, was du sendest, und nichts, was dir gesendet wird, lässt sich lesen. Bitte jemanden im Kreis um einen frischen Einladungslink.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this phone passed that point while it was away. The circle was erased from this device, and there was no other circle to fall back to.{lockLine} Ask somebody for a fresh invite link, or start a new circle.": "Starling wirft die Schlüssel eines Kreises weg, statt sie wochenlang mitzuschleppen, und dieses Handy hat diesen Punkt überschritten, während es weg war. Der Kreis wurde von diesem Gerät gelöscht, und es gab keinen anderen Kreis, zu dem Starling wechseln konnte.{lockLine} Bitte jemanden um einen frischen Einladungslink, oder starte einen neuen Kreis.",
  "Starling trusts whoever first answers with keys that match their member id. Reading these numbers out to each other is what turns that into knowing who is on your map.": "Starling vertraut dem, der zuerst mit Schlüsseln antwortet, die zur Mitglieds-ID passen. Erst wenn ihr euch diese Nummern gegenseitig vorlest, wisst ihr wirklich, wer auf deiner Karte ist.",
  "Starling will use {host}.": "Starling wird {host} nutzen.",
  "Starling's battery use is set to Restricted, so Android stops a share about a minute after the app leaves the screen. Set it to Unrestricted in the app's settings to keep sharing with the screen off.": "Die Akkunutzung von Starling steht auf Eingeschränkt, also stoppt Android eine Freigabe etwa eine Minute, nachdem die App vom Bildschirm verschwindet. Stell sie in den App-Einstellungen auf Uneingeschränkt, um bei ausgeschaltetem Bildschirm weiter zu teilen.",
  "Start a new circle": "Neuen Kreis starten",
  "Start fresh": "Neu anfangen",
  "Start sharing": "Teilen starten",
  "Steady sending": "Gleichmäßig senden",
  "Steady sending is on too, so the relay cannot read your movement from the timing.": "Gleichmäßig senden ist auch an, also kann das Relay deine Bewegung nicht aus dem Timing lesen.",
  "Still about {n} minutes out.": "Immer noch etwa {n} Minuten daneben.",
  "Stop by itself:": "Von selbst beenden:",
  "Stop sending": "Senden beenden",
  "Stop sharing with helpers": "Teilen mit Helfern beenden",
  "Stopped": "Gestoppt",
  "stops in {left}": "endet in {left}",
  "Street maps load tiles from OpenStreetMap, which sees your map viewport. Off-grid loads nothing.": "Straßenkarten laden Kacheln von OpenStreetMap, das deinen Kartenausschnitt sieht. Die Grundkarte Ohne Netz lädt nichts.",
  "Switch circle": "Kreis wechseln",
  "Switched to {name}.": "Gewechselt zu {name}.",
  "Tap Keep sharing to let shares run while Starling is closed or locked. The lock then waits until the share ends.": "Tipp auf Weiter teilen, damit Freigaben laufen, während Starling geschlossen oder gesperrt ist. Die Sperre wartet dann, bis die Freigabe endet.",
  "Tap the map where {name} is.": "Tipp auf der Karte dorthin, wo {name} ist.",
  "Tell me when a member's phone drops under 15 percent, before their dot goes dark": "Sag mir, wenn das Handy eines Mitglieds unter 15 Prozent fällt, bevor sein Punkt dunkel wird",
  "Tell me when someone in the circle reaches a place or leaves one": "Sag mir, wenn jemand im Kreis einen Ort erreicht oder verlässt",
  "telling your circle...": "Kreis wird informiert...",
  "That address did not work. Use a full https address.": "Diese Adresse hat nicht funktioniert. Nimm eine vollständige https-Adresse.",
  "That circle expired, and this device could not erase all of it. Open Starling again to finish clearing it.": "Dieser Kreis ist abgelaufen, und dieses Gerät konnte nicht alles davon löschen. Öffne Starling erneut, um das Aufräumen abzuschließen.",
  "That circle expired, and this phone could not erase it": "Dieser Kreis ist abgelaufen, und dieses Handy konnte ihn nicht löschen",
  "That does not look like a Starling invite link.": "Das sieht nicht nach einem Starling-Einladungslink aus.",
  "That invitation arrived incomplete": "Diese Einladung kam unvollständig an",
  "That invitation expired. Make a new link.": "Diese Einladung ist abgelaufen. Erstell einen neuen Link.",
  "That is the lot: {n} places is the cap.": "Mehr geht nicht: {n} Orte sind das Limit.",
  "That is your duress passcode. Pick a different one.": "Das ist dein Zwangs-Passcode. Wähle einen anderen.",
  "That is your own invite link.": "Das ist dein eigener Einladungslink.",
  "That is your unlock passcode. A duress code has to be different.": "Das ist dein Entsperr-Passcode. Ein Zwangscode muss anders sein.",
  "That link is dead. The others still work.": "Dieser Link ist tot. Die anderen funktionieren noch.",
  "That passcode is right, but this install's stored data will not open. Nothing was erased.": "Der Passcode stimmt, aber die gespeicherten Daten dieser Installation lassen sich nicht öffnen. Nichts wurde gelöscht.",
  "That passcode is wrong.": "Der Passcode ist falsch.",
  "That phone is answering with keys this device has never seen. It is a reinstall, or somebody else in {who}'s place, and nothing here can tell you which. Their location stays off your map until you check the number with them and accept it.": "Das andere Handy antwortet mit Schlüsseln, die dieses Gerät noch nie gesehen hat. Entweder eine Neuinstallation, oder jemand anderes gibt sich als {who} aus, und nichts hier kann dir sagen, welches von beidem. Der Standort erscheint nicht auf deiner Karte, bis du die Nummer mit der Person geprüft und die neuen Schlüssel angenommen hast.",
  "That request's keys are malformed. Nobody was let in.": "Die Schlüssel dieser Anfrage sind fehlerhaft. Niemand wurde reingelassen.",
  "That tracker ID did not work.": "Diese Tracker-ID hat nicht funktioniert.",
  "The app lock ended your share": "Die App-Sperre hat deine Freigabe beendet",
  "The app lock had ended your share. It is back on.": "Die App-Sperre hatte deine Freigabe beendet. Sie läuft wieder.",
  "The app lock will end this share": "Die App-Sperre wird diese Freigabe beenden",
  "The app was closed while sharing was on, which stopped it, and opening it again put it back on. If closing it was not you, check who has access to this phone.": "Die App wurde geschlossen, während das Teilen an war, was es gestoppt hat, und das erneute Öffnen hat es wieder gestartet. Wenn nicht du sie geschlossen hast, prüf, wer Zugriff auf dieses Handy hat.",
  "The app was closed while sharing was on, which stops it every time. If that was not you, check who has access to this phone.": "Die App wurde geschlossen, während das Teilen an war, und das stoppt es jedes Mal. Wenn das nicht du warst, prüf, wer Zugriff auf dieses Handy hat.",
  "The clock looks right now. Your circle can see you again.": "Die Uhr geht jetzt richtig. Dein Kreis kann dich wieder sehen.",
  "The demo has its own Real map button. Your choice here applies when you exit.": "Die Demo hat ihren eigenen Knopf Echte Karte. Deine Wahl hier gilt, wenn du sie beendest.",
  "The fountain": "Der Brunnen",
  "The label is for you. It is never sent anywhere.": "Die Bezeichnung ist für dich. Sie wird nie irgendwohin gesendet.",
  "The last send failed: the server answered {code}.": "Das letzte Senden ist fehlgeschlagen: Der Server hat {code} geantwortet.",
  "The last send failed: the server did not answer.": "Das letzte Senden ist fehlgeschlagen: Der Server hat nicht geantwortet.",
  "The last send worked.": "Das letzte Senden hat geklappt.",
  "The link stops working immediately, and any request already waiting on it is dropped. Open Invite again for a fresh one.": "Der Link funktioniert sofort nicht mehr, und jede Anfrage, die schon darauf wartet, wird verworfen. Öffne Einladen erneut für einen frischen.",
  "the person who let you in": "die Person, die dich reingelassen hat",
  "The person who shared this link stopped their emergency share or checked in safe. The last known position stays on the map.": "Die Person, die diesen Link geteilt hat, hat die Notfall-Freigabe beendet oder sich in Sicherheit gemeldet. Die letzte bekannte Position bleibt auf der Karte.",
  "The relay that passes your updates along stores only encrypted data it cannot read, and deletes it after 24 hours. The protocol is open, so anyone can check these claims against the code.": "Das Relay, das deine Updates weiterreicht, speichert nur verschlüsselte Daten, die es nicht lesen kann, und löscht sie nach 24 Stunden. Das Protokoll ist offen, also kann jeder diese Aussagen am Code prüfen.",
  "The SOS is cleared.": "Das SOS ist aufgehoben.",
  "Their dot may go dark soon.": "Der Punkt könnte bald dunkel werden.",
  "Their number is {theirs}. Yours is {mine}. Read them to each other out loud, on a line you already trust. Nothing else in this circle has been checked by a person yet.": "Die Nummer der Person ist {theirs}. Deine ist {mine}. Lest sie euch laut vor, über eine Verbindung, der ihr schon vertraut. Sonst wurde in diesem Kreis noch nichts von einer Person geprüft.",
  "them": "sie",
  "Theme": "Design",
  "They": "sie",
  "They chose the name {who}. Anyone can type any name, so the number below is the only part that proves who they are.": "Die Person hat den Namen {who} gewählt. Jeder kann jeden Namen eintippen, also ist die Nummer unten das Einzige, was beweist, wer sie ist.",
  "This browser is blocking storage. Starling runs, but nothing is saved after you close it.": "Dieser Browser blockiert den Speicher. Starling läuft, aber nach dem Schließen bleibt nichts gespeichert.",
  "This circle uses another relay": "Dieser Kreis nutzt ein anderes Relay",
  "This circle uses the relay at {host}. Asking to join switches Starling to it.": "Dieser Kreis nutzt das Relay auf {host}. Beitritt anfragen stellt Starling darauf um.",
  "This device could not run the lock's key stretching. Nothing was erased; try again, or free some memory.": "Dieses Gerät konnte die Schlüsselableitung der Sperre nicht ausführen. Nichts wurde gelöscht; versuch es noch mal, oder gib etwas Arbeitsspeicher frei.",
  "This help link is no longer active. The last known position stays on the map; ask for a fresh link if the emergency is still going on.": "Dieser Hilfe-Link ist nicht mehr aktiv. Die letzte bekannte Position bleibt auf der Karte; bitte um einen frischen Link, wenn der Notfall noch andauert.",
  "This invitation is for a circle on {host}.": "Diese Einladung ist für einen Kreis auf {host}.",
  "This is taking a while. The person who invited you may not have seen the request yet, or the link may have expired. Reach them however you normally would; a fresh link takes a minute to make.": "Das dauert gerade länger. Vielleicht hat die Person, die dich eingeladen hat, die Anfrage noch nicht gesehen, oder der Link ist abgelaufen. Erreich sie, wie du es sonst auch tust; ein frischer Link ist in einer Minute erstellt.",
  "This is the number your circle should hear from you.": "Das ist die Nummer, die dein Kreis von dir hören sollte.",
  "This link has expired": "Dieser Link ist abgelaufen",
  "This page needs JavaScript. The person's position arrives encrypted and is decrypted here, in your browser, with a key carried in this link that never reaches any server; without JavaScript there is nothing that can do that decryption. If you are on Tor Browser's Safest setting, allow JavaScript for this page to see them.": "Diese Seite braucht JavaScript. Die Position der Person kommt verschlüsselt an und wird hier, in deinem Browser, entschlüsselt, mit einem Schlüssel, der in diesem Link steckt und nie einen Server erreicht; ohne JavaScript gibt es nichts, was diese Entschlüsselung machen könnte. Wenn du den Tor Browser auf der Stufe Am sichersten nutzt, erlaube JavaScript für diese Seite, um die Person zu sehen.",
  "This phone has been offline too long": "Dieses Handy war zu lange offline",
  "This phone's clock is wrong": "Die Uhr dieses Handys geht falsch",
  "This phone's clock is wrong, so your circle cannot see you.{off} Turn on automatic date and time.": "Die Uhr dieses Handys geht falsch, deshalb kann dein Kreis dich nicht sehen.{off} Schalte automatisches Datum und Uhrzeit ein.",
  "This sends a request. Somebody already in the circle has to check your safety number and accept it before you can see anyone, or they you. That check is how they know the request really came from you and not from somebody who got hold of the link.": "Das sendet eine Anfrage. Jemand, der schon im Kreis ist, muss deine Sicherheitsnummer prüfen und annehmen, bevor du jemanden sehen kannst, oder die anderen dich. Durch diese Prüfung wissen sie, dass die Anfrage wirklich von dir kam und nicht von jemandem, der den Link in die Hände bekommen hat.",
  "This session has ended": "Diese Sitzung ist beendet",
  "Those keys are gone": "Diese Schlüssel sind weg",
  "Those new keys are malformed. They were not accepted.": "Diese neuen Schlüssel sind fehlerhaft. Sie wurden nicht angenommen.",
  "Timed share ended. Your circle sees you stopped sharing.": "Zeitlich begrenzte Freigabe beendet. Dein Kreis sieht, dass du nicht mehr teilst.",
  "To join it, put {relay} in Settings, Advanced, Relay, restart Starling and open the link again. Your other circles stop updating while it is set.": "Um beizutreten, trag {relay} unter Einstellungen, Erweitert, Relay ein, starte Starling neu und öffne den Link erneut. Deine anderen Kreise aktualisieren sich nicht, solange das gesetzt ist.",
  "Tracker ID, like phone1 (optional)": "Tracker-ID, etwa phone1 (optional)",
  "Trail": "Spur",
  "Trail history": "Spurverlauf",
  "Try again": "Noch mal versuchen",
  "Turn off app lock": "App-Sperre ausschalten",
  "Turn on app lock": "App-Sperre einschalten",
  "Turned down. Your link still works for whoever it was meant for.": "Abgelehnt. Dein Link funktioniert weiter für die Person, für die er gedacht war.",
  "Unlock": "Entsperren",
  "Unlock with biometrics": "Mit Biometrie entsperren",
  "Unlocking put it back on.": "Das Entsperren hat es wieder gestartet.",
  "Unlocking...": "Entsperre...",
  "Unrestricted. Android lets Starling keep a share going with the screen off.": "Uneingeschränkt. Android lässt Starling eine Freigabe bei ausgeschaltetem Bildschirm weiterlaufen.",
  "Update Starling": "Starling aktualisieren",
  "Use a full https address, like https://your-server/owntracks": "Nimm eine vollständige https-Adresse, etwa https://dein-server/owntracks",
  "Use at least {n} characters.": "Nimm mindestens {n} Zeichen.",
  "Use this device's Face ID, fingerprint, or Windows Hello to unlock. Your passcode still works as backup.": "Entsperre mit Face ID, Fingerabdruck oder Windows Hello dieses Geräts. Dein Passcode funktioniert weiter als Ersatz.",
  "Use up to 64 characters for the tracker ID, on one line.": "Nimm bis zu 64 Zeichen für die Tracker-ID, in einer Zeile.",
  "Use your own relay": "Eigenes Relay nutzen",
  "Verified": "Verifiziert",
  "Waiting for a location...": "Warte auf einen Standort...",
  "Waiting to be let into {name}": "Warte darauf, in {name} reingelassen zu werden",
  "Was": "Vorher",
  "Watch the demo": "Demo ansehen",
  "west": "Westen",
  "What Starling is and how it works &#8599;": "Was Starling ist und wie es funktioniert &#8599;",
  "When you are safe": "Wenn du in Sicherheit bist",
  "While you share, your position also goes to {host}.": "Während du teilst, geht deine Position auch an {host}.",
  "Who could read you": "Wer deine Position lesen könnte",
  "With approximate location, Android updates your position roughly and only about every ten minutes, so your circle sees you jump. Allow precise location in the app's settings for a live share.": "Mit ungefährem Standort aktualisiert Android deine Position nur grob und nur etwa alle zehn Minuten, also sieht dein Kreis dich springen. Erlaube den genauen Standort in den App-Einstellungen für eine Live-Freigabe.",
  "With Battery Saver on, this phone turns location off while the screen is off, so your circle stops seeing you move. Turn Battery Saver off to keep sharing.": "Mit Energiesparmodus schaltet dieses Handy den Standort ab, solange der Bildschirm aus ist, also sieht dein Kreis nicht mehr, wie du dich bewegst. Schalte den Energiesparmodus aus, um weiter zu teilen.",
  "Wrong passcode. Try again.": "Falscher Passcode. Versuch es noch mal.",
  "You": "Du",
  "You already asked to join. They still have to let you in.": "Du hast schon um Beitritt gebeten. Sie müssen dich noch reinlassen.",
  "You have an invite to a circle. Set up how you will appear to the people in it.": "Du hast eine Einladung in einen Kreis. Leg fest, wie du den Leuten darin erscheinst.",
  "You have checked this number with {who}.": "Du hast diese Nummer mit {who} geprüft.",
  "You joined the circle.": "Du bist dem Kreis beigetreten.",
  "You left. Now in {name}.": "Du bist raus. Jetzt in {name}.",
  "You're in": "Du bist drin",
  "Your app lock and your other circles were not touched.": "Deine App-Sperre und deine anderen Kreise wurden nicht angerührt.",
  "Your app lock is untouched and still protects whatever you set up next.": "Deine App-Sperre ist unberührt und schützt weiter, was du als Nächstes einrichtest.",
  "Your browser is blocking location for this site. Allow location in your browser's site settings, then tap Start sharing again.": "Dein Browser blockiert den Standort für diese Seite. Erlaube den Standort in den Seiteneinstellungen deines Browsers und tipp dann noch mal auf Teilen starten.",
  "Your circle cannot see you. The relay refuses anything stamped with a time that far out, so your position is not going anywhere.{off} Turn on automatic date and time, then check again.": "Dein Kreis kann dich nicht sehen. Das Relay lehnt alles ab, was mit einer so weit abweichenden Zeit gestempelt ist, also geht deine Position nirgendwohin.{off} Schalte automatisches Datum und Uhrzeit ein und prüf dann noch mal.",
  "Your circle has new keys, but they could not be saved. If Starling restarts you will need a fresh invitation.": "Dein Kreis hat neue Schlüssel, aber sie ließen sich nicht speichern. Wenn Starling neu startet, brauchst du eine frische Einladung.",
  "Your circle has new keys.": "Dein Kreis hat neue Schlüssel.",
  "Your circle moved on without this phone": "Dein Kreis ist ohne dieses Handy weitergezogen",
  "Your circle now sees you stopped sharing.": "Dein Kreis sieht jetzt, dass du nicht mehr teilst.",
  "Your circle sees an alert at your live position. Tap the check mark above to cancel it and let everyone know you are okay.": "Dein Kreis sieht einen Alarm an deiner Live-Position. Tipp oben auf das Häkchen, um ihn abzubrechen und allen zu sagen, dass es dir gut geht.",
  "Your circles": "Deine Kreise",
  "Your circles use {host}, and Starling talks to one relay at a time.": "Deine Kreise nutzen {host}, und Starling nutzt immer nur ein Relay gleichzeitig.",
  "Your circles use the default relay, and Starling talks to one relay at a time.": "Deine Kreise nutzen das Standard-Relay, und Starling nutzt immer nur ein Relay gleichzeitig.",
  "Your current circle stays. This adds a new one, and you can switch between them from the circle name at the top of the map.": "Dein aktueller Kreis bleibt. Das fügt einen neuen hinzu, und du kannst über den Kreisnamen oben auf der Karte zwischen ihnen wechseln.",
  "Your data": "Deine Daten",
  "Your last share was stopped outside the app": "Deine letzte Freigabe wurde außerhalb der App gestoppt",
  "Your list of members does not match": "Deine Mitgliederliste stimmt nicht überein",
  "Your name": "Dein Name",
  "Your number": "Deine Nummer",
  "Your other circles": "Deine anderen Kreise",
  "Your other circles could not be read and were dropped.": "Deine anderen Kreise ließen sich nicht lesen und wurden verworfen.",
  "Your other circles were not touched.": "Deine anderen Kreise wurden nicht angerührt.",
  "Your own server": "Dein eigener Server",
  "Your people, on your map. Nobody else.": "Deine Leute, auf deiner Karte. Sonst niemand.",
  "Your position goes out as {tid}.": "Deine Position geht als {tid} raus.",
  "Your position goes out with no tracker ID.": "Deine Position geht ohne Tracker-ID raus.",
  "Your position no longer goes to your own server.": "Deine Position geht nicht mehr an deinen eigenen Server.",
  "Your positions are encrypted on this device with a key only your circle holds. There are no accounts, no phone numbers, and no server that can read where you are. Sharing is off until you turn it on, and stopping is one tap.": "Deine Positionen werden auf diesem Gerät mit einem Schlüssel verschlüsselt, den nur dein Kreis hat. Es gibt keine Konten, keine Telefonnummern und keinen Server, der lesen kann, wo du bist. Teilen ist aus, bis du es einschaltest, und Beenden ist ein Fingertipp.",
  "Your request is waiting on the relay. Somebody already in the circle has to check your number and accept it, and they do not have to be online right now.": "Deine Anfrage wartet auf dem Relay. Jemand, der schon im Kreis ist, muss deine Nummer prüfen und annehmen, und muss dafür nicht gerade online sein.",
  "Your request was accepted. Your circle is on the map.": "Deine Anfrage wurde angenommen. Dein Kreis ist auf der Karte.",
  "Your status": "Dein Status",
  "Biometric unlock is on.": "Biometrische Entsperrung ist an.",
  "coffee run": "Kaffee holen",
  "phone's dying": "Akku fast leer",
  "Press and hold to erase": "Zum Löschen gedrückt halten",
  "Press and hold to send SOS": "Für SOS gedrückt halten",
  "Status cleared.": "Status gelöscht.",
  "Status set.": "Status gesetzt.",
  "Tap once more to erase everything": "Noch einmal tippen, um alles zu löschen",
  "Tap once more to send SOS": "Noch einmal tippen, um SOS zu senden",
  "You left the circle.": "Du hast den Kreis verlassen.",
  "You left, but this device could not erase everything. Open Starling again to finish clearing it.": "Du bist raus, aber dieses Gerät konnte nicht alles löschen. Öffne Starling noch einmal, um das Aufräumen abzuschließen.",
  "Your device or browser could not set up biometric unlock.": "Dein Gerät oder Browser konnte die biometrische Entsperrung nicht einrichten.",
  "{who} is already marked verified.": "{who} ist schon als verifiziert markiert.",
  "{who} is answering with different keys right now. Settle that on their card before marking anything.": "{who} antwortet gerade mit anderen Schlüsseln. Kläre das erst auf der Karte der Person, bevor du etwas markierst.",
  "{who} is verified.": "{who} ist verifiziert.",
  "15 s": "15 s",
  "Camera access was turned down. Allow it for Starling in system settings, then try again.": "Der Kamerazugriff wurde abgelehnt. Erlaube ihn für Starling in den Systemeinstellungen und versuch es dann noch einmal.",
  "For {name}. Each circle keeps its own precision and timing.": "Für {name}. Jeder Kreis hat seine eigene Genauigkeit und sein eigenes Tempo.",
  "How often your circle hears from you while you stay put. Moving sends sooner unless Steady sending is on. Slower is easier on the battery. An SOS always goes every 15 seconds.": "Wie oft dein Kreis von dir hört, während du dich nicht bewegst. Bewegung sendet früher, außer Gleichmäßig senden ist an. Langsamer schont den Akku. Ein SOS geht immer alle 15 Sekunden raus.",
  "Let the person checking you scan this with Starling. It holds your member id and your safety number, nothing else.": "Lass die Person, die dich prüft, das hier mit Starling scannen. Es enthält deine Mitglieds-ID und deine Sicherheitsnummer, sonst nichts.",
  "Mark {who} verified": "{who} als verifiziert markieren",
  "No camera found on this device.": "Auf diesem Gerät wurde keine Kamera gefunden.",
  "Point the camera at the code on their screen.": "Richte die Kamera auf den Code auf dem anderen Bildschirm.",
  "Safety number QR code": "QR-Code der Sicherheitsnummer",
  "Scan result": "Scan-Ergebnis",
  "Scan their code": "Code der Person scannen",
  "Scan theirs": "Code scannen",
  "Scanning a code lives in the app. Here, compare the digits.": "Scannen gibt es nur in der App. Vergleiche hier die Ziffern.",
  "Send every": "Senden alle",
  "Show as QR": "Als QR zeigen",
  "That code belongs to nobody in this circle.": "Dieser Code gehört niemandem in diesem Kreis.",
  "That is not a Starling safety number code.": "Das ist kein Starling-Code für eine Sicherheitsnummer.",
  "The camera could not start.": "Die Kamera konnte nicht starten.",
  "The code does not match the keys this phone holds for {who}. That is a reinstall, or somebody in between, and this phone cannot tell which. Do not mark them verified. Read the digits out to each other, and if they still differ, remove them.": "Der Code passt nicht zu den Schlüsseln, die dieses Handy für {who} hat. Das ist eine Neuinstallation oder jemand dazwischen, und dieses Handy kann das nicht unterscheiden. Markiere die Person nicht als verifiziert. Lest euch die Ziffern gegenseitig vor, und wenn sie immer noch nicht übereinstimmen, entferne die Person.",
  "The code matches the keys this phone holds for {who}. Nobody is in between.": "Der Code passt zu den Schlüsseln, die dieses Handy für {who} hat. Niemand sitzt dazwischen.",
  "Your number as a code": "Deine Nummer als Code",
  "Your number is not ready yet.": "Deine Nummer ist noch nicht bereit.",
  "Check-in timer": "Melde-Timer",
  "Get your circle told if you miss a check-in": "Dein Kreis erfährt es, wenn du dich nicht rechtzeitig meldest",
  "Pick how long you need. If you have not checked in when it runs out, your circle is told, even if this phone is off by then. Only checking in stops it.": "Wähle, wie viel Zeit du brauchst. Hast du dich bis zum Ablauf nicht gemeldet, wird dein Kreis benachrichtigt, auch wenn dieses Handy dann aus ist. Nur Melden stoppt ihn.",
  "Check in within": "Melden innerhalb von",
  "Start timer": "Timer starten",
  "Check in now": "Jetzt melden",
  "Check in by {time}": "Melden bis {time}",
  "Start sharing too": "Auch Teilen starten",
  "Sharing is off, so your circle gets the timer and the last position this phone sent, not where you are now.": "Teilen ist aus, also bekommt dein Kreis den Timer und die letzte Position, die dieses Handy gesendet hat, nicht deinen jetzigen Standort.",
  "Timer set. Check in by {time}.": "Timer gestellt. Melden bis {time}.",
  "Timer set, but your circle does not have it yet. Starling keeps trying.": "Timer gestellt, aber dein Kreis hat ihn noch nicht. Starling versucht es weiter.",
  "Check in within 5 minutes, or your circle is told.": "Melde dich in den nächsten 5 Minuten, sonst wird dein Kreis benachrichtigt.",
  "You missed your check-in": "Du hast dich nicht rechtzeitig gemeldet",
  "Your circle has been told. Check in now if you are okay.": "Dein Kreis wurde benachrichtigt. Melde dich jetzt, wenn alles in Ordnung ist.",
  "{who} missed their check-in": "{who} hat sich nicht rechtzeitig gemeldet",
  "Their timer ran out at {time}. Their last position is on the map.": "Der Timer ist um {time} abgelaufen. Die letzte Position ist auf der Karte.",
  "Their last position is on the map.": "Die letzte Position ist auf der Karte.",
  "Show on map": "Auf der Karte zeigen",
  "Missed check-in": "Nicht gemeldet",
  "Your check-in timer is running in {circle}. Check in there before you switch?": "Dein Melde-Timer läuft in {circle}. Dich dort melden, bevor du wechselst?",
  "Check in and switch": "Melden und wechseln",
  "Exit the demo to set a check-in timer.": "Beende die Demo, um einen Melde-Timer zu stellen.",
  "Their live position is on the map. It stays here until they check in.": "Die Live-Position ist auf der Karte. Das bleibt hier, bis die Person sich meldet.",
  "{who}'s phone stopped sending {ago} ago. The last position it sent is on the map.": "Das Handy von {who} sendet seit {ago} nichts mehr. Die zuletzt gesendete Position ist auf der Karte.",
  "{who}'s SOS went quiet": "Das SOS von {who} ist verstummt",
  "Alerts": "Hinweise",
  "{name} alerts": "Hinweise für {name}",
  "Both": "Beides",
  "Arrive": "Ankunft",
  "Leave": "Weggang",
  "Off": "Aus",
  "Your battery is at {pct}%": "Dein Akku ist bei {pct} %",
  "Sending every 5 minutes instead of every 15 seconds makes it last longer. An SOS still goes out every 15 seconds.": "Alle 5 Minuten statt alle 15 Sekunden zu senden, lässt ihn länger halten. Ein SOS geht weiterhin alle 15 Sekunden raus.",
  "Every 5 minutes": "Alle 5 Minuten",
  "Accurate to about {dist}": "Genau auf etwa {dist}",
  "Phone battery {pct}%": "Handy-Akku: {pct} %",
  "Link works until {time}": "Link gültig bis {time}",
  "Open in a map app": "In einer Karten-App öffnen",
};
