// Brazilian Portuguese catalog: normalized English source -> Brazilian Portuguese.
// Written in the register Signal uses in pt-BR: você, short sentences, plain
// words. Native-speaker review is welcome and rough edges deserve bug reports.
// Regenerate the key list with: node tools/extract-strings.mjs
// Missing entries fall back to English by design.
export const pt = {
  "Scan a code": "Escanear um código",
  "Scan an invite code": "Escanear um código de convite",
  "Point the camera at the invite code on their screen.": "Aponte a câmera para o código de convite na tela da outra pessoa.",
  "That is a safety number code, not an invite.": "Esse é um código de número de segurança, não um convite.",
  "That is not a Starling invite code.": "Isso não é um código de convite do Starling.",
  "Remind me if sharing stays off": "Me lembrar se o compartilhamento continuar desligado",
  "If you stop sharing and do not turn it back on, this phone shows a notification after that long. Nothing goes to your circle.": "Se você parar de compartilhar e não ativar de novo, este celular mostra uma notificação depois desse tempo. Nada vai para o seu círculo.",
  "Never": "Nunca",
  "1 h": "1 h",
  "4 h": "4 h",
  "12 h": "12 h",
  "SOS and Do Not Disturb": "SOS e Não perturbe",
  "An SOS from your circle rings through Do Not Disturb when alarms are allowed. To let it through total silence too, turn on Override Do Not Disturb for Emergency alerts.": "Um SOS do seu círculo toca mesmo com o Não perturbe ativo, quando os alarmes são permitidos. Para que ele toque também no silêncio total, ative Ignorar Não perturbe em Alertas de emergência.",
  "Open emergency alert settings": "Abrir configurações de alertas de emergência",
  "{dist} to the {way} of you": "{dist} ao {way} de você",
  "{failed} of {total} members did not get the new keys yet.": "{failed} de {total} membros ainda não receberam as novas chaves.",
  "{n} members' keys changed": "As chaves de {n} membros mudaram",
  "{n} sets of keys besides yours can decrypt what you send: {checked} checked by a person, {unchecked} trusted on first use.": "{n} conjuntos de chaves além do seu podem descriptografar o que você envia: {checked} verificados por uma pessoa, {unchecked} confiados no primeiro uso.",
  "{name} radius": "Raio de {name}",
  "{name} saved. Only this phone knows it exists.": "Lugar salvo: {name}. Só este celular sabe que ele existe.",
  "{who} arrived at {place}": "{who} chegou em {place}",
  "{who} can read nothing this circle sends from now on. Everyone still here got new keys.": "{who} não consegue mais ler nada que este círculo envia de agora em diante. Quem continua aqui recebeu novas chaves.",
  "{who} changed the keys": "{who} mudou as chaves",
  "{who} changed the keys.": "{who} mudou as chaves.",
  "{who} checked in": "{who} avisou que está bem",
  "{who} is answering with different keys. That is a reinstall, or somebody else in their place, and this phone cannot tell which. Their location stays off your map until you accept.": "{who} está respondendo com chaves diferentes. Pode ser uma reinstalação, ou alguém no lugar dessa pessoa, e este celular não tem como saber qual. A localização fica fora do seu mapa até você aceitar.",
  "{who} is now pinned to the new keys.": "As novas chaves de {who} agora estão fixadas.",
  "{who} is out. Everyone else has new keys.": "{who} está fora. Todos os outros têm novas chaves.",
  "{who} joined. Everyone got new keys.": "{who} entrou. Todos receberam novas chaves.",
  "{who} left {place}": "{who} saiu de {place}",
  "{who} made new keys, but your list of members does not match theirs.": "{who} gerou novas chaves, mas sua lista de membros não bate com a lista dessa pessoa.",
  "{who} removed {gone}": "{who} removeu {gone}",
  "{who} removed {gone}.": "{who} removeu {gone}.",
  "{who} removed {n} people": "{who} removeu {n} pessoas",
  "{who} removed {n} people from the circle.": "{who} removeu {n} pessoas do círculo.",
  "{who} wants to join": "{who} quer entrar",
  "{who} wants to join. Check their safety number.": "{who} quer entrar. Verifique o número de segurança dessa pessoa.",
  "{who}'s keys changed": "As chaves de {who} mudaram",
  "{who}'s keys changed. Their location is hidden until you accept it.": "As chaves de {who} mudaram. A localização fica oculta até você aceitar.",
  "{who}'s phone is at {pct}%": "O celular de {who} está com {pct}%",
  "1 hr": "1 h",
  "1 min": "1 min",
  "5 min": "5 min",
  "A circle holds {n} people and yours is full. Remove somebody before letting anyone else in.": "Um círculo comporta {n} pessoas, e o seu está cheio. Remova alguém antes de deixar outra pessoa entrar.",
  "A few words your circle sees next to your name. It is encrypted like everything else, and it clears when you stop sharing.": "Algumas palavras que seu círculo vê ao lado do seu nome. São criptografadas como todo o resto, e somem quando você para de compartilhar.",
  "a member": "um membro",
  "A member": "Um membro",
  "A member's keys changed": "As chaves de um membro mudaram",
  "A newly admitted key can also read back {window} of history. That window is yours to set in Settings.": "Uma chave recém-admitida também consegue ler {window} de histórico para trás. Essa janela é você quem define, em Configurações.",
  "A place with the privacy fence on shares only its center while you are inside it, never your exact spot within. Your circle still sees you are there; what they stop seeing is where in there. An SOS always sends your real position.": "Um lugar com a cerca de privacidade ligada compartilha só o centro dele enquanto você está lá dentro, nunca seu ponto exato ali. Seu círculo continua vendo que você está lá; o que deixa de ver é em que parte. Um SOS sempre envia sua posição real.",
  "A relay must be an https URL, like https://relay.example.org": "O relay precisa ser uma URL https, como https://relay.example.org",
  "A second passcode for a moment when someone makes you open Starling. Entering it on the lock screen erases everything on this device, instantly and silently, and shows a fresh install. There is no undo and no way back in. It only guards the passcode path: biometric unlock still opens the app normally, so if a forced unlock is in your threat model, turn biometrics off too.": "Uma segunda senha para o momento em que alguém obriga você a abrir o Starling. Digitá-la na tela de bloqueio apaga tudo neste dispositivo, na hora e em silêncio, e mostra uma instalação nova. Não dá para desfazer nem para voltar a entrar. Ela só protege o caminho da senha: o desbloqueio biométrico continua abrindo o app normalmente, então, se um desbloqueio forçado faz parte do seu modelo de ameaças, desligue a biometria também.",
  "A tracker ID goes out as tid with each position, so a forwarder or Home Assistant can tell this phone apart.": "Um ID de rastreador sai como tid com cada posição, para que um encaminhador ou o Home Assistant consiga distinguir este celular.",
  "A welcome arrived that did not match the person this link came from, and it was refused. That can be an interception attempt, or just a stale retry or a network hiccup. Your request is still waiting for the person who actually invited you; check with them before using the link again.": "Chegou uma mensagem de boas-vindas que não batia com a pessoa de quem este link veio, e ela foi recusada. Pode ser uma tentativa de interceptação, ou só um reenvio atrasado ou uma falha de rede. Seu pedido continua esperando a pessoa que realmente convidou você; fale com ela antes de usar o link de novo.",
  "A welcome that did not match the link's sender was refused. That can be an interception attempt, or just a stale retry. Check with whoever gave you the link before you use it again.": "Uma mensagem de boas-vindas que não batia com quem enviou o link foi recusada. Pode ser uma tentativa de interceptação, ou só um reenvio atrasado. Fale com quem deu o link a você antes de usá-lo de novo.",
  "Accept the new keys": "Aceitar as novas chaves",
  "Accepting gives the whole circle new keys and lets them see everyone's location from then on. They cannot read anything sent before.": "Aceitar dá novas chaves ao círculo inteiro e permite que essa pessoa veja a localização de todos a partir daí. Ela não consegue ler nada enviado antes.",
  "Add Starling to your home screen": "Adicione o Starling à tela inicial",
  "ahead": "adiantado",
  "Allow": "Permitir",
  "Allow background running": "Permitir execução em segundo plano",
  "also to {host}": "também para {host}",
  "Android had stopped your share in the background. It is back on.": "O Android tinha parado seu compartilhamento em segundo plano. Ele voltou a ficar ativo.",
  "Android kept Starling from running in the background, so your circle stopped getting your location and the share ended. Nobody did this by hand.": "O Android impediu o Starling de rodar em segundo plano, então seu círculo parou de receber sua localização e o compartilhamento terminou. Não foi ninguém que fez isso.",
  "Android may pause Starling to save battery while your screen is off, and your circle would stop seeing you move. Letting Starling run in the background stops that. It only makes a difference while you share.": "O Android pode pausar o Starling para economizar bateria enquanto sua tela está desligada, e seu círculo deixaria de ver você se mover. Deixar o Starling rodar em segundo plano evita isso. Só faz diferença enquanto você compartilha.",
  "Android shut down the part of Starling that sends your position, so the share stopped. Nobody did this by hand.": "O Android encerrou a parte do Starling que envia sua posição, então o compartilhamento parou. Não foi ninguém que fez isso.",
  "Android stopped Starling in the background because its battery use is set to Restricted, and that ends every share a minute after you leave the app. Set it to Unrestricted in the app's settings.": "O Android parou o Starling em segundo plano porque o uso de bateria dele está como Restrito, e isso encerra todo compartilhamento um minuto depois de você sair do app. Mude para Sem restrições nas configurações do app.",
  "Android stopped Starling in the background, so the share ended. Nobody did this by hand.": "O Android parou o Starling em segundo plano, então o compartilhamento terminou. Não foi ninguém que fez isso.",
  "Android will stop this share when you leave the app": "O Android vai parar este compartilhamento quando você sair do app",
  "Another link, for one more person": "Outro link, para mais uma pessoa",
  "Anyone who checks this phone's storage can see that a duress code exists, though not what it is. What they cannot do is tell it apart from your real passcode while typing.": "Qualquer pessoa que examine o armazenamento deste celular consegue ver que existe uma senha de coação, mas não qual é. O que ela não consegue é distingui-la da sua senha real enquanto você digita.",
  "Anyone you send one of these to can watch your live location on any phone or computer, with no app and no account. A link shows this emergency only, never your circle, and never the other links.": "Qualquer pessoa para quem você enviar um destes pode acompanhar sua localização ao vivo em qualquer celular ou computador, sem app e sem conta. Um link mostra só esta emergência, nunca seu círculo, e nunca os outros links.",
  "App lock is off.": "O bloqueio do app está desligado.",
  "App lock is on.": "O bloqueio do app está ligado.",
  "Arrive and leave alerts": "Alertas de chegada e saída",
  "Ask {who} to read out the number on their screen. If it is the new one, accept it. If it is the old one, or they did not reinstall, remove them.": "Peça para {who} ler em voz alta o número que aparece na tela. Se for o novo, aceite. Se for o antigo, ou se não houve reinstalação, remova essa pessoa.",
  "Ask to join": "Pedir para entrar",
  "At {place}": "Em {place}",
  "Auto": "Automático",
  "Auto-lock": "Bloqueio automático",
  "Avatar": "Avatar",
  "Avatar {em}": "Avatar {em}",
  "Basemap": "Mapa base",
  "Battery {pct} percent": "Bateria em {pct} por cento",
  "Battery Saver is turning off your location": "A Economia de bateria está desligando sua localização",
  "behind": "atrasado",
  "Biometric unlock did not work. Use your passcode.": "O desbloqueio biométrico não funcionou. Use sua senha.",
  "Biometric unlock is off.": "O desbloqueio biométrico está desligado.",
  "Cancel": "Cancelar",
  "Cancel SOS and check in with your circle": "Cancelar o SOS e avisar seu círculo que você está bem",
  "Cancel the request": "Cancelar o pedido",
  "Cancel this link": "Cancelar este link",
  "Cancel your join request first.": "Primeiro cancele seu pedido para entrar.",
  "Center the map on me": "Centralizar o mapa em mim",
  "Change passcode": "Alterar senha",
  "Changing where your position goes needs your passcode.": "Mudar para onde sua posição vai exige sua senha.",
  "Check": "Verificar",
  "Check {who}'s number": "Verificar o número de {who}",
  "Check again": "Verificar de novo",
  "Check in with your circle": "Avisar seu círculo que você está bem",
  "Check the numbers": "Verificar os números",
  "Check their safety number with them first. Accepting is what lets them see everyone's location.": "Verifique o número de segurança com essa pessoa primeiro. Aceitar é o que permite que ela veja a localização de todos.",
  "Check-in delivered. Your circle sees it now.": "Aviso entregue. Seu círculo já está vendo.",
  "Check-in not delivered yet. Starling keeps trying.": "Aviso ainda não entregue. O Starling continua tentando.",
  "Check-in queued. Starling keeps trying...": "Aviso na fila. O Starling continua tentando...",
  "Checked in": "Está bem",
  "Choose a passcode to lock Starling on this device. There is no reset: if you forget it, you have to erase this device and rejoin from an invite.": "Escolha uma senha para bloquear o Starling neste dispositivo. Não existe redefinição: se você esquecer, vai ter que apagar este dispositivo e entrar de novo por um convite.",
  "Circle name": "Nome do círculo",
  "Clear status": "Limpar status",
  "Close": "Fechar",
  "Close member card": "Fechar o cartão do membro",
  "Closing the app stops a share again.": "Fechar o app volta a parar o compartilhamento.",
  "Closing the app will not stop a share now.": "Fechar o app não para mais o compartilhamento.",
  "Compare in person": "Comparar pessoalmente",
  "Connected": "Conectado",
  "Continue": "Continuar",
  "Coordinates copied": "Coordenadas copiadas",
  "Copied. Paste it anywhere you keep your records.": "Copiado. Cole onde você guarda seus registros.",
  "Copy": "Copiar",
  "Copy coordinates": "Copiar coordenadas",
  "Copy failed": "Não foi possível copiar",
  "Copy failed. Long-press the link instead.": "Não foi possível copiar. Toque e segure o link em vez disso.",
  "Copy it all": "Copiar tudo",
  "Copy link": "Copiar link",
  "Copy sharing report": "Copiar relatório de compartilhamento",
  "Could not cancel the link. Try again.": "Não foi possível cancelar o link. Tente de novo.",
  "Could not change that setting.": "Não foi possível mudar essa configuração.",
  "Could not change the Orbot setting.": "Não foi possível mudar a configuração do Orbot.",
  "Could not copy the report.": "Não foi possível copiar o relatório.",
  "Could not join. Try again.": "Não foi possível entrar. Tente de novo.",
  "Could not leave. Try again.": "Não foi possível sair. Tente de novo.",
  "Could not let them in. Try again.": "Não foi possível deixar a pessoa entrar. Tente de novo.",
  "Could not make an invite link. Try again.": "Não foi possível criar um link de convite. Tente de novo.",
  "Could not make another link.": "Não foi possível criar outro link.",
  "Could not make new keys right now. Try again in a moment.": "Não foi possível gerar novas chaves agora. Tente de novo daqui a pouco.",
  "Could not make new keys. Try again.": "Não foi possível gerar novas chaves. Tente de novo.",
  "Could not reach anyone with the new keys. Nothing changed.": "Não foi possível entregar as novas chaves a ninguém. Nada mudou.",
  "Could not reach the relay to check the time.": "Não foi possível conectar ao relay para verificar a hora.",
  "Could not reach them to send the keys, so nobody was let in. Try again in a moment.": "Não foi possível contatar a pessoa para enviar as chaves, então ninguém entrou. Tente de novo daqui a pouco.",
  "Could not remove them. Nothing changed.": "Não foi possível remover a pessoa. Nada mudou.",
  "Could not save. Try again.": "Não foi possível salvar. Tente de novo.",
  "Could not send {who} the keys, and could not undo letting them in. Remove them from the circle before you try again.": "Não foi possível enviar as chaves para {who}, nem desfazer a entrada. Remova essa pessoa do círculo antes de tentar de novo.",
  "Could not send them the keys, so nobody was let in. Your link still works, so try again.": "Não foi possível enviar as chaves, então ninguém entrou. Seu link ainda funciona, então tente de novo.",
  "Could not switch. Try again.": "Não foi possível trocar. Tente de novo.",
  "Create a circle": "Criar um círculo",
  "Create circle": "Criar círculo",
  "Current": "Atual",
  "Dark": "Escuro",
  "Demo circle": "Círculo de demonstração",
  "Demo flight - nothing is real": "Voo de demonstração, nada é real",
  "Directions": "Como chegar",
  "Done": "Pronto",
  "Download as a file": "Baixar como arquivo",
  "Duress passcode removed.": "Senha de coação removida.",
  "Duress passcode saved.": "Senha de coação salva.",
  "east": "leste",
  "Encrypts your circle secret on this device. Nobody can open Starling, or read the secret from storage, without your passcode.": "Criptografa o segredo do seu círculo neste dispositivo. Ninguém consegue abrir o Starling, nem ler o segredo do armazenamento, sem a sua senha.",
  "End to end encrypted. This page can read this one emergency share and nothing else.": "Criptografado de ponta a ponta. Esta página consegue ler só este compartilhamento de emergência e nada mais.",
  "End-to-end encrypted. No accounts. Open protocol.": "Criptografia de ponta a ponta. Sem contas. Protocolo aberto.",
  "End-to-end encrypted. The relay sees ciphertext only.": "Criptografia de ponta a ponta. O relay só vê texto cifrado.",
  "English is the app's source language. Translations come from the community; rough edges are worth reporting.": "O inglês é o idioma de origem do app. As traduções vêm da comunidade; vale a pena relatar o que soar estranho.",
  "Enter your passcode": "Digite sua senha",
  "Enter your passcode to open your circle.": "Digite sua senha para abrir seu círculo.",
  "Enter your passcode to stop encrypting the circle secret at rest.": "Digite sua senha para parar de criptografar o segredo do círculo armazenado neste dispositivo.",
  "Erase and start over": "Apagar e começar de novo",
  "Erases the circle secret, your identity, and all Starling data from this device, then reloads. One residual: street-map tiles your browser cached may remain in its own cache. The Off-grid basemap never loads any. There is no undo. Hold the button to confirm.": "Apaga o segredo do círculo, sua identidade e todos os dados do Starling deste dispositivo, e depois recarrega. Um resíduo: blocos do mapa de ruas que seu navegador guardou podem continuar no cache dele. O mapa base Sem rede nunca carrega nenhum. Não dá para desfazer. Segure o botão para confirmar.",
  "Every link stops updating and shows that the session ended. A new SOS makes new links.": "Todo link para de atualizar e mostra que a sessão terminou. Um novo SOS cria novos links.",
  "Everyone else gets new keys. {who} can read nothing this circle sends from now on, and is not told. What they already saw, they keep.": "Todos os outros recebem novas chaves. {who} não consegue ler nada que este círculo envia de agora em diante, e não recebe aviso. O que já viu, continua tendo.",
  "Everyone here is checked": "Todos aqui foram verificados",
  "Everyone in the circle gets a fresh key and the old one stops working, so anybody holding a copy of the old one goes dark. Do this if a phone in the circle was taken, unlocked, or handed over. Nobody is removed and nothing on your map disappears.": "Todos no círculo recebem uma chave nova e a antiga para de funcionar, então quem tiver uma cópia da antiga fica no escuro. Faça isso se um celular do círculo foi tomado, desbloqueado ou entregue a alguém. Ninguém é removido e nada some do seu mapa.",
  "Everyone in this circle, their safety numbers, and who you have checked.": "Todos neste círculo, seus números de segurança e quem você já verificou.",
  "Everything Starling keeps about you, on this device and nowhere else. Positions are absent because they are never stored; keys are absent on purpose.": "Tudo que o Starling guarda sobre você, neste dispositivo e em nenhum outro lugar. Não há posições porque elas nunca são armazenadas; não há chaves, de propósito.",
  "Exit": "Sair",
  "Exit the demo first.": "Saia da demonstração primeiro.",
  "Exit the demo to edit your places.": "Saia da demonstração para editar seus lugares.",
  "Exit the demo to invite your people.": "Saia da demonstração para convidar seu pessoal.",
  "Exit the demo to see your circle's keys.": "Saia da demonstração para ver as chaves do seu círculo.",
  "Exit the demo to set a status.": "Saia da demonstração para definir um status.",
  "Expand or collapse the circle sheet": "Expandir ou recolher o painel do círculo",
  "Expires in {left}": "Expira em {left}",
  "for {t}": "por {t}",
  "For a bug report: versions, permissions, battery settings and counts. It has no locations, no keys and no names in it.": "Para relatar um erro: versões, permissões, configurações de bateria e contagens. Não tem localizações, chaves nem nomes.",
  "Forgot passcode": "Esqueci a senha",
  "Get help from outside your circle": "Peça ajuda de fora do seu círculo",
  "Get outside help": "Pedir ajuda externa",
  "Get told when your people arrive": "Saiba quando seu pessoal chegar",
  "Give the place a name first.": "Dê um nome ao lugar primeiro.",
  "Got it": "Entendi",
  "Help link": "Link de ajuda",
  "Help links switched off": "Links de ajuda desligados",
  "Hold on, still finishing the last circle change.": "Espere, a última mudança do círculo ainda está terminando.",
  "Hold the phones side by side. Every group has to match.": "Segure os celulares lado a lado. Todos os grupos têm que bater.",
  "Hold to erase everything": "Segure para apagar tudo",
  "Hold to erase this device": "Segure para apagar este dispositivo",
  "Hold to send SOS": "Segure para enviar SOS",
  "Holds the screen on while the map is open": "Mantém a tela ligada enquanto o mapa está aberto",
  "Home": "Casa",
  "How far back you can see": "Até onde você consegue ver para trás",
  "How you appear to the people you invite. This never leaves your circle.": "Como você aparece para as pessoas que convida. Isso nunca sai do seu círculo.",
  "I have an invite": "Tenho um convite",
  "Invite link": "Link de convite",
  "Invite link cleared from your clipboard.": "Link de convite apagado da área de transferência.",
  "Invite people": "Convidar pessoas",
  "Invite QR code": "QR code do convite",
  "Invite someone": "Convidar alguém",
  "Invite your people": "Convide seu pessoal",
  "It is about {n} minutes {dir}.": "Está uns {n} minutos {dir}.",
  "It is back on now that the app is open.": "Voltou a ficar ativo agora que o app está aberto.",
  "Its keys are out of memory and nothing you send arrives any more, but this device could not delete them from its own storage, most likely because there is no room left. They are still on the disk. Free some space and open Starling again to finish clearing it, or use Panic to erase everything now.": "As chaves dele saíram da memória e nada que você envia chega mais, mas este dispositivo não conseguiu apagá-las do próprio armazenamento, provavelmente porque não sobrou espaço. Elas ainda estão no disco. Libere espaço e abra o Starling de novo para terminar a limpeza, ou use o Apagamento de pânico para apagar tudo agora.",
  "Join a circle": "Entrar em um círculo",
  "Join with a link": "Entrar com um link",
  "Join with invite": "Entrar com convite",
  "Just you here so far": "Por enquanto, só você aqui",
  "Keep screen awake": "Manter a tela ligada",
  "Keep sharing": "Continuar compartilhando",
  "Keep sharing when the app is closed": "Continuar compartilhando com o app fechado",
  "Keep sharing with the screen off": "Continuar compartilhando com a tela desligada",
  "Keep this screen on": "Manter esta tela ligada",
  "Keys changed": "As chaves mudaram",
  "Keys changed. Check before you trust it.": "As chaves mudaram. Verifique antes de confiar.",
  "Keys older than this window are destroyed on this device and cannot be brought back, by you or by anyone holding the phone.": "Chaves mais antigas que essa janela são destruídas neste dispositivo e não podem ser recuperadas, nem por você nem por quem estiver com o celular.",
  "Language": "Idioma",
  "Language saved. Reopen settings to see them translated too.": "Idioma salvo. Reabra as configurações para vê-las traduzidas também.",
  "Last seen": "Visto por último",
  "last sent {ago} ago": "último envio há {ago}",
  "Last update {ago}": "Última atualização: {ago}",
  "Leave circle": "Sair do círculo",
  "Leave this circle": "Sair deste círculo",
  "Light": "Claro",
  "Link cancelled. It cannot be used now.": "Link cancelado. Não pode mais ser usado.",
  "Live": "Ao vivo",
  "Live · Neighborhood": "Ao vivo · Bairro",
  "Live · Precise": "Ao vivo · Exata",
  "Load map": "Carregar mapa",
  "Locating...": "Localizando...",
  "Location is blocked": "A localização está bloqueada",
  "Location is not available in this browser.": "A localização não está disponível neste navegador.",
  "Location is off on this phone. Turn it on to keep sharing.": "A localização está desligada neste celular. Ligue para continuar compartilhando.",
  "Location needs HTTPS. Open the deployed app or localhost.": "A localização precisa de HTTPS. Abra o app publicado ou localhost.",
  "Location permission is off for Starling. Open the app's settings, allow location, then come back and tap Start sharing.": "A permissão de localização está desligada para o Starling. Abra as configurações do app, permita a localização, depois volte e toque em Começar a compartilhar.",
  "Location stopped: {reason}": "A localização parou: {reason}",
  "Locked": "Bloqueado",
  "Low battery alerts": "Alertas de bateria fraca",
  "Made by {name}": "Feito por {name}",
  "made it": "cheguei",
  "Make another link": "Criar outro link",
  "Make new keys": "Gerar novas chaves",
  "Map": "Mapa",
  "Mark not verified": "Marcar como não verificado",
  "Mark verified": "Marcar como verificado",
  "Member": "Membro",
  "Member details": "Detalhes do membro",
  "Name the spots that matter and hear about arrivals. Places never leave this phone.": "Dê nome aos pontos que importam e fique sabendo das chegadas. Os lugares nunca saem deste celular.",
  "Name the spots that matter, like Home or School, and Starling tells you when someone in your circle arrives or leaves. Places are stored only on this phone. They are never sent anywhere, and the relay cannot learn they exist.": "Dê nome aos pontos que importam, como Casa ou Escola, e o Starling avisa quando alguém do seu círculo chega ou sai. Os lugares ficam guardados só neste celular. Nunca são enviados a lugar nenhum, e o relay não tem como saber que existem.",
  "Neighborhood": "Bairro",
  "Neighborhood rounds your position to about 1 km on your device before it is encrypted": "Bairro arredonda sua posição para cerca de 1 km no seu dispositivo antes de criptografá-la",
  "never": "nunca",
  "New circle": "Novo círculo",
  "New keys now": "Novas chaves agora",
  "New keys were made while this device could not be reached, and they cannot be worked out from the old ones. Nothing you send now arrives. Ask somebody in the circle for a fresh invite link.": "Novas chaves foram geradas enquanto este dispositivo estava inacessível, e elas não podem ser deduzidas das antigas. Nada que você envia agora chega. Peça a alguém do círculo um novo link de convite.",
  "New link ready to send.": "Novo link pronto para enviar.",
  "No location fix yet. Still trying...": "Ainda sem posição. O Starling continua tentando...",
  "No location yet. Start sharing to place yourself.": "Ainda sem localização. Comece a compartilhar para se posicionar.",
  "no position yet": "ainda sem posição",
  "No position yet. Start sharing first, or pick the spot on the map.": "Ainda sem posição. Comece a compartilhar primeiro, ou escolha o ponto no mapa.",
  "No update from anyone in over {n} minutes. Usually that just means phones are asleep. But if others say they are sharing right now, this phone may have missed the circle's new keys; ask any member for a fresh invite to be sure.": "Nenhuma atualização de ninguém há mais de {n} minutos. Normalmente isso só quer dizer que os celulares estão dormindo. Mas se os outros dizem que estão compartilhando agora, este celular pode ter perdido as novas chaves do círculo; peça um novo convite a qualquer membro para ter certeza.",
  "Nobody else in this circle yet": "Por enquanto, mais ninguém neste círculo",
  "Nobody else is in this circle yet. Invite someone from the map.": "Ainda não tem mais ninguém neste círculo. Convide alguém pelo mapa.",
  "Nobody has been heard from in a while": "Ninguém dá notícias há um tempo",
  "Nobody has told you the circle's real name yet (names travel encrypted, like everything else), so pick whatever you will recognize. Rename it any time in settings.": "Ninguém contou a você o nome real do círculo ainda (os nomes viajam criptografados, como todo o resto), então escolha algo que você reconheça. Renomeie quando quiser nas configurações.",
  "north": "norte",
  "northeast": "nordeste",
  "northwest": "noroeste",
  "not available": "não disponível",
  "Not connected": "Sem conexão",
  "Not now": "Agora não",
  "Not reaching the relay": "Sem contato com o relay",
  "Not reaching your circle": "Sem contato com seu círculo",
  "not ready yet": "ainda não está pronto",
  "Not sharing": "Compartilhamento desligado",
  "Not verified": "Não verificado",
  "Not visible: this phone's clock is wrong": "Você não está visível: o relógio deste celular está errado",
  "nothing sent yet": "nada enviado ainda",
  "now": "agora",
  "Now": "Agora",
  "Numbers match, let them in": "Os números batem, deixar entrar",
  "Off-grid": "Sem rede",
  "omw to the fountain": "indo pra fonte",
  "One of your circles expired while this phone was away": "Um dos seus círculos expirou enquanto este celular estava fora",
  "One readable file: profile, settings, places, circle names, who you trust. No positions, because Starling stores none, and no keys, ever.": "Um arquivo legível: perfil, configurações, lugares, nomes dos círculos, em quem você confia. Sem posições, porque o Starling não guarda nenhuma, e sem chaves, nunca.",
  "One use only, and it expires in {left}. Accepting somebody uses it up.": "Só um uso, e expira em {left}. Aceitar alguém gasta o link.",
  "Only if you run a relay yourself. Everyone in your circle has to use the same one, and the invite links you send carry it.": "Só se você tiver seu próprio relay. Todos no seu círculo têm que usar o mesmo, e os links de convite que você envia levam esse relay junto.",
  "Only your own keys can decrypt what you send. The relay stores ciphertext it cannot open.": "Só suas próprias chaves conseguem descriptografar o que você envia. O relay guarda texto cifrado que não consegue abrir.",
  "Open app settings": "Abrir configurações do app",
  "Open members": "Abrir membros",
  "Open Starling to check their number and let them in.": "Abra o Starling para verificar o número e deixar a pessoa entrar.",
  "Open Starling to see their live position.": "Abra o Starling para ver a posição ao vivo.",
  "Optimized. Android may pause Starling to save battery while the screen is off, which can stop your circle seeing you move. Allowing it to run in the background prevents that.": "Otimizado. O Android pode pausar o Starling para economizar bateria com a tela desligada, o que pode impedir seu círculo de ver você se mover. Permitir que rode em segundo plano evita isso.",
  "Or your own words": "Ou suas próprias palavras",
  "Panic wipe": "Apagamento de pânico",
  "Passcode": "Senha",
  "Passcode changed.": "Senha alterada.",
  "Paste the invite link someone sent you. The circle secret stays in the link fragment and never touches a server.": "Cole o link de convite que alguém enviou a você. O segredo do círculo fica no fragmento do link e nunca toca um servidor.",
  "Paused while Tor mode is on, so nothing leaves this phone outside Tor.": "Pausado enquanto o modo Tor está ligado, para que nada saia deste celular fora do Tor.",
  "People and keys": "Pessoas e chaves",
  "Pick an avatar": "Escolha um avatar",
  "Pick on the map": "Escolher no mapa",
  "Place name": "Nome do lugar",
  "Places": "Lugares",
  "Point Starling at your own relay if you run one. The relay source ships with the app, so anyone can host it. Leave this empty for the default. A change applies the next time Starling starts.": "Aponte o Starling para seu próprio relay, se você mantém um. O código do relay vem junto com o app, então qualquer pessoa pode hospedá-lo. Deixe vazio para usar o padrão. Uma mudança vale a partir da próxima vez que o Starling abrir.",
  "Precise": "Exata",
  "Precision": "Precisão",
  "Privacy fence": "Cerca de privacidade",
  "Privacy fence for {name}": "Cerca de privacidade de {name}",
  "Probably just quiet": "Provavelmente é só silêncio",
  "Read this out to {who} on a call or in person. The same digits on both screens means nobody is in between.": "Leia isto em voz alta para {who} em uma ligação ou pessoalmente. Os mesmos dígitos nas duas telas significam que não há ninguém no meio.",
  "Real map": "Mapa real",
  "Recenter": "Centralizar",
  "Reconnecting": "Reconectando",
  "Reconnecting...": "Reconectando...",
  "Reject": "Recusar",
  "Relay": "Relay",
  "Relay saved. It applies the next time Starling starts.": "Relay salvo. Vale a partir da próxima vez que o Starling abrir.",
  "Relock after the app has been in the background this long. Locking ends a share unless Keep sharing when the app is closed is on.": "Bloqueia de novo depois que o app ficar em segundo plano por esse tempo. O bloqueio encerra o compartilhamento, a menos que Continuar compartilhando com o app fechado esteja ligado.",
  "Remove": "Remover",
  "Remove {name}": "Remover {name}",
  "Remove duress passcode": "Remover senha de coação",
  "Remove them": "Remover a pessoa",
  "Request sent. Someone in the circle has to accept it from their phone.": "Pedido enviado. Alguém do círculo tem que aceitá-lo pelo celular.",
  "Require passcode": "Exigir senha",
  "Restricted. Android stops Starling about a minute after you leave it, and a share stops with it. Set battery use to Unrestricted in the app's settings.": "Restrito. O Android encerra o Starling cerca de um minuto depois que você sai dele, e o compartilhamento para junto. Mude o uso de bateria para Sem restrições nas configurações do app.",
  "Review the request": "Analisar o pedido",
  "Revoke": "Revogar",
  "Revoked": "Revogado",
  "Route through Orbot": "Rotear pelo Orbot",
  "Running in the background": "Execução em segundo plano",
  "Safety number {digits}": "Número de segurança {digits}",
  "Safety number loading": "Carregando número de segurança",
  "Save": "Salvar",
  "Save duress passcode": "Salvar senha de coação",
  "Save my current spot": "Salvar meu ponto atual",
  "Saved. Your circle sees it once you start sharing.": "Salvo. Seu círculo vê assim que você começar a compartilhar.",
  "See everything Starling has": "Ver tudo que o Starling tem",
  "See who is here": "Ver quem está aqui",
  "Send": "Enviar",
  "Send it through something you already trust, like Signal. Whoever opens it can ask to join; they are not in until you check their number and accept.": "Envie por algo em que você já confia, como o Signal. Quem abrir pode pedir para entrar; a pessoa só entra depois que você verificar o número dela e aceitar.",
  "Send on the timer even when you have not moved. The relay cannot read a position either way, but a burst of updates while you walk and silence while you sit is a movement trail made of timing alone. This hides that, and costs a little battery.": "Envia a cada intervalo mesmo quando você não se moveu. O relay não consegue ler uma posição de qualquer jeito, mas uma rajada de atualizações enquanto você anda e silêncio enquanto está parado é um rastro de movimento feito só do ritmo dos envios. Isso esconde esse rastro, e gasta um pouco de bateria.",
  "Send the link": "Enviar o link",
  "Sends relay and map traffic through Orbot's Tor proxy on this device. Needs Orbot installed with Power User Mode on. Orbot's per-app VPN mode also covers Starling with this off.": "Envia o tráfego do relay e do mapa pelo proxy Tor do Orbot neste dispositivo. Precisa do Orbot instalado com o Power User Mode ligado. O modo VPN por app do Orbot também cobre o Starling com isto desligado.",
  "Sends your own position in OwnTracks format to a server you run, like Reitti, Dawarich or Home Assistant, only while you share. It goes straight from this phone, never through the relay, and your circle's positions never go there. The server gets your precise position whatever the precision setting. With the app lock on, changing it needs your passcode.": "Envia sua própria posição no formato OwnTracks para um servidor que você mantém, como Reitti, Dawarich ou Home Assistant, só enquanto você compartilha. Vai direto deste celular, nunca pelo relay, e as posições do seu círculo nunca vão para lá. O servidor recebe sua posição precisa, seja qual for a configuração de precisão. Com o bloqueio do app ligado, mudar isto exige sua senha.",
  "Sent it to the wrong person?": "Enviou para a pessoa errada?",
  "Sent with the tracker ID {tid}.": "Enviado com o ID de rastreador {tid}.",
  "service error": "erro do serviço",
  "Session ended": "Sessão encerrada",
  "Set a passcode": "Definir uma senha",
  "Set a status for your circle": "Defina um status para seu círculo",
  "Set status": "Definir status",
  "Set tracker ID": "Definir ID de rastreador",
  "Settings": "Configurações",
  "Share timer": "Temporizador de compartilhamento",
  "Shares now keep running while Starling is closed or locked.": "Agora os compartilhamentos continuam rodando com o Starling fechado ou bloqueado.",
  "Sharing (pretend)": "Compartilhando (simulado)",
  "Sharing live": "Compartilhando ao vivo",
  "Sharing normally stops when you swipe Starling out of recents, because the keys that encrypt each position live in the app. With this on, Starling stays loaded in the background until the share ends, so closing it does not stop it. Anyone holding your unlocked phone can see the app is still running, and it is still holding your keys, so the app lock cannot protect them until the share ends.": "Normalmente o compartilhamento para quando você tira o Starling dos apps recentes, porque as chaves que criptografam cada posição vivem no app. Com isto ligado, o Starling continua carregado em segundo plano até o compartilhamento terminar, então fechá-lo não para o compartilhamento. Quem estiver com seu celular desbloqueado consegue ver que o app continua rodando, e ele continua com suas chaves na memória, então o bloqueio do app não consegue protegê-las até o compartilhamento terminar.",
  "Sharing report copied. It has no locations and no keys in it.": "Relatório de compartilhamento copiado. Não tem localizações nem chaves.",
  "Sharing was on when the app closed, so it is back on.": "O compartilhamento estava ligado quando o app fechou, então voltou a ficar ativo.",
  "Sharing was stopped from the notification.": "O compartilhamento foi parado pela notificação.",
  "Sharing{run}, and this screen has to stay on": "Compartilhando{run}, e esta tela precisa ficar ligada",
  "Show recent paths on the map": "Mostrar trajetos recentes no mapa",
  "Show the demo on a real map? Tiles of its Central Park stage load from openstreetmap.org - the demo's only network use.": "Mostrar a demonstração em um mapa real? Os blocos do cenário do Central Park são carregados de openstreetmap.org, o único uso de rede da demonstração.",
  "Show this safety number large for comparing in person": "Mostrar este número de segurança em tamanho grande para comparar pessoalmente",
  "Signal lost": "Sinal perdido",
  "Somebody already in that circle has to accept your request. Read them your number: {digits}{jumped}": "Alguém que já está nesse círculo tem que aceitar seu pedido. Leia seu número para essa pessoa: {digits}{jumped}",
  "Somebody else is jamming that invite link, so it cannot be used any more. Nobody was let in. Make a new link and send it again.": "Outra pessoa está interferindo nesse link de convite, então ele não pode mais ser usado. Ninguém entrou. Crie um novo link e envie de novo.",
  "Someone": "Alguém",
  "Someone shared this emergency link with you. Their live position appears here the moment it arrives. Keep this page open.": "Alguém compartilhou este link de emergência com você. A posição ao vivo dessa pessoa aparece aqui assim que chegar. Mantenha esta página aberta.",
  "Someone tapped Stop on the sharing notification. If that was not you, check who has access to this phone.": "Alguém tocou em Parar na notificação de compartilhamento. Se não foi você, veja quem tem acesso a este celular.",
  "Someone wants to join": "Alguém quer entrar",
  "SOS": "SOS",
  "SOS active": "SOS ativo",
  "SOS armed · Locating...": "SOS armado · Localizando...",
  "SOS armed · Location is off": "SOS armado · Localização desligada",
  "SOS armed · Not reaching your circle": "SOS armado · Sem contato com seu círculo",
  "SOS armed · Sharing live": "SOS armado · Compartilhando ao vivo",
  "SOS delivered to your circle.": "SOS entregue ao seu círculo.",
  "SOS from {who}": "SOS de {who}",
  "SOS is armed": "O SOS está armado",
  "SOS not delivered yet. Starling keeps trying.": "SOS ainda não entregue. O Starling continua tentando.",
  "SOS queued. Starling keeps trying...": "SOS na fila. O Starling continua tentando...",
  "SOS sent to your circle. Tap the check mark to cancel.": "SOS enviado ao seu círculo. Toque na marca de confirmação para cancelar.",
  "Source code": "Código-fonte",
  "south": "sul",
  "southeast": "sudeste",
  "southwest": "sudoeste",
  "starling": "starling",
  "Starling cannot recover a forgotten passcode. Nothing about your circle leaves your device unencrypted, so there is no reset link. You can erase this device and rejoin your circle from a fresh invite. Hold the button to erase everything on this device.": "O Starling não consegue recuperar uma senha esquecida. Nada sobre seu círculo sai do seu dispositivo sem criptografia, então não existe link de redefinição. Você pode apagar este dispositivo e entrar de novo no seu círculo por um novo convite. Segure o botão para apagar tudo neste dispositivo.",
  "Starling hit a problem while starting.": "O Starling teve um problema ao iniciar.",
  "Starling locked itself while you were away, and a locked Starling holds no keys, so the lock ended your share.": "O Starling se bloqueou enquanto você estava fora, e um Starling bloqueado não guarda chaves, então o bloqueio encerrou seu compartilhamento.",
  "Starling locks itself after a while in the background, and a locked Starling holds no keys, so the lock would end this share.": "O Starling se bloqueia depois de um tempo em segundo plano, e um Starling bloqueado não guarda chaves, então o bloqueio encerraria este compartilhamento.",
  "Starling only gets good when your people are on the map. Send them your invite link.": "O Starling só fica bom quando seu pessoal está no mapa. Envie seu link de convite para eles.",
  "Starling only has your approximate location": "O Starling só tem sua localização aproximada",
  "Starling throws a circle's keys away rather than carry them for weeks, and that circle passed the point where this device could still read it, so it was erased from this phone. {kept} Ask somebody in that circle for a fresh invite link if you want back in.": "O Starling joga fora as chaves de um círculo em vez de carregá-las por semanas, e esse círculo passou do ponto em que este dispositivo ainda conseguia lê-lo, então ele foi apagado deste celular. {kept} Peça a alguém desse círculo um novo link de convite se quiser voltar.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this device passed that point while it was away. Its keys are gone from memory and from storage, and so is this phone's own identity in that circle, so nothing you send arrives and nothing sent to you can be read. Ask somebody in the circle for a fresh invite link.": "O Starling joga fora as chaves de um círculo em vez de carregá-las por semanas, e este dispositivo passou desse ponto enquanto estava fora. As chaves sumiram da memória e do armazenamento, e a própria identidade deste celular nesse círculo também, então nada que você envia chega e nada enviado a você pode ser lido. Peça a alguém do círculo um novo link de convite.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this phone passed that point while it was away. The circle was erased from this device, and there was no other circle to fall back to.{lockLine} Ask somebody for a fresh invite link, or start a new circle.": "O Starling joga fora as chaves de um círculo em vez de carregá-las por semanas, e este celular passou desse ponto enquanto estava fora. O círculo foi apagado deste dispositivo, e não havia outro círculo para usar no lugar.{lockLine} Peça a alguém um novo link de convite, ou comece um novo círculo.",
  "Starling trusts whoever first answers with keys that match their member id. Reading these numbers out to each other is what turns that into knowing who is on your map.": "O Starling confia em quem responde primeiro com chaves que batem com o ID de membro. Ler esses números em voz alta um para o outro é o que transforma isso em saber quem está no seu mapa.",
  "Starling will use {host}.": "O Starling vai usar {host}.",
  "Starling's battery use is set to Restricted, so Android stops a share about a minute after the app leaves the screen. Set it to Unrestricted in the app's settings to keep sharing with the screen off.": "O uso de bateria do Starling está como Restrito, então o Android encerra o compartilhamento cerca de um minuto depois que o app sai da tela. Mude para Sem restrições nas configurações do app para continuar compartilhando com a tela desligada.",
  "Start a new circle": "Começar um novo círculo",
  "Start fresh": "Começar do zero",
  "Start sharing": "Começar a compartilhar",
  "Steady sending": "Envio constante",
  "Steady sending is on too, so the relay cannot read your movement from the timing.": "O envio constante também está ligado, então o relay não consegue ler seu movimento pelo tempo entre envios.",
  "Still about {n} minutes out.": "Ainda uns {n} minutos de diferença.",
  "Stop by itself:": "Parar sozinho:",
  "Stop sending": "Parar de enviar",
  "Stop sharing with helpers": "Parar de compartilhar com os ajudantes",
  "Stopped": "Parado",
  "stops in {left}": "termina em {left}",
  "Street maps load tiles from OpenStreetMap, which sees your map viewport. Off-grid loads nothing.": "Os mapas de ruas carregam blocos do OpenStreetMap, que vê a área visível do seu mapa. Sem rede não carrega nada.",
  "Switch circle": "Trocar de círculo",
  "Switched to {name}.": "Agora você está em {name}.",
  "Tap Keep sharing to let shares run while Starling is closed or locked. The lock then waits until the share ends.": "Toque em Continuar compartilhando para deixar os compartilhamentos rodarem com o Starling fechado ou bloqueado. O bloqueio então espera o compartilhamento terminar.",
  "Tap the map where {name} is.": "Toque no mapa onde fica {name}.",
  "Tell me when a member's phone drops under 15 percent, before their dot goes dark": "Me avise quando o celular de um membro cair abaixo de 15 por cento, antes que o ponto dele apague",
  "Tell me when someone in the circle reaches a place or leaves one": "Me avise quando alguém do círculo chegar a um lugar ou sair de um",
  "telling your circle...": "avisando seu círculo...",
  "That address did not work. Use a full https address.": "Esse endereço não funcionou. Use um endereço https completo.",
  "That circle expired, and this device could not erase all of it. Open Starling again to finish clearing it.": "Esse círculo expirou, e este dispositivo não conseguiu apagá-lo por completo. Abra o Starling de novo para terminar a limpeza.",
  "That circle expired, and this phone could not erase it": "Esse círculo expirou, e este celular não conseguiu apagá-lo",
  "That does not look like a Starling invite link.": "Isso não parece um link de convite do Starling.",
  "That invitation arrived incomplete": "Esse convite chegou incompleto",
  "That invitation expired. Make a new link.": "Esse convite expirou. Crie um novo link.",
  "That is the lot: {n} places is the cap.": "É isso: o limite é de {n} lugares.",
  "That is your duress passcode. Pick a different one.": "Essa é sua senha de coação. Escolha outra.",
  "That is your own invite link.": "Esse é o seu próprio link de convite.",
  "That is your unlock passcode. A duress code has to be different.": "Essa é sua senha de desbloqueio. A senha de coação tem que ser diferente.",
  "That link is dead. The others still work.": "Esse link morreu. Os outros ainda funcionam.",
  "That passcode is right, but this install's stored data will not open. Nothing was erased.": "Essa senha está certa, mas os dados guardados desta instalação não abrem. Nada foi apagado.",
  "That passcode is wrong.": "Essa senha está errada.",
  "That phone is answering with keys this device has never seen. It is a reinstall, or somebody else in {who}'s place, and nothing here can tell you which. Their location stays off your map until you check the number with them and accept it.": "Esse celular está respondendo com chaves que este dispositivo nunca viu. É uma reinstalação, ou outra pessoa no lugar de {who}, e nada aqui consegue dizer qual. A localização fica fora do seu mapa até você verificar o número com a pessoa e aceitar.",
  "That request's keys are malformed. Nobody was let in.": "As chaves desse pedido estão malformadas. Ninguém entrou.",
  "That tracker ID did not work.": "Esse ID de rastreador não funcionou.",
  "The app lock ended your share": "O bloqueio do app encerrou seu compartilhamento",
  "The app lock had ended your share. It is back on.": "O bloqueio do app tinha encerrado seu compartilhamento. Ele voltou a ficar ativo.",
  "The app lock will end this share": "O bloqueio do app vai encerrar este compartilhamento",
  "The app was closed while sharing was on, which stopped it, and opening it again put it back on. If closing it was not you, check who has access to this phone.": "O app foi fechado com o compartilhamento ligado, o que parou o compartilhamento, e ele voltou quando o app foi aberto de novo. Se não foi você que fechou, veja quem tem acesso a este celular.",
  "The app was closed while sharing was on, which stops it every time. If that was not you, check who has access to this phone.": "O app foi fechado com o compartilhamento ligado, e isso sempre para o compartilhamento. Se não foi você, veja quem tem acesso a este celular.",
  "The clock looks right now. Your circle can see you again.": "O relógio parece certo agora. Seu círculo consegue ver você de novo.",
  "The demo has its own Real map button. Your choice here applies when you exit.": "A demonstração tem seu próprio botão Mapa real. Sua escolha aqui vale quando você sair.",
  "The fountain": "A fonte",
  "The label is for you. It is never sent anywhere.": "O rótulo é para você. Nunca é enviado a lugar nenhum.",
  "The last send failed: the server answered {code}.": "O último envio falhou: o servidor respondeu {code}.",
  "The last send failed: the server did not answer.": "O último envio falhou: o servidor não respondeu.",
  "The last send worked.": "O último envio funcionou.",
  "The link stops working immediately, and any request already waiting on it is dropped. Open Invite again for a fresh one.": "O link para de funcionar na hora, e qualquer pedido que já estava esperando nele é descartado. Abra Convidar de novo para criar um novo.",
  "the person who let you in": "quem deixou você entrar",
  "The person who shared this link stopped their emergency share or checked in safe. The last known position stays on the map.": "A pessoa que compartilhou este link parou o compartilhamento de emergência ou avisou que está bem. A última posição conhecida fica no mapa.",
  "The relay that passes your updates along stores only encrypted data it cannot read, and deletes it after 24 hours. The protocol is open, so anyone can check these claims against the code.": "O relay que repassa suas atualizações guarda só dados criptografados que não consegue ler, e apaga tudo depois de 24 horas. O protocolo é aberto, então qualquer pessoa pode conferir essas afirmações no código.",
  "The SOS is cleared.": "O SOS foi cancelado.",
  "Their dot may go dark soon.": "O ponto dessa pessoa pode apagar em breve.",
  "Their number is {theirs}. Yours is {mine}. Read them to each other out loud, on a line you already trust. Nothing else in this circle has been checked by a person yet.": "O número dessa pessoa é {theirs}. O seu é {mine}. Leiam os números em voz alta um para o outro, por um canal em que vocês já confiam. Nada mais neste círculo foi verificado por uma pessoa ainda.",
  "them": "essa pessoa",
  "Theme": "Tema",
  "They": "Essa pessoa",
  "They chose the name {who}. Anyone can type any name, so the number below is the only part that proves who they are.": "A pessoa escolheu o nome {who}. Qualquer um pode digitar qualquer nome, então o número abaixo é a única parte que prova quem ela é.",
  "This browser is blocking storage. Starling runs, but nothing is saved after you close it.": "Este navegador está bloqueando o armazenamento. O Starling funciona, mas nada fica salvo depois que você fecha.",
  "This circle uses another relay": "Este círculo usa outro relay",
  "This circle uses the relay at {host}. Asking to join switches Starling to it.": "Este círculo usa o relay em {host}. Pedir para entrar muda o Starling para ele.",
  "This device could not run the lock's key stretching. Nothing was erased; try again, or free some memory.": "Este dispositivo não conseguiu executar a derivação de chave do bloqueio. Nada foi apagado; tente de novo, ou libere memória.",
  "This help link is no longer active. The last known position stays on the map; ask for a fresh link if the emergency is still going on.": "Este link de ajuda não está mais ativo. A última posição conhecida fica no mapa; peça um novo link se a emergência ainda continua.",
  "This invitation is for a circle on {host}.": "Este convite é para um círculo em {host}.",
  "This is taking a while. The person who invited you may not have seen the request yet, or the link may have expired. Reach them however you normally would; a fresh link takes a minute to make.": "Isto está demorando. A pessoa que convidou você pode não ter visto o pedido ainda, ou o link pode ter expirado. Fale com ela do jeito que você normalmente faria; criar um novo link leva um minuto.",
  "This is the number your circle should hear from you.": "Este é o número que seu círculo deve ouvir de você.",
  "This link has expired": "Este link expirou",
  "This page needs JavaScript. The person's position arrives encrypted and is decrypted here, in your browser, with a key carried in this link that never reaches any server; without JavaScript there is nothing that can do that decryption. If you are on Tor Browser's Safest setting, allow JavaScript for this page to see them.": "Esta página precisa de JavaScript. A posição da pessoa chega criptografada e é descriptografada aqui, no seu navegador, com uma chave que vai neste link e nunca chega a servidor nenhum; sem JavaScript não há nada que faça essa descriptografia. Se você usa o Tor Browser no nível de segurança mais alto (O mais seguro), permita JavaScript nesta página para ver a pessoa.",
  "This phone has been offline too long": "Este celular ficou off-line por tempo demais",
  "This phone's clock is wrong": "O relógio deste celular está errado",
  "This phone's clock is wrong, so your circle cannot see you.{off} Turn on automatic date and time.": "O relógio deste celular está errado, então seu círculo não consegue ver você.{off} Ligue a data e hora automáticas.",
  "This sends a request. Somebody already in the circle has to check your safety number and accept it before you can see anyone, or they you. That check is how they know the request really came from you and not from somebody who got hold of the link.": "Isto envia um pedido. Alguém que já está no círculo tem que verificar seu número de segurança e aceitar antes que você veja alguém, ou alguém veja você. Essa verificação é como eles sabem que o pedido veio mesmo de você e não de alguém que pegou o link.",
  "This session has ended": "Esta sessão terminou",
  "Those keys are gone": "Essas chaves se foram",
  "Those new keys are malformed. They were not accepted.": "Essas novas chaves estão malformadas. Não foram aceitas.",
  "Timed share ended. Your circle sees you stopped sharing.": "O compartilhamento com temporizador terminou. Seu círculo vê que você parou de compartilhar.",
  "To join it, put {relay} in Settings, Advanced, Relay, restart Starling and open the link again. Your other circles stop updating while it is set.": "Para entrar, coloque {relay} em Configurações, Avançado, Relay, reinicie o Starling e abra o link de novo. Seus outros círculos param de atualizar enquanto isso estiver definido.",
  "Tracker ID, like phone1 (optional)": "ID de rastreador, como celular1 (opcional)",
  "Trail": "Rastro",
  "Trail history": "Histórico do rastro",
  "Try again": "Tentar de novo",
  "Turn off app lock": "Desligar o bloqueio do app",
  "Turn on app lock": "Ligar o bloqueio do app",
  "Turned down. Your link still works for whoever it was meant for.": "Recusado. Seu link ainda funciona para a pessoa a quem ele se destinava.",
  "Unlock": "Desbloquear",
  "Unlock with biometrics": "Desbloquear com biometria",
  "Unlocking put it back on.": "Desbloquear reativou o compartilhamento.",
  "Unlocking...": "Desbloqueando...",
  "Unrestricted. Android lets Starling keep a share going with the screen off.": "Sem restrições. O Android deixa o Starling manter o compartilhamento com a tela desligada.",
  "Update Starling": "Atualizar o Starling",
  "Use a full https address, like https://your-server/owntracks": "Use um endereço https completo, como https://seu-servidor/owntracks",
  "Use at least {n} characters.": "Use pelo menos {n} caracteres.",
  "Use this device's Face ID, fingerprint, or Windows Hello to unlock. Your passcode still works as backup.": "Use o Face ID, a impressão digital ou o Windows Hello deste dispositivo para desbloquear. Sua senha continua funcionando como reserva.",
  "Use up to 64 characters for the tracker ID, on one line.": "Use até 64 caracteres para o ID de rastreador, em uma linha só.",
  "Use your own relay": "Usar seu próprio relay",
  "Verified": "Verificado",
  "Waiting for a location...": "Esperando uma localização...",
  "Waiting to be let into {name}": "Esperando para entrar em {name}",
  "Was": "Antes",
  "Watch the demo": "Ver a demonstração",
  "west": "oeste",
  "What Starling is and how it works &#8599;": "O que é o Starling e como funciona &#8599;",
  "When you are safe": "Quando você estiver em segurança",
  "While you share, your position also goes to {host}.": "Enquanto você compartilha, sua posição também vai para {host}.",
  "Who could read you": "Quem pode ler o que você envia",
  "With approximate location, Android updates your position roughly and only about every ten minutes, so your circle sees you jump. Allow precise location in the app's settings for a live share.": "Com a localização aproximada, o Android atualiza sua posição de forma imprecisa e só a cada dez minutos, mais ou menos, então seu círculo vê você pulando. Permita a localização precisa nas configurações do app para compartilhar ao vivo.",
  "With Battery Saver on, this phone turns location off while the screen is off, so your circle stops seeing you move. Turn Battery Saver off to keep sharing.": "Com a Economia de bateria ligada, este celular desliga a localização enquanto a tela está desligada, então seu círculo deixa de ver você se mover. Desligue a Economia de bateria para continuar compartilhando.",
  "Wrong passcode. Try again.": "Senha errada. Tente de novo.",
  "You": "Você",
  "You already asked to join. They still have to let you in.": "Você já pediu para entrar. Eles ainda precisam deixar você entrar.",
  "You have an invite to a circle. Set up how you will appear to the people in it.": "Você tem um convite para um círculo. Defina como vai aparecer para as pessoas dele.",
  "You have checked this number with {who}.": "Você verificou este número com {who}.",
  "You joined the circle.": "Você entrou no círculo.",
  "You left. Now in {name}.": "Você saiu. Agora em {name}.",
  "You're in": "Você entrou",
  "Your app lock and your other circles were not touched.": "Seu bloqueio do app e seus outros círculos não foram tocados.",
  "Your app lock is untouched and still protects whatever you set up next.": "Seu bloqueio do app continua intacto e segue protegendo o que você configurar a seguir.",
  "Your browser is blocking location for this site. Allow location in your browser's site settings, then tap Start sharing again.": "Seu navegador está bloqueando a localização para este site. Permita a localização nas configurações do site no navegador, depois toque em Começar a compartilhar de novo.",
  "Your circle cannot see you. The relay refuses anything stamped with a time that far out, so your position is not going anywhere.{off} Turn on automatic date and time, then check again.": "Seu círculo não consegue ver você. O relay recusa qualquer coisa marcada com uma hora tão errada, então sua posição não está indo a lugar nenhum.{off} Ligue a data e hora automáticas, depois verifique de novo.",
  "Your circle has new keys, but they could not be saved. If Starling restarts you will need a fresh invitation.": "Seu círculo tem novas chaves, mas não foi possível salvá-las. Se o Starling reiniciar, você vai precisar de um novo convite.",
  "Your circle has new keys.": "Seu círculo tem novas chaves.",
  "Your circle moved on without this phone": "Seu círculo seguiu em frente sem este celular",
  "Your circle now sees you stopped sharing.": "Seu círculo agora vê que você parou de compartilhar.",
  "Your circle sees an alert at your live position. Tap the check mark above to cancel it and let everyone know you are okay.": "Seu círculo vê um alerta na sua posição ao vivo. Toque na marca de confirmação acima para cancelar e avisar a todos que você está bem.",
  "Your circles": "Seus círculos",
  "Your circles use {host}, and Starling talks to one relay at a time.": "Seus círculos usam {host}, e o Starling fala com um relay por vez.",
  "Your circles use the default relay, and Starling talks to one relay at a time.": "Seus círculos usam o relay padrão, e o Starling fala com um relay por vez.",
  "Your current circle stays. This adds a new one, and you can switch between them from the circle name at the top of the map.": "Seu círculo atual continua. Isto adiciona um novo, e você pode alternar entre eles pelo nome do círculo no topo do mapa.",
  "Your data": "Seus dados",
  "Your last share was stopped outside the app": "Seu último compartilhamento foi parado fora do app",
  "Your list of members does not match": "Sua lista de membros não bate",
  "Your name": "Seu nome",
  "Your number": "Seu número",
  "Your other circles": "Seus outros círculos",
  "Your other circles could not be read and were dropped.": "Seus outros círculos não puderam ser lidos e foram descartados.",
  "Your other circles were not touched.": "Seus outros círculos não foram tocados.",
  "Your own server": "Seu próprio servidor",
  "Your people, on your map. Nobody else.": "Seu pessoal, no seu mapa. Mais ninguém.",
  "Your position goes out as {tid}.": "Sua posição sai como {tid}.",
  "Your position goes out with no tracker ID.": "Sua posição sai sem ID de rastreador.",
  "Your position no longer goes to your own server.": "Sua posição não vai mais para seu próprio servidor.",
  "Your positions are encrypted on this device with a key only your circle holds. There are no accounts, no phone numbers, and no server that can read where you are. Sharing is off until you turn it on, and stopping is one tap.": "Suas posições são criptografadas neste dispositivo com uma chave que só seu círculo tem. Não há contas, nem números de telefone, nem servidor que consiga ler onde você está. O compartilhamento fica desligado até você ligar, e parar é um toque.",
  "Your request is waiting on the relay. Somebody already in the circle has to check your number and accept it, and they do not have to be online right now.": "Seu pedido está esperando no relay. Alguém que já está no círculo tem que verificar seu número e aceitar, e não precisa estar on-line agora.",
  "Your request was accepted. Your circle is on the map.": "Seu pedido foi aceito. Seu círculo está no mapa.",
  "Your status": "Seu status",
  "Biometric unlock is on.": "O desbloqueio biométrico está ligado.",
  "coffee run": "buscando café",
  "phone's dying": "quase sem bateria",
  "Press and hold to erase": "Segure para apagar",
  "Press and hold to send SOS": "Segure para enviar SOS",
  "Status cleared.": "Status apagado.",
  "Status set.": "Status definido.",
  "Tap once more to erase everything": "Toque mais uma vez para apagar tudo",
  "Tap once more to send SOS": "Toque mais uma vez para enviar SOS",
  "You left the circle.": "Você saiu do círculo.",
  "You left, but this device could not erase everything. Open Starling again to finish clearing it.": "Você saiu, mas este aparelho não conseguiu apagar tudo. Abra o Starling de novo para terminar a limpeza.",
  "Your device or browser could not set up biometric unlock.": "Seu aparelho ou navegador não conseguiu configurar o desbloqueio biométrico.",
  "{who} is already marked verified.": "{who} já está marcado como verificado.",
  "{who} is answering with different keys right now. Settle that on their card before marking anything.": "{who} está respondendo com outras chaves agora. Resolva isso no cartão dessa pessoa antes de marcar qualquer coisa.",
  "{who} is verified.": "{who} está verificado.",
  "15 s": "15 s",
  "Camera access was turned down. Allow it for Starling in system settings, then try again.": "O acesso à câmera foi negado. Permita para o Starling nas configurações do sistema e tente de novo.",
  "For {name}. Each circle keeps its own precision and timing.": "Para {name}. Cada círculo guarda sua própria precisão e seu próprio ritmo.",
  "How often your circle hears from you while you stay put. Moving sends sooner unless Steady sending is on. Slower is easier on the battery. An SOS always goes every 15 seconds.": "Com que frequência seu círculo recebe notícias suas enquanto você fica parado. Movimento envia antes, a menos que o Envio constante esteja ligado. Mais devagar gasta menos bateria. Um SOS sempre sai a cada 15 segundos.",
  "Let the person checking you scan this with Starling. It holds your member id and your safety number, nothing else.": "Deixe a pessoa que está verificando você escanear isto com o Starling. Ele contém seu ID de membro e seu número de segurança, nada mais.",
  "Mark {who} verified": "Marcar {who} como verificado",
  "No camera found on this device.": "Nenhuma câmera encontrada neste aparelho.",
  "Point the camera at the code on their screen.": "Aponte a câmera para o código na tela da outra pessoa.",
  "Safety number QR code": "Código QR do número de segurança",
  "Scan result": "Resultado da leitura",
  "Scan their code": "Escanear o código da pessoa",
  "Scan theirs": "Escanear o da pessoa",
  "Scanning a code lives in the app. Here, compare the digits.": "Escanear um código só funciona no app. Aqui, compare os dígitos.",
  "Send every": "Enviar a cada",
  "Show as QR": "Mostrar como QR",
  "That code belongs to nobody in this circle.": "Esse código não é de ninguém deste círculo.",
  "That is not a Starling safety number code.": "Isso não é um código de número de segurança do Starling.",
  "The camera could not start.": "A câmera não conseguiu iniciar.",
  "The code does not match the keys this phone holds for {who}. That is a reinstall, or somebody in between, and this phone cannot tell which. Do not mark them verified. Read the digits out to each other, and if they still differ, remove them.": "O código não bate com as chaves que este celular tem para {who}. Isso é uma reinstalação, ou alguém no meio, e este celular não consegue dizer qual dos dois. Não marque a pessoa como verificada. Leiam os dígitos em voz alta um para o outro e, se ainda forem diferentes, remova a pessoa.",
  "The code matches the keys this phone holds for {who}. Nobody is in between.": "O código bate com as chaves que este celular tem para {who}. Não tem ninguém no meio.",
  "Your number as a code": "Seu número como código",
  "Your number is not ready yet.": "Seu número ainda não está pronto.",
  "Check-in timer": "Timer de aviso",
  "Get your circle told if you miss a check-in": "Seu círculo fica sabendo se você não avisar a tempo",
  "Pick how long you need. If you have not checked in when it runs out, your circle is told, even if this phone is off by then. Only checking in stops it.": "Escolha quanto tempo você precisa. Se você não tiver avisado quando o tempo acabar, seu círculo recebe um alerta, mesmo que este celular já esteja desligado. Só avisar para o timer.",
  "Check in within": "Avisar em até",
  "Start timer": "Iniciar timer",
  "Check in now": "Avisar agora",
  "Check in by {time}": "Prazo para avisar: {time}",
  "Start sharing too": "Começar a compartilhar também",
  "Sharing is off, so your circle gets the timer and the last position this phone sent, not where you are now.": "O compartilhamento está desligado, então seu círculo recebe o timer e a última posição que este celular enviou, não onde você está agora.",
  "Timer set. Check in by {time}.": "Timer definido. Prazo para avisar: {time}.",
  "Timer set, but your circle does not have it yet. Starling keeps trying.": "Timer definido, mas seu círculo ainda não recebeu. O Starling continua tentando.",
  "Check in within 5 minutes, or your circle is told.": "Avise nos próximos 5 minutos, ou seu círculo recebe um alerta.",
  "You missed your check-in": "Você não avisou a tempo",
  "Your circle has been told. Check in now if you are okay.": "Seu círculo recebeu um alerta. Avise agora se você está bem.",
  "{who} missed their check-in": "{who} não avisou a tempo",
  "Their timer ran out at {time}. Their last position is on the map.": "O prazo dessa pessoa acabou às {time}. A última posição dela está no mapa.",
  "Their last position is on the map.": "A última posição dessa pessoa está no mapa.",
  "Show on map": "Ver no mapa",
  "Missed check-in": "Prazo vencido",
  "Your check-in timer is running in {circle}. Check in there before you switch?": "Seu timer de aviso está correndo em {circle}. Avisar lá antes de trocar?",
  "Check in and switch": "Avisar e trocar",
  "Exit the demo to set a check-in timer.": "Saia da demonstração para definir um timer de aviso.",
  "Their live position is on the map. It stays here until they check in.": "A posição ao vivo dessa pessoa está no mapa. Este alerta fica aqui até ela avisar que está bem.",
  "{who}'s phone stopped sending {ago} ago. The last position it sent is on the map.": "O celular de {who} parou de enviar há {ago}. A última posição que ele enviou está no mapa.",
  "{who}'s SOS went quiet": "O SOS de {who} ficou sem sinal",
  "Alerts": "Alertas",
  "{name} alerts": "Alertas de {name}",
  "Both": "Ambos",
  "Arrive": "Chegada",
  "Leave": "Saída",
  "Off": "Nenhum",
  "Your battery is at {pct}%": "Sua bateria está com {pct}%",
  "Sending every 5 minutes instead of every 15 seconds makes it last longer. An SOS still goes out every 15 seconds.": "Enviar a cada 5 minutos em vez de a cada 15 segundos faz a bateria durar mais. Um SOS continua saindo a cada 15 segundos.",
  "Every 5 minutes": "A cada 5 minutos",
  "Accurate to about {dist}": "Precisão de cerca de {dist}",
  "Phone battery {pct}%": "Bateria do celular: {pct}%",
  "Link works until {time}": "Link válido até {time}",
  "Open in a map app": "Abrir em um app de mapas",
};
