// Spanish catalog: normalized English source -> Spanish.
// Reviewed line by line by a native speaker (issue #1); rough edges still
// deserve bug reports. Regenerate the key list with:
// node tools/extract-strings.mjs
// Missing entries fall back to English by design.
export const es = {
  "Scan a code": "Escanear un código",
  "Scan an invite code": "Escanear un código de invitación",
  "Point the camera at the invite code on their screen.": "Apunta la cámara al código de invitación en su pantalla.",
  "That is a safety number code, not an invite.": "Ese es un código de número de seguridad, no una invitación.",
  "That is not a Starling invite code.": "Eso no es un código de invitación de Starling.",
  "Remind me if sharing stays off": "Recordarme si sigo sin compartir",
  "If you stop sharing and do not turn it back on, this phone shows a notification after that long. Nothing goes to your circle.": "Si dejas de compartir y no lo vuelves a activar, este teléfono muestra una notificación pasado ese tiempo. A tu círculo no le llega nada.",
  "Never": "Nunca",
  "1 h": "1 h",
  "4 h": "4 h",
  "12 h": "12 h",
  "SOS and Do Not Disturb": "SOS y No molestar",
  "An SOS from your circle rings through Do Not Disturb when alarms are allowed. To let it through total silence too, turn on Override Do Not Disturb for Emergency alerts.": "Un SOS de tu círculo suena con No molestar activado si las alarmas están permitidas. Para que suene también en silencio total, activa Ignorar No molestar en Alertas de emergencia.",
  "Open emergency alert settings": "Abrir ajustes de alertas de emergencia",
  "Invite QR code": "Código QR de invitación",
  "{who} is answering with different keys. That is a reinstall, or somebody else in their place, and this phone cannot tell which. Their location stays off your map until you accept.": "{who} está respondiendo con claves distintas. Puede ser una reinstalación, o puede ser otra persona en su lugar, y este teléfono no puede distinguirlo. Su ubicación queda fuera de tu mapa hasta que aceptes.",
  "Ask {who} to read out the number on their screen. If it is the new one, accept it. If it is the old one, or they did not reinstall, remove them.": "Pídele a {who} que te lea el número que ve en su pantalla. Si es el nuevo, acéptalo. Si es el viejo, o no reinstaló la app, quítalo del círculo.",
  "Avatar": "Avatar",
  "Cancel": "Cancelar",
  "Cancel SOS and check in with your circle": "Cancelar el SOS y avisar a tu círculo",
  "End to end encrypted. This page can read this one emergency share and nothing else.": "Cifrado de extremo a extremo. Esta página puede leer esta emergencia y nada más.",
  "Everyone else gets new keys. {who} can read nothing this circle sends from now on, and is not told. What they already saw, they keep.": "Todos los demás reciben claves nuevas. {who} no podrá leer nada de lo que este círculo envíe a partir de ahora, y no se le avisa. Lo que ya vio, lo conserva.",
  "Keys changed": "Claves cambiadas",
  "Map": "Mapa",
  "Mark not verified": "Marcar como no verificado",
  "no position yet": "sin posición todavía",
  "Member details": "Detalles del miembro",
  "Not reaching the relay": "Sin conexión con el relay",
  "Not verified": "No verificado",
  "Place name": "Nombre del lugar",
  "Read this out to {who} on a call or in person. The same digits on both screens means nobody is in between.": "Léeselo a {who} en una llamada o en persona. Los mismos dígitos en ambas pantallas significan que no hay nadie en medio.",
  "Recenter": "Centrar",
  "Revoked": "Revocado",
  "Safety number loading": "Cargando número de seguridad",
  "Show this safety number large for comparing in person": "Mostrar este número de seguridad en grande para compararlo en persona",
  "Someone shared this emergency link with you. Their live position appears here the moment it arrives. Keep this page open.": "Alguien compartió contigo este enlace de emergencia. Su posición en vivo aparecerá aquí en cuanto llegue. Mantén esta página abierta.",
  "The person who shared this link stopped their emergency share or checked in safe. The last known position stays on the map.": "La persona que compartió este enlace detuvo su emergencia o avisó que está a salvo. La última posición conocida se queda en el mapa.",
  "This help link is no longer active. The last known position stays on the map; ask for a fresh link if the emergency is still going on.": "Este enlace de ayuda ya no está activo. La última posición conocida queda en el mapa; pide un enlace nuevo si la emergencia continúa.",
  "This link has expired": "Este enlace expiró",
  "This page needs JavaScript. The person's position arrives encrypted and is decrypted here, in your browser, with a key carried in this link that never reaches any server; without JavaScript there is nothing that can do that decryption. If you are on Tor Browser's Safest setting, allow JavaScript for this page to see them.": "Esta página necesita JavaScript. La posición de la persona llega cifrada y se descifra aquí, en tu navegador, con una clave que viaja en este enlace y nunca llega a ningún servidor; sin JavaScript no hay nada que pueda hacer ese descifrado. Si usas Tor Browser en el nivel más seguro, permite JavaScript en esta página para verla.",
  "This session has ended": "Esta sesión terminó",
  "Verified": "Verificado",
  "Waiting for a location...": "Esperando una ubicación...",
  "Home": "Casa",
  "The fountain": "La fuente",
  "coffee run": "por un café",
  "phone's dying": "casi sin batería",
  "omw to the fountain": "voy a la fuente",
  "made it": "llegué",
  "You": "Tú",
  "1 hr": "1 h",
  "1 min": "1 min",
  "5 min": "5 min",
  "15 s": "15 s",
  "A circle holds {n} people and yours is full. Remove somebody before letting anyone else in.": "Un círculo tiene espacio para {n} personas y el tuyo está lleno. Elimina a alguien antes de dejar entrar a otra persona.",
  "A few words your circle sees next to your name. It is encrypted like everything else, and it clears when you stop sharing.": "Unas palabras que tu círculo ve junto a tu nombre. Está cifrado como todo lo demás, y se borra cuando dejas de compartir.",
  "A member": "Un miembro",
  "A member's keys changed": "Las claves de un miembro cambiaron",
  "A relay must be an https URL, like https://relay.example.org": "El relay debe ser una URL https, como https://relay.example.org",
  "A second passcode for a moment when someone makes you open Starling. Entering it on the lock screen erases everything on this device, instantly and silently, and shows a fresh install. There is no undo and no way back in. It only guards the passcode path: biometric unlock still opens the app normally, so if a forced unlock is in your threat model, turn biometrics off too.": "Un segundo código de acceso para cuando alguien te obliga a abrir Starling. Escribirlo en la pantalla de bloqueo borra todo en este dispositivo, al instante y sin avisar, y muestra una instalación nueva. No hay forma de deshacerlo ni de volver atrás. Solo protege el camino del código de acceso: el desbloqueo biométrico sigue abriendo la app con normalidad, así que si un desbloqueo forzado forma parte de tu modelo de amenazas, desactiva también la biometría.",
  "A welcome arrived that did not match the person this link came from, and it was refused. That can be an interception attempt, or just a stale retry or a network hiccup. Your request is still waiting for the person who actually invited you; check with them before using the link again.": "Llegó un mensaje de bienvenida que no coincidía con la persona de la que venía este enlace, y se rechazó. Puede ser un intento de interceptación, o solo un reintento antiguo o un fallo de red. Tu solicitud sigue esperando a la persona que realmente te invitó: consúltalo con ella antes de volver a usar el enlace.",
  "A welcome that did not match the link's sender was refused. That can be an interception attempt, or just a stale retry. Check with whoever gave you the link before you use it again.": "Se rechazó un mensaje de bienvenida que no coincidía con quien envió el enlace. Puede ser un intento de interceptación, o solo un reintento antiguo. Consúltalo con quien te dio el enlace antes de volver a usarlo.",
  "Accept the new keys": "Aceptar las claves nuevas",
  "Accepting gives the whole circle new keys and lets them see everyone's location from then on. They cannot read anything sent before.": "Aceptar le da al círculo entero claves nuevas y les permite ver la ubicación de todos a partir de ese momento. No pueden leer nada enviado antes.",
  "Add Starling to your home screen": "Añade Starling a tu pantalla de inicio",
  "Another link, for one more person": "Otro enlace, para una persona más",
  "Anyone who checks this phone's storage can see that a duress code exists, though not what it is. What they cannot do is tell it apart from your real passcode while typing.": "Cualquiera que revise el almacenamiento de este teléfono puede ver que existe un código de coacción, aunque no cuál es. Lo que no puede hacer es distinguirlo de tu código de acceso real mientras lo escribes.",
  "Anyone you send one of these to can watch your live location on any phone or computer, with no app and no account. A link shows this emergency only, never your circle, and never the other links.": "Cualquiera a quien le envíes uno de estos puede ver tu ubicación en vivo desde cualquier teléfono u ordenador, sin app y sin cuenta. Un enlace muestra solo esta emergencia, nunca tu círculo, y nunca los otros enlaces.",
  "App lock is off.": "El bloqueo de la app está desactivado.",
  "App lock is on.": "El bloqueo de la app está activado.",
  "Arrive and leave alerts": "Avisos de llegada y salida",
  "Ask to join": "Pedir unirse",
  "At {place}": "En {place}",
  "Auto": "Auto",
  "Auto-lock": "Bloqueo automático",
  "Avatar {em}": "Avatar {em}",
  "Basemap": "Mapa base",
  "Battery {pct} percent": "Batería al {pct} por ciento",
  "Biometric unlock did not work. Use your passcode.": "El desbloqueo biométrico no funcionó. Usa tu código de acceso.",
  "Biometric unlock is off.": "El desbloqueo biométrico está desactivado.",
  "Cancel the request": "Cancelar la solicitud",
  "Cancel this link": "Cancelar este enlace",
  "Center the map on me": "Centrar el mapa en mí",
  "Change passcode": "Cambiar código de acceso",
  "Check": "Comprobar",
  "Check again": "Comprobar de nuevo",
  "Check in with your circle": "Avisar a tu círculo",
  "Check the numbers": "Comprueba los números",
  "Check their safety number with them first. Accepting is what lets them see everyone's location.": "Comprueba primero su número de seguridad con ellos. Aceptar es lo que les permite ver la ubicación de todos.",
  "Check {who}'s number": "Comprobar el número de {who}",
  "Checked in": "Avisado",
  "Choose a passcode to lock Starling on this device. There is no reset: if you forget it, you have to erase this device and rejoin from an invite.": "Elige un código de acceso para bloquear Starling en este dispositivo. No hay forma de restablecerlo: si lo olvidas, tienes que borrar este dispositivo y volver a unirte con una invitación.",
  "Circle name": "Nombre del círculo",
  "Clear status": "Borrar estado",
  "Close": "Cerrar",
  "Close member card": "Cerrar la tarjeta del miembro",
  "Compare in person": "Comparar en persona",
  "Connected": "Conectado",
  "Continue": "Continuar",
  "Coordinates copied": "Coordenadas copiadas",
  "Copy": "Copiar",
  "Copy coordinates": "Copiar coordenadas",
  "Copy failed": "No se pudo copiar",
  "Copy failed. Long-press the link instead.": "No se pudo copiar. Mantén pulsado el enlace en su lugar.",
  "Copy link": "Copiar enlace",
  "Could not cancel the link. Try again.": "No se pudo cancelar el enlace. Inténtalo de nuevo.",
  "Could not change the Orbot setting.": "No se pudo cambiar el ajuste de Orbot.",
  "Could not join. Try again.": "No fue posible unirse. Inténtalo de nuevo.",
  "Could not leave. Try again.": "No se pudo salir. Inténtalo de nuevo.",
  "Could not let them in. Try again.": "No se pudo dejarlos entrar. Inténtalo de nuevo.",
  "Could not make an invite link. Try again.": "No se pudo crear el enlace de invitación. Inténtalo de nuevo.",
  "Could not make another link.": "No se pudo crear otro enlace.",
  "Could not make new keys right now. Try again in a moment.": "No se pudieron generar claves nuevas ahora. Inténtalo de nuevo en un momento.",
  "Could not make new keys. Try again.": "No se pudieron generar claves nuevas. Inténtalo de nuevo.",
  "Could not reach anyone with the new keys. Nothing changed.": "No se pudo contactar a nadie con las claves nuevas. Nada cambió.",
  "Could not reach the relay to check the time.": "No se pudo contactar al relay para comprobar la hora.",
  "Could not reach them to send the keys, so nobody was let in. Try again in a moment.": "No se los pudo contactar para enviarles las claves, así que no se dejó entrar a nadie. Inténtalo de nuevo en un momento.",
  "Could not remove them. Nothing changed.": "No se pudo eliminarlos. Nada cambió.",
  "Could not save. Try again.": "No se pudo guardar. Inténtalo de nuevo.",
  "Could not send them the keys, so nobody was let in. Your link still works, so try again.": "No se les pudieron enviar las claves, así que no se dejó entrar a nadie. Tu enlace todavía funciona, así que inténtalo de nuevo.",
  "Could not send {who} the keys, and could not undo letting them in. Remove them from the circle before you try again.": "No se le pudieron enviar las claves a {who}, y no se pudo deshacer haberlo dejado entrar. Elimínalo del círculo antes de volver a intentarlo.",
  "Could not switch. Try again.": "No se pudo cambiar. Inténtalo de nuevo.",
  "Create a circle": "Crear un círculo",
  "Create circle": "Crear círculo",
  "Current": "Actual",
  "Dark": "Oscuro",
  "Demo circle": "Círculo de demostración",
  "Demo flight - nothing is real": "Vuelo de demostración: nada es real",
  "Directions": "Cómo llegar",
  "Done": "Listo",
  "Duress passcode removed.": "Código de coacción eliminado.",
  "Duress passcode saved.": "Código de coacción guardado.",
  "Encrypts your circle secret on this device. Nobody can open Starling, or read the secret from storage, without your passcode.": "Cifra el secreto de tu círculo en este dispositivo. Nadie puede abrir Starling, ni leer el secreto del almacenamiento, sin tu código de acceso.",
  "End-to-end encrypted. No accounts. Open protocol.": "Cifrado de extremo a extremo. Sin cuentas. Protocolo abierto.",
  "End-to-end encrypted. The relay sees ciphertext only.": "Cifrado de extremo a extremo. El relay solo ve texto cifrado.",
  "English is the app's source language. Translations come from the community; rough edges are worth reporting.": "El inglés es el idioma de origen de la app. Las traducciones vienen de la comunidad: si encuentras algo raro, vale la pena reportarlo.",
  "Enter your passcode to open your circle.": "Escribe tu código de acceso para abrir tu círculo.",
  "Enter your passcode to stop encrypting the circle secret at rest.": "Escribe tu código de acceso para dejar de cifrar el secreto del círculo almacenado en tu dispositivo.",
  "Erase and start over": "Borrar y empezar de nuevo",
  "Erases the circle secret, your identity, and all Starling data from this device, then reloads. One residual: street-map tiles your browser cached may remain in its own cache. The Off-grid basemap never loads any. There is no undo. Hold the button to confirm.": "Borra el secreto del círculo, tu identidad y todos los datos de Starling de este dispositivo, y luego recarga. Queda un resto: los mosaicos del mapa de calles que tu navegador haya guardado pueden quedar en su propia caché. El mapa base Fuera de red nunca carga ninguno. No hay forma de deshacerlo. Mantén pulsado el botón para confirmar.",
  "Every link stops updating and shows that the session ended. A new SOS makes new links.": "Todos los enlaces dejan de actualizarse y muestran que la sesión terminó. Un nuevo SOS crea enlaces nuevos.",
  "Everyone here is checked": "Todos aquí están comprobados",
  "Everyone in the circle gets a fresh key and the old one stops working, so anybody holding a copy of the old one goes dark. Do this if a phone in the circle was taken, unlocked, or handed over. Nobody is removed and nothing on your map disappears.": "Todos en el círculo reciben una clave nueva y la anterior deja de funcionar, así que cualquiera que tenga una copia de la vieja se queda a oscuras. Haz esto si a alguien del círculo le quitaron el teléfono, se lo desbloquearon o fue entregado a alguien. No se elimina a nadie y nada desaparece de tu mapa.",
  "Everyone in this circle, their safety numbers, and who you have checked.": "Todos los miembros de este círculo, sus números de seguridad y a quién has comprobado.",
  "Exit": "Salir",
  "Exit the demo first.": "Sal de la demostración primero.",
  "Exit the demo to edit your places.": "Sal de la demostración para editar tus lugares.",
  "Exit the demo to invite your people.": "Sal de la demostración para invitar a tu gente.",
  "Exit the demo to see your circle's keys.": "Sal de la demostración para ver las claves de tu círculo.",
  "Exit the demo to set a status.": "Sal de la demostración para poner un estado.",
  "Expand or collapse the circle sheet": "Expandir o contraer el panel del círculo",
  "Expires in {left}": "Expira en {left}",
  "Forgot passcode": "Olvidé mi código de acceso",
  "Get help from outside your circle": "Pide ayuda desde fuera de tu círculo",
  "Get outside help": "Pedir ayuda externa",
  "Get told when your people arrive": "Entérate cuando llegue tu gente",
  "Give the place a name first.": "Ponle un nombre al lugar primero.",
  "Got it": "Entendido",
  "Help link": "Enlace de ayuda",
  "Help links switched off": "Enlaces de ayuda desactivados",
  "Hold on, still finishing the last circle change.": "Espera, todavía estamos terminando el último cambio del círculo.",
  "Hold the phones side by side. Every group has to match.": "Sostén los teléfonos uno junto al otro. Todos los grupos tienen que coincidir.",
  "Hold to erase everything": "Mantén pulsado para borrar todo",
  "Hold to erase this device": "Mantén pulsado para borrar este dispositivo",
  "Hold to send SOS": "Mantén pulsado para enviar SOS",
  "Holds the screen on while the map is open": "Mantiene la pantalla encendida mientras el mapa está abierto",
  "How far back you can see": "Cuánto puedes ver hacia atrás",
  "How you appear to the people you invite. This never leaves your circle.": "Cómo apareces ante las personas que invitas. Esto nunca sale de tu círculo.",
  "How often your circle hears from you while you stay put. Moving sends sooner unless Steady sending is on. Slower is easier on the battery. An SOS always goes every 15 seconds.": "Cada cuánto tu círculo sabe de ti mientras no te mueves. Si te mueves se envía antes, salvo que el envío constante esté activado. Más lento gasta menos batería. Un SOS siempre sale cada 15 segundos.",
  "I have an invite": "Tengo una invitación",
  "Invite link": "Enlace de invitación",
  "Invite link cleared from your clipboard.": "Enlace de invitación borrado del portapapeles.",
  "Invite people": "Invitar personas",
  "Invite someone": "Invitar a alguien",
  "Invite your people": "Invita a tu gente",
  "It is about {n} minutes {dir}.": "Va unos {n} minutos {dir}.",
  "Its keys are out of memory and nothing you send arrives any more, but this device could not delete them from its own storage, most likely because there is no room left. They are still on the disk. Free some space and open Starling again to finish clearing it, or use Panic to erase everything now.": "Sus claves ya no están en memoria y nada de lo que envíes llega, pero este dispositivo no pudo borrarlas de su propio almacenamiento, probablemente porque no queda espacio. Siguen en el disco. Libera algo de espacio y abre Starling de nuevo para terminar de borrarlas, o usa el borrado de pánico para borrar todo ahora.",
  "Join a circle": "Unirte a un círculo",
  "Join with a link": "Unirte con un enlace",
  "Join with invite": "Unirte con invitación",
  "Just you here so far": "Por ahora solo estás tú aquí",
  "Keep screen awake": "Mantener la pantalla encendida",
  "Keep this screen on": "Mantener esta pantalla encendida",
  "Keys changed. Check before you trust it.": "Las claves cambiaron. Compruébalo antes de confiar.",
  "Keys older than this window are destroyed on this device and cannot be brought back, by you or by anyone holding the phone.": "Las claves más viejas que esta ventana de tiempo se destruyen en este dispositivo y no se pueden recuperar, ni por ti ni por nadie que tenga el teléfono.",
  "Language": "Idioma",
  "Language saved. Reopen settings to see them translated too.": "Idioma guardado. Vuelve a abrir los ajustes para verlos traducidos también.",
  "Last seen": "Última vez visto",
  "Last update {ago}": "Última actualización: {ago}",
  "Leave circle": "Salir del círculo",
  "Leave this circle": "Salir de este círculo",
  "Light": "Claro",
  "Link cancelled. It cannot be used now.": "Enlace cancelado. Ya no se puede usar.",
  "Live": "En vivo",
  "Live · Neighborhood": "En vivo · Vecindario",
  "Live · Precise": "En vivo · Precisa",
  "Locating...": "Localizando...",
  "Load map": "Cargar mapa",
  "Location is blocked": "La ubicación está bloqueada",
  "Location is not available in this browser.": "La ubicación no está disponible en este navegador.",
  "Location needs HTTPS. Open the deployed app or localhost.": "La ubicación necesita HTTPS. Abre la app desplegada o localhost.",
  "Location permission is off for Starling. Open the app's settings, allow location, then come back and tap Start sharing.": "El permiso de ubicación está desactivado para Starling. Abre los ajustes de la app, permite la ubicación y luego vuelve y toca Empezar a compartir.",
  "Location stopped: {reason}": "Ubicación detenida: {reason}",
  "Locked": "Bloqueado",
  "Low battery alerts": "Avisos de batería baja",
  "Make another link": "Crear otro enlace",
  "Make new keys": "Generar claves nuevas",
  "Mark verified": "Marcar como verificado",
  "Member": "Miembro",
  "Name the spots that matter and hear about arrivals. Places never leave this phone.": "Ponle nombre a los lugares que importan y entérate de las llegadas. Los lugares nunca salen de este teléfono.",
  "Name the spots that matter, like Home or School, and Starling tells you when someone in your circle arrives or leaves. Places are stored only on this phone. They are never sent anywhere, and the relay cannot learn they exist.": "Ponle nombre a los lugares que importan, como Casa o Escuela, y Starling te avisa cuando alguien de tu círculo llega o se va. Los lugares se guardan solo en este teléfono. Nunca se envían a ningún sitio, y el relay no puede saber que existen.",
  "Neighborhood": "Vecindario",
  "Neighborhood rounds your position to about 1 km on your device before it is encrypted": "Vecindario redondea tu posición a aproximadamente 1 km en tu dispositivo antes de cifrarla",
  "New circle": "Círculo nuevo",
  "New keys now": "Claves nuevas ahora",
  "New keys were made while this device could not be reached, and they cannot be worked out from the old ones. Nothing you send now arrives. Ask somebody in the circle for a fresh invite link.": "Se generaron claves nuevas mientras no se podía contactar a este dispositivo, y no se pueden deducir a partir de las anteriores. Nada de lo que envíes ahora llega. Pídele a alguien del círculo un enlace de invitación nuevo.",
  "New link ready to send.": "Enlace nuevo listo para enviar.",
  "No location fix yet. Still trying...": "Todavía sin ubicación. Aún intentando...",
  "No location yet. Start sharing to place yourself.": "Todavía sin ubicación. Empieza a compartir para ubicarte.",
  "No position yet. Start sharing first, or pick the spot on the map.": "Todavía sin posición. Empieza a compartir primero, o elige el punto en el mapa.",
  "No update from anyone in over {n} minutes. Usually that just means phones are asleep. But if others say they are sharing right now, this phone may have missed the circle's new keys; ask any member for a fresh invite to be sure.": "Nadie ha actualizado en más de {n} minutos. Normalmente eso solo significa que los teléfonos están en reposo. Pero si otros dicen que están compartiendo ahora mismo, puede que este teléfono se haya perdido las claves nuevas del círculo: pídele a cualquier miembro una invitación nueva para estar seguro.",
  "Nobody else in this circle yet": "Todavía nadie más en este círculo",
  "Nobody else is in this circle yet. Invite someone from the map.": "Todavía no hay nadie más en este círculo. Invita a alguien desde el mapa.",
  "Nobody has been heard from in a while": "Nadie ha dado señales de vida desde hace un rato.",
  "Nobody has told you the circle's real name yet (names travel encrypted, like everything else), so pick whatever you will recognize. Rename it any time in settings.": "Todavía nadie te ha dicho el nombre real del círculo (los nombres viajan cifrados, como todo lo demás), así que elige algo que reconozcas. Puedes cambiarlo cuando quieras desde los ajustes.",
  "Not connected": "Sin conexión",
  "Not now": "Ahora no",
  "Not sharing": "Sin compartir",
  "Not visible: this phone's clock is wrong": "No visible: el reloj de este teléfono está mal",
  "Now": "Ahora",
  "Numbers match, let them in": "Los números coinciden, dejar entrar",
  "Off-grid": "Fuera de red",
  "One of your circles expired while this phone was away": "Uno de tus círculos expiró mientras este teléfono estaba desconectado",
  "One use only, and it expires in {left}. Accepting somebody uses it up.": "Solo se puede usar una vez, y expira en {left}. Aceptar a alguien lo gasta.",
  "Open Starling to check their number and let them in.": "Abre Starling para comprobar su número y dejarlo entrar.",
  "Open Starling to see their live position.": "Abre Starling para ver su posición en vivo.",
  "Open app settings": "Abrir ajustes de la app",
  "Open members": "Abrir miembros",
  "Or your own words": "O tus propias palabras",
  "Panic wipe": "Borrado de pánico",
  "Passcode": "Código de acceso",
  "Passcode changed.": "Código de acceso cambiado.",
  "Paste the invite link someone sent you. The circle secret stays in the link fragment and never touches a server.": "Pega el enlace de invitación que te enviaron. El secreto del círculo se queda en el fragmento del enlace y nunca toca un servidor.",
  "People and keys": "Personas y claves",
  "Pick an avatar": "Elige un avatar",
  "Pick on the map": "Elegir en el mapa",
  "Places": "Lugares",
  "Point Starling at your own relay if you run one. The relay source ships with the app, so anyone can host it. Leave this empty for the default. A change applies the next time Starling starts.": "Apunta Starling a tu propio relay si tienes uno. El código del relay viene con la app, así que cualquiera puede alojarlo. Déjalo vacío para usar el predeterminado. Un cambio se aplica la próxima vez que Starling arranque.",
  "Precise": "Precisa",
  "Precision": "Precisión",
  "Press and hold to erase": "Mantén presionado para borrar",
  "Press and hold to send SOS": "Mantén presionado para enviar SOS",
  "Probably just quiet": "Probablemente solo está tranquilo",
  "Real map": "Mapa real",
  "Reconnecting": "Reconectando",
  "Reconnecting...": "Reconectando...",
  "Reject": "Rechazar",
  "Relay": "Relay",
  "Relay saved. It applies the next time Starling starts.": "Relay guardado. Se aplica la próxima vez que Starling arranque.",
  "Relock after the app has been in the background this long. Locking ends a share unless Keep sharing when the app is closed is on.": "Vuelve a bloquear después de que la app lleve tanto tiempo en segundo plano. El bloqueo termina lo que estés compartiendo, salvo que esté activado Seguir compartiendo cuando la app está cerrada.",
  "Remove": "Eliminar",
  "Remove duress passcode": "Eliminar código de coacción",
  "Remove them": "Eliminarlo",
  "Remove {name}": "Eliminar a {name}",
  "Request sent. Someone in the circle has to accept it from their phone.": "Solicitud enviada. Alguien del círculo tiene que aceptarla desde su teléfono.",
  "Require passcode": "Requerir código de acceso",
  "Review the request": "Revisar la solicitud",
  "Revoke": "Revocar",
  "Route through Orbot": "Enrutar a través de Orbot",
  "SOS": "SOS",
  "SOS active": "SOS activo",
  "SOS armed · Locating...": "SOS armado · Localizando...",
  "SOS armed · Sharing live": "SOS armado · Compartiendo en vivo",
  "SOS from {who}": "SOS de {who}",
  "SOS is armed": "El SOS está armado",
  "SOS sent to your circle. Tap the check mark to cancel.": "SOS enviado a tu círculo. Toca la marca de verificación para cancelarlo.",
  "Safety number {digits}": "Número de seguridad {digits}",
  "Save duress passcode": "Guardar código de coacción",
  "Save my current spot": "Guardar mi ubicación actual",
  "Saved. Your circle sees it once you start sharing.": "Guardado. Tu círculo lo ve en cuanto empieces a compartir.",
  "See who is here": "Ver quién está aquí",
  "Send": "Enviar",
  "Send every": "Enviar cada",
  "Send it through something you already trust, like Signal. Whoever opens it can ask to join; they are not in until you check their number and accept.": "Envíalo por algo en lo que ya confíes, como Signal. Quien lo abra puede pedir unirse: no entra hasta que compruebes su número y aceptes.",
  "Send on the timer even when you have not moved. The relay cannot read a position either way, but a burst of updates while you walk and silence while you sit is a movement trail made of timing alone. This hides that, and costs a little battery.": "Envía por temporizador incluso cuando no te has movido. El relay no puede leer la posición de todos modos, pero una ráfaga de actualizaciones mientras caminas y silencio mientras estás quieto forman un rastro de movimiento hecho solo de tiempos. Esto lo oculta, y cuesta un poco de batería.",
  "Send the link": "Enviar el enlace",
  "Sends relay and map traffic through Orbot's Tor proxy on this device. Needs Orbot installed with Power User Mode on. Orbot's per-app VPN mode also covers Starling with this off.": "Envía el tráfico del relay y del mapa a través del proxy Tor de Orbot en este dispositivo. Necesita tener Orbot instalado con \"Power User Mode\" activado. El modo VPN por app de Orbot también cubre a Starling aunque esto esté desactivado.",
  "Sent it to the wrong person?": "¿Se lo enviaste a la persona equivocada?",
  "Session ended": "Sesión terminada",
  "Set a passcode": "Elegir código de acceso",
  "Set a status for your circle": "Pon un estado para tu círculo",
  "Set status": "Poner estado",
  "Settings": "Ajustes",
  "Show the demo on a real map? Tiles of its Central Park stage load from openstreetmap.org - the demo's only network use.": "\u00bfVer la demostraci\u00f3n en un mapa real? Los mosaicos de su escenario de Central Park se cargan desde openstreetmap.org: el \u00fanico uso de red de la demostraci\u00f3n.",
  "Sharing (pretend)": "Compartiendo (simulado)",
  "Sharing live": "Compartiendo en vivo",
  "Sharing{run}, and this screen has to stay on": "Compartiendo{run}, y esta pantalla tiene que quedar encendida",
  "Show recent paths on the map": "Mostrar rutas recientes en el mapa",
  "Signal lost": "Señal perdida",
  "Somebody already in that circle has to accept your request. Read them your number: {digits}{jumped}": "Alguien que ya esté en ese círculo tiene que aceptar tu solicitud. Léele tu número: {digits}{jumped}",
  "Somebody else is jamming that invite link, so it cannot be used any more. Nobody was let in. Make a new link and send it again.": "Alguien más está saturando ese enlace de invitación, así que ya no se puede usar. No se dejó entrar a nadie. Crea un enlace nuevo y envíalo de nuevo.",
  "Someone": "Alguien",
  "Someone wants to join": "Alguien quiere unirse",
  "Starling cannot recover a forgotten passcode. Nothing about your circle leaves your device unencrypted, so there is no reset link. You can erase this device and rejoin your circle from a fresh invite. Hold the button to erase everything on this device.": "Starling no puede recuperar un código de acceso olvidado. Nada de tu círculo sale de tu dispositivo sin cifrar, así que no hay enlace para restablecerlo. Puedes borrar este dispositivo y volver a unirte a tu círculo con una invitación nueva. Mantén pulsado el botón para borrar todo en este dispositivo.",
  "Starling hit a problem while starting.": "Starling tuvo un problema al iniciar.",
  "Starling only gets good when your people are on the map. Send them your invite link.": "Starling solo funciona bien cuando tu gente está en el mapa. Envíales tu enlace de invitación.",
  "Starling throws a circle's keys away rather than carry them for weeks, and that circle passed the point where this device could still read it, so it was erased from this phone. {kept} Ask somebody in that circle for a fresh invite link if you want back in.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y ese círculo pasó el punto en el que este dispositivo todavía podía leerlo, así que se borró de este teléfono. {kept} Pídele a alguien de ese círculo un enlace de invitación nuevo si quieres volver a entrar.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this device passed that point while it was away. Its keys are gone from memory and from storage, and so is this phone's own identity in that circle, so nothing you send arrives and nothing sent to you can be read. Ask somebody in the circle for a fresh invite link.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y este dispositivo pasó ese punto mientras estaba desconectado. Sus claves desaparecieron de la memoria y del almacenamiento, y también la identidad de este teléfono en ese círculo, así que nada de lo que envíes llega y nada de lo que te envíen se puede leer. Pídele a alguien del círculo un enlace de invitación nuevo.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this phone passed that point while it was away. The circle was erased from this device, and there was no other circle to fall back to.{lockLine} Ask somebody for a fresh invite link, or start a new circle.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y este teléfono pasó ese punto mientras estaba desconectado. El círculo se borró de este dispositivo, y no había otro círculo al que recurrir.{lockLine} Pídele a alguien un enlace de invitación nuevo, o crea un círculo nuevo.",
  "Starling trusts whoever first answers with keys that match their member id. Reading these numbers out to each other is what turns that into knowing who is on your map.": "Starling confía en quien primero responda con claves que coincidan con su id de miembro. Leerse estos números en voz alta es lo que convierte eso en saber quién está en tu mapa.",
  "Start a new circle": "Crear un círculo nuevo",
  "Start fresh": "Empezar de cero",
  "Start sharing": "Empezar a compartir",
  "Steady sending": "Envío constante",
  "Steady sending is on too, so the relay cannot read your movement from the timing.": "El envío constante también está activado, así que el relay no puede leer tu movimiento a partir de los tiempos.",
  "Still about {n} minutes out.": "Todavía a unos {n} minutos.",
  "Stop sharing with helpers": "Dejar de compartir con los ayudantes",
  "Stopped": "Detenido",
  "Street maps load tiles from OpenStreetMap, which sees your map viewport. Off-grid loads nothing.": "Los mapas de calles cargan mosaicos desde OpenStreetMap, que ve el área visible de tu mapa. Fuera de red no carga nada.",
  "Switch circle": "Cambiar de círculo",
  "Switched to {name}.": "Cambiaste a {name}.",
  "Tap the map where {name} is.": "Toca el mapa donde está {name}.",
  "Tell me when a member's phone drops under 15 percent, before their dot goes dark": "Avísame cuando el teléfono de un miembro baje del 15 por ciento, antes de que su punto se apague",
  "Tell me when someone in the circle reaches a place or leaves one": "Avísame cuando alguien del círculo llegue a un lugar o salga de uno",
  "That circle expired, and this device could not erase all of it. Open Starling again to finish clearing it.": "Ese círculo expiró, y este dispositivo no pudo borrarlo por completo. Abre Starling de nuevo para terminar de borrarlo.",
  "That circle expired, and this phone could not erase it": "Ese círculo expiró, y este teléfono no pudo borrarlo",
  "That does not look like a Starling invite link.": "Eso no parece un enlace de invitación de Starling.",
  "That invitation arrived incomplete": "Esa invitación llegó incompleta",
  "That invitation expired. Make a new link.": "Esa invitación expiró. Crea un enlace nuevo.",
  "That is the lot: {n} places is the cap.": "Eso es todo: el límite es de {n} lugares.",
  "That is your duress passcode. Pick a different one.": "Ese es tu código de coacción. Elige uno diferente.",
  "That is your own invite link.": "Ese es tu propio enlace de invitación.",
  "That is your unlock passcode. A duress code has to be different.": "Ese es tu código de acceso normal. El código de coacción tiene que ser diferente.",
  "That link is dead. The others still work.": "Ese enlace ya no funciona. Los demás siguen funcionando.",
  "Tap once more to erase everything": "Toca una vez más para borrarlo todo",
  "Tap once more to send SOS": "Toca una vez más para enviar SOS",
  "That passcode is right, but this install's stored data will not open. Nothing was erased.": "Ese código de acceso es correcto, pero los datos guardados de esta instalación no se abren. No se borró nada.",
  "That phone is answering with keys this device has never seen. It is a reinstall, or somebody else in {who}'s place, and nothing here can tell you which. Their location stays off your map until you check the number with them and accept it.": "Ese teléfono está respondiendo con claves que este dispositivo nunca ha visto. Es una reinstalación, o alguien más en el lugar de {who}, y nada aquí puede decirte cuál de las dos. Su ubicación se mantiene fuera de tu mapa hasta que compruebes el número con esa persona y lo aceptes.",
  "That request's keys are malformed. Nobody was let in.": "Las claves de esa solicitud están mal formadas. No se dejó entrar a nadie.",
  "The SOS is cleared.": "El SOS se canceló.",
  "The clock looks right now. Your circle can see you again.": "El reloj se ve bien ahora. Tu círculo puede verte de nuevo.",
  "The demo has its own Real map button. Your choice here applies when you exit.": "La demostración tiene su propio botón de Mapa real. Lo que elijas aquí se aplica cuando salgas.",
  "The label is for you. It is never sent anywhere.": "La etiqueta es solo para ti. Nunca se envía a ningún sitio.",
  "The link stops working immediately, and any request already waiting on it is dropped. Open Invite again for a fresh one.": "El enlace deja de funcionar de inmediato, y cualquier solicitud que ya estuviera esperando se descarta. Abre Invitar de nuevo para conseguir uno nuevo.",
  "The relay that passes your updates along stores only encrypted data it cannot read, and deletes it after 24 hours. The protocol is open, so anyone can check these claims against the code.": "El relay que transmite tus actualizaciones solo guarda datos cifrados que no puede leer, y los borra después de 24 horas. El protocolo es abierto, así que cualquiera puede comprobar estas afirmaciones contra el código.",
  "Their dot may go dark soon.": "Es posible que su punto se apague pronto.",
  "Their number is {theirs}. Yours is {mine}. Read them to each other out loud, on a line you already trust. Nothing else in this circle has been checked by a person yet.": "Su número es {theirs}. El tuyo es {mine}. Léanselos en voz alta el uno al otro, por un canal en el que ya confíen. Nada más en este círculo ha sido comprobado por una persona todavía.",
  "Theme": "Tema",
  "They": "Ellos",
  "This browser is blocking storage. Starling runs, but nothing is saved after you close it.": "Este navegador está bloqueando el almacenamiento. Starling funciona, pero no se guarda nada después de cerrarlo.",
  "This is taking a while. The person who invited you may not have seen the request yet, or the link may have expired. Reach them however you normally would; a fresh link takes a minute to make.": "Esto está tardando. Puede que la persona que te invitó todavía no haya visto la solicitud, o que el enlace haya expirado. Contáctala como lo harías normalmente: crear un enlace nuevo toma un minuto.",
  "This is the number your circle should hear from you.": "Este es el número que tu círculo debería escuchar de ti.",
  "This phone has been offline too long": "Este teléfono ha estado desconectado demasiado tiempo",
  "This phone's clock is wrong": "El reloj de este teléfono está mal",
  "This phone's clock is wrong, so your circle cannot see you.{off} Turn on automatic date and time.": "El reloj de este teléfono está mal, así que tu círculo no puede verte.{off} Activa la fecha y hora automáticas.",
  "This sends a request. Somebody already in the circle has to check your safety number and accept it before you can see anyone, or they you. That check is how they know the request really came from you and not from somebody who got hold of the link.": "Esto envía una solicitud. Alguien que ya esté en el círculo tiene que comprobar tu número de seguridad y aceptarla antes de que puedas ver a cualquiera, o ellos a ti. Esa comprobación es como saben que la solicitud realmente vino de ti y no de alguien que consiguió el enlace.",
  "Those keys are gone": "Esas claves ya no existen",
  "Those new keys are malformed. They were not accepted.": "Esas claves nuevas están mal formadas. No se aceptaron.",
  "Trail": "Rastro",
  "Trail history": "Historial de rastro",
  "Try again": "Inténtalo de nuevo",
  "Turn off app lock": "Desactivar el bloqueo de la app",
  "Turn on app lock": "Activar el bloqueo de la app",
  "Turned down. Your link still works for whoever it was meant for.": "Rechazada. Tu enlace todavía funciona para quien iba dirigido.",
  "Unlock": "Desbloquear",
  "Unlock with biometrics": "Desbloquear con biometría",
  "Unlocking...": "Desbloqueando...",
  "Update Starling": "Actualizar Starling",
  "Use at least {n} characters.": "Usa al menos {n} caracteres.",
  "Use this device's Face ID, fingerprint, or Windows Hello to unlock. Your passcode still works as backup.": "Usa el Face ID, la huella o Windows Hello de este dispositivo para desbloquear. Tu código de acceso sigue funcionando como respaldo.",
  "Waiting to be let into {name}": "Esperando a que te dejen entrar a {name}",
  "Was": "Antes",
  "Watch the demo": "Ver la demostración",
  "What Starling is and how it works &#8599;": "Qué es Starling y cómo funciona &#8599;",
  "When you are safe": "Cuando estés a salvo",
  "Wrong passcode. Try again.": "Código de acceso incorrecto. Inténtalo de nuevo.",
  "You already asked to join. They still have to let you in.": "Ya pediste unirte. Todavía tienen que dejarte entrar.",
  "You have an invite to a circle. Set up how you will appear to the people in it.": "Tienes una invitación a un círculo. Configura cómo aparecerás ante las personas que están en él.",
  "You have checked this number with {who}.": "Has comprobado este número con {who}.",
  "You joined the circle.": "Te uniste al círculo.",
  "You left. Now in {name}.": "Saliste. Ahora estás en {name}.",
  "You're in": "Ya estás dentro",
  "Your app lock and your other circles were not touched.": "Tu bloqueo de la app y tus otros círculos no se tocaron.",
  "Your app lock is untouched and still protects whatever you set up next.": "Tu bloqueo de la app sigue intacto y sigue protegiendo lo que configures a continuación.",
  "Your browser is blocking location for this site. Allow location in your browser's site settings, then tap Start sharing again.": "Tu navegador está bloqueando la ubicación para este sitio. Permite la ubicación en los ajustes del sitio de tu navegador, y luego toca Empezar a compartir de nuevo.",
  "Your circle cannot see you. The relay refuses anything stamped with a time that far out, so your position is not going anywhere.{off} Turn on automatic date and time, then check again.": "Tu círculo no puede verte. El relay rechaza cualquier cosa marcada con una hora tan desfasada, así que tu posición no va a ningún lado.{off} Activa la fecha y hora automáticas, y luego comprueba de nuevo.",
  "Your circle has new keys, but they could not be saved. If Starling restarts you will need a fresh invitation.": "Tu círculo tiene claves nuevas, pero no se pudieron guardar. Si Starling se reinicia, necesitarás una invitación nueva.",
  "Your circle has new keys.": "Tu círculo tiene claves nuevas.",
  "Your circle moved on without this phone": "Tu círculo siguió adelante sin este teléfono",
  "Your circle sees an alert at your live position. Tap the check mark above to cancel it and let everyone know you are okay.": "Tu círculo ve una alerta en tu posición en vivo. Toca la marca de verificación de arriba para cancelarla y avisarles a todos que estás bien.",
  "Your circles": "Tus círculos",
  "Your current circle stays. This adds a new one, and you can switch between them from the circle name at the top of the map.": "Tu círculo actual se mantiene. Esto añade uno nuevo, y puedes cambiar entre ellos desde el nombre del círculo en la parte superior del mapa.",
  "Your list of members does not match": "Tu lista de miembros no coincide",
  "Your name": "Tu nombre",
  "Your number": "Tu número",
  "Your other circles": "Tus otros círculos",
  "Your other circles could not be read and were dropped.": "Tus otros círculos no se pudieron leer y se descartaron.",
  "Your other circles were not touched.": "Tus otros círculos no se tocaron.",
  "Your people, on your map. Nobody else.": "Tu gente, en tu mapa. Nadie más.",
  "Your positions are encrypted on this device with a key only your circle holds. There are no accounts, no phone numbers, and no server that can read where you are. Sharing is off until you turn it on, and stopping is one tap.": "Tus posiciones se cifran en este dispositivo con una clave que solo tiene tu círculo. No hay cuentas, ni números de teléfono, ni ningún servidor que pueda leer dónde estás. Compartir está desactivado hasta que lo actives, y detenerlo es un solo toque.",
  "Your request is waiting on the relay. Somebody already in the circle has to check your number and accept it, and they do not have to be online right now.": "Tu solicitud está esperando en el relay. Alguien que ya esté en el círculo tiene que comprobar tu número y aceptarlo, y no hace falta que esté conectado ahora mismo.",
  "Your request was accepted. Your circle is on the map.": "Tu solicitud fue aceptada. Tu círculo está en el mapa.",
  "Your status": "Tu estado",
  "a member": "un miembro",
  "ahead": "de adelanto",
  "behind": "de atraso",
  "for {t}": "durante {t}",
  "not available": "no disponible",
  "not ready yet": "todavía no está listo",
  "now": "ahora",
  "service error": "error del servicio",
  "starling": "starling",
  "the person who let you in": "la persona que te dejó entrar",
  "them": "ellos",
  "{failed} of {total} members did not get the new keys yet.": "{failed} de {total} miembros aún no tienen las claves nuevas.",
  "{name} radius": "Radio de {name}",
  "{name} saved. Only this phone knows it exists.": "{name} guardado. Solo este teléfono sabe que existe.",
  "{n} members' keys changed": "Las claves de {n} miembros cambiaron",
  "{who} arrived at {place}": "{who} llegó a {place}",
  "{who} can read nothing this circle sends from now on. Everyone still here got new keys.": "{who} no puede leer nada de lo que este círculo envíe a partir de ahora. Todos los que siguen aquí tienen claves nuevas.",
  "{who} changed the keys": "{who} cambió las claves",
  "{who} changed the keys.": "{who} cambió las claves.",
  "{who} checked in": "{who} avisó",
  "{who} is now pinned to the new keys.": "Las claves nuevas quedaron ancladas a {who}.",
  "{who} is out. Everyone else has new keys.": "{who} está fuera. Todos los demás tienen claves nuevas.",
  "{who} joined. Everyone got new keys.": "{who} se unió. Todos recibieron claves nuevas.",
  "{who} left {place}": "{who} salió de {place}",
  "{who} made new keys, but your list of members does not match theirs.": "{who} generó claves nuevas, pero tu lista de miembros no coincide con la suya.",
  "{who} removed {gone}": "{who} eliminó a {gone}",
  "{who} removed {gone}.": "{who} eliminó a {gone}.",
  "{who} removed {n} people": "{who} eliminó a {n} personas",
  "{who} removed {n} people from the circle.": "{who} eliminó a {n} personas del círculo.",
  "{who} wants to join": "{who} quiere unirse",
  "{who} wants to join. Check their safety number.": "{who} quiere unirse. Comprueba su número de seguridad.",
  "{who}'s keys changed": "Las claves de {who} cambiaron",
  "{who}'s keys changed. Their location is hidden until you accept it.": "Las claves de {who} cambiaron. Su ubicación está oculta hasta que lo aceptes.",
  "{who}'s phone is at {pct}%": "El teléfono de {who} está al {pct}%",
  "{dist} to the {way} of you": "{dist} al {way} de ti",
  "{n} sets of keys besides yours can decrypt what you send: {checked} checked by a person, {unchecked} trusted on first use.": "{n} juegos de claves adem\u00e1s del tuyo pueden descifrar lo que env\u00edas: {checked} comprobados por una persona, {unchecked} confiados en el primer uso.",
  "A newly admitted key can also read back {window} of history. That window is yours to set in Settings.": "Una clave reci\u00e9n admitida tambi\u00e9n puede leer {window} de historial hacia atr\u00e1s. Esa ventana la eliges t\u00fa en Ajustes.",
  "A place with the privacy fence on shares only its center while you are inside it, never your exact spot within. Your circle still sees you are there; what they stop seeing is where in there. An SOS always sends your real position.": "Un lugar con la valla de privacidad activada comparte solo su centro mientras est\u00e1s dentro, nunca tu punto exacto ah\u00ed. Tu c\u00edrculo sigue viendo que est\u00e1s ah\u00ed; lo que deja de ver es en qu\u00e9 parte. Un SOS siempre env\u00eda tu posici\u00f3n real.",
  "Check-in delivered. Your circle sees it now.": "Aviso entregado. Tu c\u00edrculo ya lo ve.",
  "Check-in not delivered yet. Starling keeps trying.": "El aviso no se ha entregado todav\u00eda. Starling sigue intent\u00e1ndolo.",
  "Check-in queued. Starling keeps trying...": "Aviso en cola. Starling sigue intent\u00e1ndolo...",
  "Copied. Paste it anywhere you keep your records.": "Copiado. P\u00e9galo donde guardes tus registros.",
  "Copy it all": "Copiarlo todo",
  "Download as a file": "Descargar como archivo",
  "east": "este",
  "Everything Starling keeps about you, on this device and nowhere else. Positions are absent because they are never stored; keys are absent on purpose.": "Todo lo que Starling guarda sobre ti, en este dispositivo y en ning\u00fan otro sitio. No hay posiciones porque nunca se almacenan; no hay claves, a prop\u00f3sito.",
  "never": "nunca",
  "north": "norte",
  "northeast": "noreste",
  "northwest": "noroeste",
  "One readable file: profile, settings, places, circle names, who you trust. No positions, because Starling stores none, and no keys, ever.": "Un archivo legible: perfil, ajustes, lugares, nombres de c\u00edrculos, en qui\u00e9n conf\u00edas. Sin posiciones, porque Starling no guarda ninguna, y sin claves, jam\u00e1s.",
  "Only your own keys can decrypt what you send. The relay stores ciphertext it cannot open.": "Solo tus propias claves pueden descifrar lo que envías. El relay guarda información cifrada que no puede abrir.",
  "Privacy fence": "Valla de privacidad",
  "Privacy fence for {name}": "Valla de privacidad para {name}",
  "See everything Starling has": "Ver todo lo que Starling tiene",
  "Share timer": "Temporizador de compartir",
  "SOS delivered to your circle.": "SOS entregado a tu c\u00edrculo.",
  "SOS not delivered yet. Starling keeps trying.": "El SOS no se ha entregado todav\u00eda. Starling sigue intent\u00e1ndolo.",
  "SOS queued. Starling keeps trying...": "SOS en cola. Starling sigue intent\u00e1ndolo...",
  "south": "sur",
  "southeast": "sureste",
  "southwest": "suroeste",
  "stops in {left}": "se detiene en {left}",
  "Stop by itself:": "Parar solo:",
  "telling your circle...": "avisando a tu c\u00edrculo...",
  "Sharing was on when the app closed, so it is back on.":
    "La ubicaci\u00f3n se estaba compartiendo cuando se cerr\u00f3 la aplicaci\u00f3n, as\u00ed que vuelve a estar activa.",
  "Timed share ended. Your circle sees you stopped sharing.": "El tiempo de compartir termin\u00f3. Tu c\u00edrculo ve que dejaste de compartir.",
  "west": "oeste",
  "Who could read you": "Qui\u00e9n podr\u00eda leerte",
  "Your circle now sees you stopped sharing.": "Tu c\u00edrculo ya ve que dejaste de compartir.",
  "Your data": "Tus datos",
  "10 minutes": "10 minutos",
  "1 hour": "1 hora",
  "6 hours": "6 horas",
  "24 hours": "24 horas",
  "Your last share was stopped outside the app": "Tu último compartir se detuvo fuera de la app",
  "Android shut down the part of Starling that sends your position, so the share stopped. Nobody did this by hand.": "Android cerr\u00f3 la parte de Starling que env\u00eda tu posici\u00f3n, as\u00ed que el compartir se detuvo. Nadie lo hizo a mano.",
  "Someone tapped Stop on the sharing notification. If that was not you, check who has access to this phone.": "Alguien tocó Detener en la notificación de compartir ubicación. Si no fuiste tú, revisa quién tiene acceso a este teléfono.",
  "The app was closed while sharing was on, which stops it every time. If that was not you, check who has access to this phone.": "La app se cerró mientras compartías tu ubicación, y eso siempre la detiene. Si no fuiste tú, revisa quién tiene acceso a este teléfono.",
  "The app was closed while sharing was on, which stopped it, and opening it again put it back on. If closing it was not you, check who has access to this phone.":
    "La app se cerró mientras compartías tu ubicación, eso la detuvo, y al abrirla de nuevo volvió a activarse. Si no fuiste tú quien la cerró, revisa quién tiene acceso a este teléfono.",
  "Keep sharing when the app is closed": "Seguir compartiendo cuando la app est\u00e1 cerrada",
  "Sharing normally stops when you swipe Starling out of recents, because the keys that encrypt each position live in the app. With this on, Starling stays loaded in the background until the share ends, so closing it does not stop it. Anyone holding your unlocked phone can see the app is still running, and it is still holding your keys, so the app lock cannot protect them until the share ends.":
    "Normalmente el compartir se detiene cuando quitas Starling de las apps recientes, porque las claves que cifran cada posici\u00f3n viven en la app. Con esto activado, Starling sigue cargada en segundo plano hasta que termina el compartir, as\u00ed que cerrarla no lo detiene. Cualquiera que tenga tu tel\u00e9fono desbloqueado puede ver que la app sigue funcionando, y sigue guardando tus claves, as\u00ed que el bloqueo de la app no puede protegerlas hasta que el compartir termine.",
  "Closing the app will not stop a share now.": "Cerrar la app ahora no detendrá el compartir.",
  "Closing the app stops a share again.": "Cerrar la app vuelve a detener el compartir.",
  "Could not change that setting.": "No se pudo cambiar ese ajuste.",
  "Sharing was stopped from the notification.": "Se detuvo el compartir desde la notificación.",
  "Made by {name}": "Hecho por {name}",
  "They chose the name {who}. Anyone can type any name, so the number below is the only part that proves who they are.":
    "Eligió el nombre {who}. Cualquiera puede escribir cualquier nombre, así que el número de abajo es lo único que demuestra quién es.",
  "Source code": "Código fuente",
  "Allow": "Permitir",
  "Allow background running": "Permitir en segundo plano",
  "Android had stopped your share in the background. It is back on.": "Android había detenido tu compartir en segundo plano. Ya está activo otra vez.",
  "Android kept Starling from running in the background, so your circle stopped getting your location and the share ended. Nobody did this by hand.": "Android no dejó que Starling siguiera funcionando en segundo plano, así que tu círculo dejó de recibir tu ubicación y el compartir terminó. Nadie lo hizo a mano.",
  "Android may pause Starling to save battery while your screen is off, and your circle would stop seeing you move. Letting Starling run in the background stops that. It only makes a difference while you share.": "Android puede pausar Starling para ahorrar batería mientras la pantalla está apagada, y tu círculo dejaría de verte moverte. Dejar que Starling funcione en segundo plano lo evita. Solo importa mientras compartes.",
  "Android stopped Starling in the background because its battery use is set to Restricted, and that ends every share a minute after you leave the app. Set it to Unrestricted in the app's settings.": "Android detuvo Starling en segundo plano porque su uso de batería está en Restringido, y eso termina cada compartir un minuto después de salir de la app. Cámbialo a Sin restricciones en los ajustes de la app.",
  "Android stopped Starling in the background, so the share ended. Nobody did this by hand.": "Android detuvo Starling en segundo plano, así que el compartir terminó. Nadie lo hizo a mano.",
  "Android will stop this share when you leave the app": "Android detendrá este compartir cuando salgas de la app",
  "Battery Saver is turning off your location": "El Ahorro de batería está apagando tu ubicación",
  "Copy sharing report": "Copiar informe de compartir",
  "Could not copy the report.": "No se pudo copiar el informe.",
  "For a bug report: versions, permissions, battery settings and counts. It has no locations, no keys and no names in it.": "Para reportar un error: versiones, permisos, ajustes de batería y conteos. No incluye ubicaciones, ni claves, ni nombres.",
  "For {name}. Each circle keeps its own precision and timing.": "Para {name}. Cada círculo guarda su propia precisión y frecuencia.",
  "It is back on now that the app is open.": "Ya está activo otra vez porque abriste la app.",
  "Keep sharing with the screen off": "Sigue compartiendo con la pantalla apagada",
  "Location is off on this phone. Turn it on to keep sharing.": "La ubicación está desactivada en este teléfono. Actívala para seguir compartiendo.",
  "Not reaching your circle": "No llega a tu círculo",
  "Optimized. Android may pause Starling to save battery while the screen is off, which can stop your circle seeing you move. Allowing it to run in the background prevents that.": "Optimizado. Android puede pausar Starling para ahorrar batería mientras la pantalla está apagada, y tu círculo podría dejar de verte moverte. Permitir que funcione en segundo plano lo evita.",
  "Restricted. Android stops Starling about a minute after you leave it, and a share stops with it. Set battery use to Unrestricted in the app's settings.": "Restringido. Android detiene Starling más o menos un minuto después de que sales de ella, y el compartir se detiene también. Cambia el uso de batería a Sin restricciones en los ajustes de la app.",
  "Running in the background": "Funcionamiento en segundo plano",
  "Sharing report copied. It has no locations and no keys in it.": "Informe copiado. No incluye ubicaciones ni claves.",
  "SOS armed · Not reaching your circle": "SOS armado · No llega a tu círculo",
  "Starling only has your approximate location": "Starling solo tiene tu ubicación aproximada",
  "Starling's battery use is set to Restricted, so Android stops a share about a minute after the app leaves the screen. Set it to Unrestricted in the app's settings to keep sharing with the screen off.": "El uso de batería de Starling está en Restringido, así que Android detiene el compartir más o menos un minuto después de que la app sale de la pantalla. Cámbialo a Sin restricciones en los ajustes de la app para seguir compartiendo con la pantalla apagada.",
  "Unrestricted. Android lets Starling keep a share going with the screen off.": "Sin restricciones. Android deja que Starling siga compartiendo con la pantalla apagada.",
  "With approximate location, Android updates your position roughly and only about every ten minutes, so your circle sees you jump. Allow precise location in the app's settings for a live share.": "Con la ubicación aproximada, Android actualiza tu posición de forma imprecisa y solo cada diez minutos más o menos, así que tu círculo te ve saltar. Permite la ubicación precisa en los ajustes de la app para compartir en vivo.",
  "With Battery Saver on, this phone turns location off while the screen is off, so your circle stops seeing you move. Turn Battery Saver off to keep sharing.": "Con el Ahorro de batería activado, este teléfono apaga la ubicación mientras la pantalla está apagada, así que tu círculo deja de verte moverte. Desactiva el Ahorro de batería para seguir compartiendo.",
  "nothing sent yet": "nada enviado todavía",
  "last sent {ago} ago": "último envío hace {ago}",
  "Keep sharing": "Seguir compartiendo",
  "Shares now keep running while Starling is closed or locked.": "Ahora lo que compartes sigue activo aunque Starling esté cerrada o bloqueada.",
  "SOS armed · Location is off": "SOS armado · Ubicación desactivada",
  "Starling locked itself while you were away, and a locked Starling holds no keys, so the lock ended your share.": "Starling se bloqueó mientras no estabas, y una Starling bloqueada no guarda claves, así que el bloqueo terminó lo que estabas compartiendo.",
  "Starling locks itself after a while in the background, and a locked Starling holds no keys, so the lock would end this share.": "Starling se bloquea después de un rato en segundo plano, y una Starling bloqueada no guarda claves, así que el bloqueo terminaría lo que estás compartiendo.",
  "Tap Keep sharing to let shares run while Starling is closed or locked. The lock then waits until the share ends.": "Toca Seguir compartiendo para que se siga compartiendo aunque Starling esté cerrada o bloqueada. El bloqueo espera entonces a que termines de compartir.",
  "The app lock ended your share": "El bloqueo de la app terminó lo que compartías",
  "The app lock had ended your share. It is back on.": "El bloqueo de la app había terminado lo que compartías. Ya está activo otra vez.",
  "The app lock will end this share": "El bloqueo de la app terminará lo que compartes",
  "Unlocking put it back on.": "Al desbloquearla, se volvió a activar.",
  "also to {host}": "también a {host}",
  "Changing where your position goes needs your passcode.": "Cambiar adónde va tu ubicación requiere tu código de acceso.",
  "Enter your passcode": "Escribe tu código de acceso",
  "Paused while Tor mode is on, so nothing leaves this phone outside Tor.": "En pausa mientras el modo Tor esté activado, para que nada salga de este teléfono fuera de Tor.",
  "Save": "Guardar",
  "Sends your own position in OwnTracks format to a server you run, like Reitti, Dawarich or Home Assistant, only while you share. It goes straight from this phone, never through the relay, and your circle's positions never go there. The server gets your precise position whatever the precision setting. With the app lock on, changing it needs your passcode.": "Envía tu propia ubicación en formato OwnTracks a un servidor que tú administras, como Reitti, Dawarich o Home Assistant, solo mientras compartes. Sale directamente de este teléfono, nunca a través del relay, y las ubicaciones de tu círculo nunca van ahí. El servidor recibe tu ubicación precisa, sea cual sea el ajuste de precisión. Con el bloqueo de la app activado, cambiarlo requiere tu código de acceso.",
  "Stop sending": "Dejar de enviar",
  "That address did not work. Use a full https address.": "Esa dirección no funcionó. Usa una dirección https completa.",
  "That passcode is wrong.": "Ese código de acceso es incorrecto.",
  "The last send failed: the server answered {code}.": "El último envío falló: el servidor respondió {code}.",
  "The last send failed: the server did not answer.": "El último envío falló: el servidor no respondió.",
  "The last send worked.": "El último envío funcionó.",
  "Use a full https address, like https://your-server/owntracks": "Usa una dirección https completa, como https://tu-servidor/owntracks",
  "While you share, your position also goes to {host}.": "Mientras compartes, tu ubicación también va a {host}.",
  "Your own server": "Tu propio servidor",
  "A tracker ID goes out as tid with each position, so a forwarder or Home Assistant can tell this phone apart.": "Un ID de rastreador se envía como tid con cada ubicación, para que un reenviador o Home Assistant distinga este teléfono.",
  "Sent with the tracker ID {tid}.": "Se envía con el ID de rastreador {tid}.",
  "Set tracker ID": "Guardar ID de rastreador",
  "That tracker ID did not work.": "Ese ID de rastreador no funcionó.",
  "Tracker ID, like phone1 (optional)": "ID de rastreador, como telefono1 (opcional)",
  "Use up to 64 characters for the tracker ID, on one line.": "Usa hasta 64 caracteres para el ID de rastreador, en una sola línea.",
  "Your position goes out as {tid}.": "Tu ubicación se envía como {tid}.",
  "Your position goes out with no tracker ID.": "Tu ubicación se envía sin ID de rastreador.",
  "Your position no longer goes to your own server.": "Tu ubicación ya no va a tu propio servidor.",
  "Advanced": "Avanzado",
  "This circle uses another relay": "Este círculo usa otro relay",
  "This circle uses the relay at {host}. Asking to join switches Starling to it.": "Este círculo usa el relay de {host}. Al pedir unirte, Starling pasa a usarlo.",
  "This invitation is for a circle on {host}.": "Esta invitación es para un círculo en {host}.",
  "To join it, put {relay} in Settings, Advanced, Relay, restart Starling and open the link again. Your other circles stop updating while it is set.": "Para unirte, pon {relay} en Ajustes, Avanzado, Relay, reinicia Starling y vuelve a abrir el enlace. Tus otros círculos dejan de actualizarse mientras esté puesto.",
  "Your circles use the default relay, and Starling talks to one relay at a time.": "Tus círculos usan el relay predeterminado, y Starling usa un solo relay a la vez.",
  "Your circles use {host}, and Starling talks to one relay at a time.": "Tus círculos usan {host}, y Starling usa un solo relay a la vez.",
  "Use your own relay": "Usar tu propio relay",
  "Cancel your join request first.": "Primero cancela tu solicitud para unirte.",
  "Starling will use {host}.": "Starling usará {host}.",
  "Starling will use the default relay.": "Starling usará el relay predeterminado.",
  "Only if you run a relay yourself. Everyone in your circle has to use the same one, and the invite links you send carry it.": "Solo si tienes tu propio relay. Todos en tu círculo tienen que usar el mismo, y los enlaces de invitación que envíes lo llevan.",
  "This device could not run the lock's key stretching. Nothing was erased; try again, or free some memory.": "Este dispositivo no pudo ejecutar la derivación de clave del bloqueo. No se ha borrado nada; inténtalo de nuevo o libera algo de memoria.",
  "Biometric unlock is on.": "El desbloqueo biométrico está activado.",
  "Status cleared.": "Estado borrado.",
  "Status set.": "Estado guardado.",
  "You left the circle.": "Saliste del círculo.",
  "You left, but this device could not erase everything. Open Starling again to finish clearing it.": "Saliste, pero este dispositivo no pudo borrarlo todo. Vuelve a abrir Starling para terminar de limpiarlo.",
  "Your device or browser could not set up biometric unlock.": "Tu dispositivo o navegador no pudo configurar el desbloqueo biométrico.",
  "Show as QR": "Mostrar como QR",
  "Scan theirs": "Escanear el suyo",
  "Scanning a code lives in the app. Here, compare the digits.": "Escanear un código se hace en la app. Aquí, compara los dígitos.",
  "Your number is not ready yet.": "Tu número todavía no está listo.",
  "Your number as a code": "Tu número como código",
  "Safety number QR code": "Código QR del número de seguridad",
  "Let the person checking you scan this with Starling. It holds your member id and your safety number, nothing else.": "Deja que la persona que te está comprobando lo escanee con Starling. Contiene tu ID de miembro y tu número de seguridad, nada más.",
  "Scan their code": "Escanear su código",
  "Point the camera at the code on their screen.": "Apunta la cámara al código en su pantalla.",
  "Camera access was turned down. Allow it for Starling in system settings, then try again.": "Se denegó el acceso a la cámara. Permítelo para Starling en los ajustes del sistema y vuelve a intentarlo.",
  "No camera found on this device.": "No se encontró ninguna cámara en este dispositivo.",
  "The camera could not start.": "No se pudo iniciar la cámara.",
  "Scan result": "Resultado del escaneo",
  "The code matches the keys this phone holds for {who}. Nobody is in between.": "El código coincide con las claves que este teléfono tiene de {who}. No hay nadie en medio.",
  "{who} is answering with different keys right now. Settle that on their card before marking anything.": "{who} está respondiendo con claves distintas ahora mismo. Resuelve eso en su tarjeta antes de marcar nada.",
  "{who} is already marked verified.": "{who} ya está marcado como verificado.",
  "Mark {who} verified": "Marcar a {who} como verificado",
  "{who} is verified.": "{who} está verificado.",
  "The code does not match the keys this phone holds for {who}. That is a reinstall, or somebody in between, and this phone cannot tell which. Do not mark them verified. Read the digits out to each other, and if they still differ, remove them.": "El código no coincide con las claves que este teléfono tiene de {who}. Puede ser una reinstalación, o puede ser alguien en medio, y este teléfono no puede distinguirlo. No lo marques como verificado. Léanse los dígitos en voz alta, y si siguen sin coincidir, quítalo del círculo.",
  "That code belongs to nobody in this circle.": "Ese código no es de nadie de este círculo.",
  "That is not a Starling safety number code.": "Eso no es un código de número de seguridad de Starling.",
  "Check-in timer": "Temporizador de aviso",
  "Get your circle told if you miss a check-in": "Que tu círculo se entere si no avisas a tiempo",
  "Pick how long you need. If you have not checked in when it runs out, your circle is told, even if this phone is off by then. Only checking in stops it.": "Elige cuánto tiempo necesitas. Si no has avisado cuando se acabe, tu círculo recibe una alerta, aunque para entonces este teléfono esté apagado. Solo avisar lo detiene.",
  "Check in within": "Avisar en un plazo de",
  "Start timer": "Iniciar temporizador",
  "Check in now": "Avisar ahora",
  "Check in by {time}": "Plazo para avisar: {time}",
  "Start sharing too": "Empezar a compartir también",
  "Sharing is off, so your circle gets the timer and the last position this phone sent, not where you are now.": "No estás compartiendo, así que tu círculo recibe el temporizador y la última posición que envió este teléfono, no dónde estás ahora.",
  "Timer set. Check in by {time}.": "Temporizador puesto. Plazo para avisar: {time}.",
  "Timer set, but your circle does not have it yet. Starling keeps trying.": "Temporizador puesto, pero tu círculo todavía no lo tiene. Starling sigue intentándolo.",
  "Check in within 5 minutes, or your circle is told.": "Avisa en los próximos 5 minutos o tu círculo recibirá una alerta.",
  "You missed your check-in": "No avisaste a tiempo",
  "Your circle has been told. Check in now if you are okay.": "Tu círculo ya recibió la alerta. Avisa ahora si estás bien.",
  "{who} missed their check-in": "{who} no avisó a tiempo",
  "Their timer ran out at {time}. Their last position is on the map.": "Su plazo terminó ({time}). Su última posición está en el mapa.",
  "Their last position is on the map.": "Su última posición está en el mapa.",
  "Show on map": "Ver en el mapa",
  "Missed check-in": "Plazo vencido",
  "Your check-in timer is running in {circle}. Check in there before you switch?": "Tu temporizador de aviso está activo en {circle}. ¿Avisas allí antes de cambiar?",
  "Check in and switch": "Avisar y cambiar",
  "Exit the demo to set a check-in timer.": "Sal de la demostración para poner un temporizador de aviso.",
  "Their live position is on the map. It stays here until they check in.": "Su posición en vivo está en el mapa. Esto se queda aquí hasta que avise.",
  "{who}'s phone stopped sending {ago} ago. The last position it sent is on the map.": "El teléfono de {who} dejó de enviar hace {ago}. La última posición que envió está en el mapa.",
  "{who}'s SOS went quiet": "El SOS de {who} se quedó sin señal",
  "Alerts": "Alertas",
  "{name} alerts": "Alertas de {name}",
  "Both": "Ambas",
  "Arrive": "Llegada",
  "Leave": "Salida",
  "Off": "Ninguna",
  "Your battery is at {pct}%": "Tu batería está al {pct}%",
  "Sending every 5 minutes instead of every 15 seconds makes it last longer. An SOS still goes out every 15 seconds.": "Enviar cada 5 minutos en lugar de cada 15 segundos hace que dure más. Un SOS sigue saliendo cada 15 segundos.",
  "Every 5 minutes": "Cada 5 minutos",
  "Accurate to about {dist}": "Precisión de unos {dist}",
  "Phone battery {pct}%": "Batería del teléfono: {pct}%",
  "Link works until {time}": "Enlace válido hasta: {time}",
  "Open in a map app": "Abrir en una app de mapas",
};
