// French catalog: normalized English source -> French.
// First draft by the developer; native-speaker review is welcome and
// rough edges deserve bug reports. Regenerate the key list with:
// node tools/extract-strings.mjs
// Missing entries fall back to English by design.
export const fr = {
  "Scan a code": "Scanner un code",
  "Scan an invite code": "Scanner un code d'invitation",
  "Point the camera at the invite code on their screen.": "Pointez la caméra vers le code d'invitation sur son écran.",
  "That is a safety number code, not an invite.": "C'est un code de numéro de sécurité, pas une invitation.",
  "That is not a Starling invite code.": "Ce n'est pas un code d'invitation Starling.",
  "Remind me if sharing stays off": "Me le rappeler si le partage reste coupé",
  "If you stop sharing and do not turn it back on, this phone shows a notification after that long. Nothing goes to your circle.": "Si vous arrêtez le partage sans le réactiver, ce téléphone affiche une notification une fois ce délai passé. Rien n'est envoyé à votre cercle.",
  "Never": "Jamais",
  "1 h": "1 h",
  "4 h": "4 h",
  "12 h": "12 h",
  "SOS and Do Not Disturb": "SOS et Ne pas déranger",
  "An SOS from your circle rings through Do Not Disturb when alarms are allowed. To let it through total silence too, turn on Override Do Not Disturb for Emergency alerts.": "Un SOS de votre cercle sonne malgré Ne pas déranger quand les alarmes sont autorisées. Pour qu'il passe aussi en silence total, activez « Ignorer le mode Ne pas déranger » pour Alertes d'urgence.",
  "Open emergency alert settings": "Ouvrir les paramètres des alertes d'urgence",
  "Invite QR code": "Code QR d'invitation",
  "{who} is answering with different keys. That is a reinstall, or somebody else in their place, and this phone cannot tell which. Their location stays off your map until you accept.": "{who} répond avec des clés différentes. C'est une réinstallation, ou quelqu'un d'autre à sa place, et ce téléphone ne peut pas faire la différence. Sa position reste hors de votre carte tant que vous n'acceptez pas.",
  "Ask {who} to read out the number on their screen. If it is the new one, accept it. If it is the old one, or they did not reinstall, remove them.": "Demandez à {who} de vous lire le numéro affiché sur son écran. Si c'est le nouveau, acceptez-le. Si c'est l'ancien, ou s'il n'y a pas eu de réinstallation, retirez cette personne du cercle.",
  "Avatar": "Avatar",
  "Cancel": "Annuler",
  "Cancel SOS and check in with your circle": "Annuler le SOS et rassurer votre cercle",
  "End to end encrypted. This page can read this one emergency share and nothing else.": "Chiffré de bout en bout. Cette page peut lire ce seul partage d'urgence et rien d'autre.",
  "Everyone else gets new keys. {who} can read nothing this circle sends from now on, and is not told. What they already saw, they keep.": "Tous les autres reçoivent de nouvelles clés. {who} ne peut plus rien lire de ce que ce cercle envoie à partir de maintenant, et ne reçoit aucun avertissement. Ce que cette personne a déjà vu, elle le garde.",
  "Keys changed": "Clés changées",
  "Map": "Carte",
  "Mark not verified": "Marquer comme non vérifié",
  "no position yet": "pas encore de position",
  "Member details": "Détails du membre",
  "Not reaching the relay": "Relais injoignable",
  "Not verified": "Non vérifié",
  "Place name": "Nom du lieu",
  "Read this out to {who} on a call or in person. The same digits on both screens means nobody is in between.": "Lisez ceci à {who} lors d'un appel ou en personne. Les mêmes chiffres sur les deux écrans signifient que personne ne s'est glissé entre vous.",
  "Recenter": "Recentrer",
  "Revoked": "Révoqué",
  "Safety number loading": "Chargement du numéro de sécurité",
  "Show this safety number large for comparing in person": "Afficher ce numéro de sécurité en grand pour le comparer en personne",
  "Someone shared this emergency link with you. Their live position appears here the moment it arrives. Keep this page open.": "Quelqu'un a partagé ce lien d'urgence avec vous. Sa position en direct apparaît ici dès qu'elle arrive. Gardez cette page ouverte.",
  "The person who shared this link stopped their emergency share or checked in safe. The last known position stays on the map.": "La personne qui a partagé ce lien a arrêté son partage d'urgence ou a fait savoir qu'elle est en sécurité. La dernière position connue reste sur la carte.",
  "This help link is no longer active. The last known position stays on the map; ask for a fresh link if the emergency is still going on.": "Ce lien d'aide n'est plus actif. La dernière position connue reste sur la carte ; demandez un nouveau lien si l'urgence continue.",
  "This link has expired": "Ce lien a expiré",
  "This page needs JavaScript. The person's position arrives encrypted and is decrypted here, in your browser, with a key carried in this link that never reaches any server; without JavaScript there is nothing that can do that decryption. If you are on Tor Browser's Safest setting, allow JavaScript for this page to see them.": "Cette page a besoin de JavaScript. La position de la personne arrive chiffrée et est déchiffrée ici, dans votre navigateur, avec une clé transportée dans ce lien qui n'atteint jamais aucun serveur ; sans JavaScript, rien ne peut faire ce déchiffrement. Si vous utilisez le Navigateur Tor au niveau « Le plus sûr », autorisez JavaScript pour cette page afin de voir la personne.",
  "This session has ended": "Cette session est terminée",
  "Verified": "Vérifié",
  "Waiting for a location...": "En attente d'une position...",
  "Home": "Maison",
  "The fountain": "La fontaine",
  "omw to the fountain": "en route vers la fontaine",
  "made it": "j'y suis",
  "You": "Vous",
  "1 hr": "1 h",
  "1 min": "1 min",
  "5 min": "5 min",
  "A circle holds {n} people and yours is full. Remove somebody before letting anyone else in.": "Un cercle peut accueillir {n} personnes au maximum, et le vôtre est plein. Retirez quelqu'un avant de laisser entrer une autre personne.",
  "A few words your circle sees next to your name. It is encrypted like everything else, and it clears when you stop sharing.": "Quelques mots que votre cercle voit à côté de votre nom. C'est chiffré comme tout le reste, et ça s'efface quand vous arrêtez de partager.",
  "A member": "ce membre",
  "A member's keys changed": "Les clés d'un membre ont changé",
  "A relay must be an https URL, like https://relay.example.org": "Un relais doit être une URL https, comme https://relay.example.org",
  "A second passcode for a moment when someone makes you open Starling. Entering it on the lock screen erases everything on this device, instantly and silently, and shows a fresh install. There is no undo and no way back in. It only guards the passcode path: biometric unlock still opens the app normally, so if a forced unlock is in your threat model, turn biometrics off too.": "Un second code d'accès pour le moment où quelqu'un vous force à ouvrir Starling. Le saisir sur l'écran de verrouillage efface tout sur cet appareil, immédiatement et sans prévenir, puis affiche une installation vierge. Il n'y a ni retour en arrière ni moyen de rentrer. Il ne protège que la saisie du code : le déverrouillage biométrique ouvre toujours l'application normalement, donc si un déverrouillage forcé fait partie de votre modèle de menace, désactivez aussi la biométrie.",
  "A welcome arrived that did not match the person this link came from, and it was refused. That can be an interception attempt, or just a stale retry or a network hiccup. Your request is still waiting for the person who actually invited you; check with them before using the link again.": "Un message de bienvenue est arrivé, mais il ne venait pas de la personne qui vous a envoyé ce lien, et il a été refusé. Cela peut être une tentative d'interception, ou juste une vieille réémission ou un raté du réseau. Votre demande attend toujours la personne qui vous a vraiment envoyé l'invitation ; vérifiez avec elle avant de réutiliser le lien.",
  "A welcome that did not match the link's sender was refused. That can be an interception attempt, or just a stale retry. Check with whoever gave you the link before you use it again.": "Un message de bienvenue qui ne correspondait pas à l'expéditeur du lien a été refusé. Cela peut être une tentative d'interception, ou juste une vieille réémission. Vérifiez avec la personne qui vous a donné le lien avant de le réutiliser.",
  "Accept the new keys": "Accepter les nouvelles clés",
  "Accepting gives the whole circle new keys and lets them see everyone's location from then on. They cannot read anything sent before.": "Accepter donne de nouvelles clés à tout le cercle et permet à cette personne de voir la position de tout le monde à partir de là. Elle ne peut rien lire de ce qui a été envoyé avant.",
  "Add Starling to your home screen": "Ajoutez Starling à votre écran d'accueil",
  "Another link, for one more person": "Un autre lien, pour une personne de plus",
  "Anyone who checks this phone's storage can see that a duress code exists, though not what it is. What they cannot do is tell it apart from your real passcode while typing.": "Quiconque inspecte le stockage de ce téléphone peut voir qu'un code de contrainte existe, mais pas lequel. Ce qu'il ne peut pas faire, c'est le distinguer de votre vrai code d'accès pendant la saisie.",
  "Anyone you send one of these to can watch your live location on any phone or computer, with no app and no account. A link shows this emergency only, never your circle, and never the other links.": "Toute personne à qui vous envoyez un de ces liens peut suivre votre position en direct sur n'importe quel téléphone ou ordinateur, sans application ni compte. Un lien montre cette urgence seulement, jamais votre cercle, et jamais les autres liens.",
  "App lock is off.": "Le verrouillage de l'application est désactivé.",
  "App lock is on.": "Le verrouillage de l'application est activé.",
  "Arrive and leave alerts": "Alertes d'arrivée et de départ",
  "Ask to join": "Demander à rejoindre",
  "At {place}": "À {place}",
  "Auto": "Auto",
  "Auto-lock": "Verrouillage automatique",
  "Avatar {em}": "Avatar {em}",
  "Basemap": "Fond de carte",
  "Battery {pct} percent": "Batterie à {pct} pour cent",
  "Biometric unlock did not work. Use your passcode.": "Le déverrouillage biométrique n'a pas fonctionné. Utilisez votre code d'accès.",
  "Biometric unlock is off.": "Le déverrouillage biométrique est désactivé.",
  "Cancel the request": "Annuler la demande",
  "Cancel this link": "Annuler ce lien",
  "Center the map on me": "Centrer la carte sur moi",
  "Change passcode": "Changer le code d'accès",
  "Check": "Vérifier",
  "Check again": "Revérifier",
  "Check in with your circle": "Rassurer votre cercle",
  "Check the numbers": "Vérifier les numéros",
  "Check their safety number with them first. Accepting is what lets them see everyone's location.": "Vérifiez d'abord son numéro de sécurité avec cette personne. C'est l'acceptation qui lui permet de voir la position de tout le monde.",
  "Check {who}'s number": "Vérifier le numéro de {who}",
  "Checked in": "Tout va bien",
  "Choose a passcode to lock Starling on this device. There is no reset: if you forget it, you have to erase this device and rejoin from an invite.": "Choisissez un code d'accès pour verrouiller Starling sur cet appareil. Il n'y a pas de réinitialisation : si vous l'oubliez, vous devrez effacer cet appareil et rejoindre le cercle avec une nouvelle invitation.",
  "Circle name": "Nom du cercle",
  "Clear status": "Effacer le statut",
  "Close": "Fermer",
  "Close member card": "Fermer la fiche du membre",
  "Compare in person": "Comparer en personne",
  "Connected": "Connecté",
  "Continue": "Continuer",
  "Coordinates copied": "Coordonnées copiées",
  "Copy": "Copier",
  "Copy coordinates": "Copier les coordonnées",
  "Copy failed": "Copie impossible",
  "Copy failed. Long-press the link instead.": "Copie impossible. Faites plutôt un appui long sur le lien.",
  "Copy link": "Copier le lien",
  "Could not cancel the link. Try again.": "Impossible d'annuler le lien. Réessayez.",
  "Could not change the Orbot setting.": "Impossible de changer le réglage Orbot.",
  "Could not join. Try again.": "Impossible de rejoindre le cercle. Réessayez.",
  "Could not leave. Try again.": "Impossible de quitter le cercle. Réessayez.",
  "Could not let them in. Try again.": "Impossible de laisser entrer cette personne. Réessayez.",
  "Could not make an invite link. Try again.": "Impossible de créer un lien d'invitation. Réessayez.",
  "Could not make another link.": "Impossible de créer un autre lien.",
  "Could not make new keys right now. Try again in a moment.": "Impossible de générer de nouvelles clés pour l'instant. Réessayez dans un moment.",
  "Could not make new keys. Try again.": "Impossible de générer de nouvelles clés. Réessayez.",
  "Could not reach anyone with the new keys. Nothing changed.": "Impossible de joindre qui que ce soit avec les nouvelles clés. Rien n'a changé.",
  "Could not reach the relay to check the time.": "Impossible de joindre le relais pour vérifier l'heure.",
  "Could not reach them to send the keys, so nobody was let in. Try again in a moment.": "Impossible de joindre cette personne pour lui envoyer les clés, donc personne n'a été admis. Réessayez dans un moment.",
  "Could not remove them. Nothing changed.": "Impossible de retirer cette personne. Rien n'a changé.",
  "Could not save. Try again.": "Impossible d'enregistrer. Réessayez.",
  "Could not send them the keys, so nobody was let in. Your link still works, so try again.": "Impossible d'envoyer les clés à cette personne, donc personne n'a été admis. Votre lien fonctionne toujours, alors réessayez.",
  "Could not send {who} the keys, and could not undo letting them in. Remove them from the circle before you try again.": "Impossible d'envoyer les clés à {who}, et impossible d'annuler son admission. Retirez cette personne du cercle avant de réessayer.",
  "Could not switch. Try again.": "Impossible de changer de cercle. Réessayez.",
  "Create a circle": "Créer un cercle",
  "Create circle": "Créer le cercle",
  "Current": "Actuel",
  "Dark": "Sombre",
  "Demo circle": "Cercle de démo",
  "Demo flight - nothing is real": "Vol de démonstration : rien n'est réel",
  "Directions": "Itinéraire",
  "Done": "Terminé",
  "Duress passcode removed.": "Code de contrainte supprimé.",
  "Duress passcode saved.": "Code de contrainte enregistré.",
  "Encrypts your circle secret on this device. Nobody can open Starling, or read the secret from storage, without your passcode.": "Chiffre le secret de votre cercle sur cet appareil. Personne ne peut ouvrir Starling, ni lire le secret dans le stockage, sans votre code d'accès.",
  "End-to-end encrypted. No accounts. Open protocol.": "Chiffré de bout en bout. Sans compte. Protocole ouvert.",
  "End-to-end encrypted. The relay sees ciphertext only.": "Chiffré de bout en bout. Le relais ne voit que du texte chiffré.",
  "English is the app's source language. Translations come from the community; rough edges are worth reporting.": "L'anglais est la langue d'origine de l'application. Les traductions viennent de la communauté ; les maladresses méritent d'être signalées.",
  "Enter your passcode to open your circle.": "Saisissez votre code d'accès pour ouvrir votre cercle.",
  "Enter your passcode to stop encrypting the circle secret at rest.": "Saisissez votre code d'accès pour ne plus chiffrer le secret du cercle stocké sur cet appareil.",
  "Erase and start over": "Effacer et recommencer",
  "Erases the circle secret, your identity, and all Starling data from this device, then reloads. One residual: street-map tiles your browser cached may remain in its own cache. The Off-grid basemap never loads any. There is no undo. Hold the button to confirm.": "Efface le secret du cercle, votre identité et toutes les données de Starling de cet appareil, puis recharge. Un reste possible : les tuiles de carte que votre navigateur a mises en cache peuvent subsister dans son propre cache. Le fond de carte Hors réseau n'en charge jamais. Il n'y a pas de retour en arrière. Maintenez le bouton pour confirmer.",
  "Every link stops updating and shows that the session ended. A new SOS makes new links.": "Chaque lien cesse de se mettre à jour et indique que la session est terminée. Un nouveau SOS crée de nouveaux liens.",
  "Everyone here is checked": "Tout le monde ici est vérifié",
  "Everyone in the circle gets a fresh key and the old one stops working, so anybody holding a copy of the old one goes dark. Do this if a phone in the circle was taken, unlocked, or handed over. Nobody is removed and nothing on your map disappears.": "Tout le monde dans le cercle reçoit une nouvelle clé et l'ancienne cesse de fonctionner, donc quiconque détient une copie de l'ancienne est coupé. Faites-le si un téléphone du cercle a été pris, déverrouillé ou remis à quelqu'un. Personne n'est retiré et rien ne disparaît de votre carte.",
  "Everyone in this circle, their safety numbers, and who you have checked.": "Tous les membres de ce cercle, leurs numéros de sécurité, et les personnes que vous avez vérifiées.",
  "Exit": "Quitter",
  "Exit the demo first.": "Quittez d'abord la démo.",
  "Exit the demo to edit your places.": "Quittez la démo pour modifier vos lieux.",
  "Exit the demo to invite your people.": "Quittez la démo pour inviter vos proches.",
  "Exit the demo to see your circle's keys.": "Quittez la démo pour voir les clés de votre cercle.",
  "Exit the demo to set a status.": "Quittez la démo pour définir un statut.",
  "Expand or collapse the circle sheet": "Déplier ou replier le panneau du cercle",
  "Expires in {left}": "Expire dans {left}",
  "Forgot passcode": "Code d'accès oublié",
  "Get help from outside your circle": "Obtenir de l'aide hors de votre cercle",
  "Get outside help": "Aide extérieure",
  "Get told when your people arrive": "Recevez une alerte quand vos proches arrivent",
  "Give the place a name first.": "Donnez d'abord un nom au lieu.",
  "Got it": "Compris",
  "Help link": "Lien d'aide",
  "Help links switched off": "Liens d'aide désactivés",
  "Hold on, still finishing the last circle change.": "Patientez, le dernier changement du cercle se termine.",
  "Hold the phones side by side. Every group has to match.": "Tenez les téléphones côte à côte. Chaque groupe doit correspondre.",
  "Hold to erase everything": "Maintenez pour tout effacer",
  "Hold to erase this device": "Maintenez pour effacer cet appareil",
  "Hold to send SOS": "Maintenez pour envoyer un SOS",
  "Holds the screen on while the map is open": "Garde l'écran allumé tant que la carte est ouverte",
  "How far back you can see": "Jusqu'où vous pouvez remonter",
  "How you appear to the people you invite. This never leaves your circle.": "Comment vous apparaissez aux personnes que vous invitez. Cela ne quitte jamais votre cercle.",
  "I have an invite": "J'ai une invitation",
  "Invite link": "Lien d'invitation",
  "Invite link cleared from your clipboard.": "Lien d'invitation effacé du presse-papiers.",
  "Invite people": "Inviter des proches",
  "Invite someone": "Inviter quelqu'un",
  "Invite your people": "Inviter vos proches",
  "It is about {n} minutes {dir}.": "L'horloge a environ {n} minutes {dir}.",
  "Its keys are out of memory and nothing you send arrives any more, but this device could not delete them from its own storage, most likely because there is no room left. They are still on the disk. Free some space and open Starling again to finish clearing it, or use Panic to erase everything now.": "Ses clés ne sont plus en mémoire et rien de ce que vous envoyez n'arrive plus, mais cet appareil n'a pas pu les supprimer de son propre stockage, sans doute parce qu'il n'y a plus de place. Elles sont encore sur le disque. Libérez de l'espace et rouvrez Starling pour finir le nettoyage, ou utilisez l'effacement panique pour tout effacer maintenant.",
  "Join a circle": "Rejoindre un cercle",
  "Join with a link": "Rejoindre avec un lien",
  "Join with invite": "Rejoindre avec une invitation",
  "Just you here so far": "Il n'y a que vous ici pour l'instant",
  "Keep screen awake": "Garder l'écran allumé",
  "Keep this screen on": "Garder cet écran allumé",
  "Keys changed. Check before you trust it.": "Les clés ont changé. Vérifiez avant de faire confiance.",
  "Keys older than this window are destroyed on this device and cannot be brought back, by you or by anyone holding the phone.": "Les clés plus anciennes que cette fenêtre sont détruites sur cet appareil et ne peuvent pas être récupérées, ni par vous ni par quiconque tient le téléphone.",
  "Language": "Langue",
  "Language saved. Reopen settings to see them translated too.": "Langue enregistrée. Rouvrez les paramètres pour les voir traduits aussi.",
  "Last seen": "Dernier signal",
  "Last update {ago}": "Dernière mise à jour : {ago}",
  "Leave circle": "Quitter le cercle",
  "Leave this circle": "Quitter ce cercle",
  "Light": "Clair",
  "Link cancelled. It cannot be used now.": "Lien annulé. Il ne peut plus être utilisé.",
  "Live": "En direct",
  "Live · Neighborhood": "En direct · Quartier",
  "Live · Precise": "En direct · Précise",
  "Locating...": "Localisation...",
  "Load map": "Charger la carte",
  "Location is blocked": "La localisation est bloquée",
  "Location is not available in this browser.": "La localisation n'est pas disponible dans ce navigateur.",
  "Location needs HTTPS. Open the deployed app or localhost.": "La localisation nécessite HTTPS. Ouvrez l'application déployée ou localhost.",
  "Location permission is off for Starling. Open the app's settings, allow location, then come back and tap Start sharing.": "L'autorisation de localisation est désactivée pour Starling. Ouvrez les paramètres de l'application, autorisez la localisation, puis revenez et appuyez sur Commencer à partager.",
  "Location stopped: {reason}": "Localisation arrêtée : {reason}",
  "Locked": "Verrouillé",
  "Low battery alerts": "Alertes de batterie faible",
  "Make another link": "Créer un autre lien",
  "Make new keys": "Générer de nouvelles clés",
  "Mark verified": "Marquer comme vérifié",
  "Member": "Membre",
  "Name the spots that matter and hear about arrivals. Places never leave this phone.": "Nommez les endroits qui comptent et sachez qui arrive. Les lieux ne quittent jamais ce téléphone.",
  "Name the spots that matter, like Home or School, and Starling tells you when someone in your circle arrives or leaves. Places are stored only on this phone. They are never sent anywhere, and the relay cannot learn they exist.": "Nommez les endroits qui comptent, comme Maison ou École, et Starling vous dit quand quelqu'un de votre cercle arrive ou repart. Les lieux sont stockés seulement sur ce téléphone. Ils ne sont jamais envoyés nulle part, et le relais ne peut pas savoir qu'ils existent.",
  "Neighborhood": "Quartier",
  "Neighborhood rounds your position to about 1 km on your device before it is encrypted": "Quartier arrondit votre position à environ 1 km sur votre appareil avant le chiffrement",
  "New circle": "Nouveau cercle",
  "New keys now": "Nouvelles clés maintenant",
  "New keys were made while this device could not be reached, and they cannot be worked out from the old ones. Nothing you send now arrives. Ask somebody in the circle for a fresh invite link.": "De nouvelles clés ont été générées pendant que cet appareil était injoignable, et elles ne peuvent pas être déduites des anciennes. Rien de ce que vous envoyez maintenant n'arrive. Demandez à quelqu'un du cercle un nouveau lien d'invitation.",
  "New link ready to send.": "Nouveau lien prêt à envoyer.",
  "No location fix yet. Still trying...": "Pas encore de position. Toujours en recherche...",
  "No location yet. Start sharing to place yourself.": "Pas encore de position. Commencez à partager pour vous placer.",
  "No position yet. Start sharing first, or pick the spot on the map.": "Pas encore de position. Commencez d'abord à partager, ou choisissez l'endroit sur la carte.",
  "No update from anyone in over {n} minutes. Usually that just means phones are asleep. But if others say they are sharing right now, this phone may have missed the circle's new keys; ask any member for a fresh invite to be sure.": "Aucune mise à jour de personne depuis plus de {n} minutes. D'habitude, cela veut juste dire que les téléphones sont en veille. Mais si les autres disent qu'ils partagent en ce moment, ce téléphone a peut-être raté les nouvelles clés du cercle ; demandez à n'importe quel membre une nouvelle invitation pour en avoir le cœur net.",
  "Nobody else in this circle yet": "Personne d'autre dans ce cercle pour l'instant",
  "Nobody else is in this circle yet. Invite someone from the map.": "Il n'y a encore personne d'autre dans ce cercle. Invitez quelqu'un depuis la carte.",
  "Nobody has been heard from in a while": "Personne n'a donné signe de vie depuis un moment",
  "Nobody has told you the circle's real name yet (names travel encrypted, like everything else), so pick whatever you will recognize. Rename it any time in settings.": "Personne ne vous a encore dit le vrai nom du cercle (les noms voyagent chiffrés, comme tout le reste), alors choisissez un nom que vous reconnaîtrez. Vous pourrez le renommer quand vous voulez dans les paramètres.",
  "Not connected": "Non connecté",
  "Not now": "Pas maintenant",
  "Not sharing": "Pas de partage",
  "Not visible: this phone's clock is wrong": "Invisible : l'horloge de ce téléphone est fausse",
  "Now": "Maintenant",
  "Numbers match, let them in": "Les numéros correspondent, laisser entrer",
  "Off-grid": "Hors réseau",
  "One of your circles expired while this phone was away": "Un de vos cercles a expiré pendant que ce téléphone était hors ligne",
  "One use only, and it expires in {left}. Accepting somebody uses it up.": "Un seul usage, et il expire dans {left}. Accepter quelqu'un le consomme.",
  "Open Starling to check their number and let them in.": "Ouvrez Starling pour vérifier son numéro et laisser entrer cette personne.",
  "Open Starling to see their live position.": "Ouvrez Starling pour voir sa position en direct.",
  "Open app settings": "Ouvrir les paramètres de l'application",
  "Open members": "Ouvrir les membres",
  "Or your own words": "Ou vos propres mots",
  "Panic wipe": "Effacement panique",
  "Passcode": "Code d'accès",
  "Passcode changed.": "Code d'accès modifié.",
  "Paste the invite link someone sent you. The circle secret stays in the link fragment and never touches a server.": "Collez le lien d'invitation qu'on vous a envoyé. Le secret du cercle reste dans le fragment du lien et n'atteint jamais aucun serveur.",
  "People and keys": "Membres et clés",
  "Pick an avatar": "Choisir un avatar",
  "Pick on the map": "Choisir sur la carte",
  "Places": "Lieux",
  "Point Starling at your own relay if you run one. The relay source ships with the app, so anyone can host it. Leave this empty for the default. A change applies the next time Starling starts.": "Pointez Starling vers votre propre relais si vous en gérez un. Le code du relais est livré avec l'application, donc n'importe qui peut l'héberger. Laissez vide pour le relais par défaut. Un changement s'applique au prochain démarrage de Starling.",
  "Precise": "Précise",
  "Precision": "Précision",
  "Probably just quiet": "Ce n'est sans doute rien",
  "Real map": "Vraie carte",
  "Reconnecting": "Reconnexion",
  "Reconnecting...": "Reconnexion...",
  "Reject": "Refuser",
  "Relay": "Relais",
  "Relay saved. It applies the next time Starling starts.": "Relais enregistré. Il s'applique au prochain démarrage de Starling.",
  "Relock after the app has been in the background this long. Locking ends a share unless Keep sharing when the app is closed is on.": "Reverrouille après ce temps passé en arrière-plan. Le verrouillage met fin au partage, sauf si « Continuer le partage quand l'application est fermée » est activé.",
  "Remove": "Retirer",
  "Remove duress passcode": "Supprimer le code de contrainte",
  "Remove them": "Retirer cette personne",
  "Remove {name}": "Retirer {name}",
  "Request sent. Someone in the circle has to accept it from their phone.": "Demande envoyée. Quelqu'un du cercle doit l'accepter depuis son téléphone.",
  "Require passcode": "Exiger le code d'accès",
  "Review the request": "Voir la demande",
  "Revoke": "Révoquer",
  "Route through Orbot": "Passer par Orbot",
  "SOS": "SOS",
  "SOS active": "SOS actif",
  "SOS armed · Locating...": "SOS armé · Localisation...",
  "SOS armed · Sharing live": "SOS armé · Partage en direct",
  "SOS from {who}": "SOS de {who}",
  "SOS is armed": "Le SOS est armé",
  "SOS sent to your circle. Tap the check mark to cancel.": "SOS envoyé à votre cercle. Appuyez sur la coche pour l'annuler.",
  "Safety number {digits}": "Numéro de sécurité {digits}",
  "Save duress passcode": "Enregistrer le code de contrainte",
  "Save my current spot": "Enregistrer ma position actuelle",
  "Saved. Your circle sees it once you start sharing.": "Enregistré. Votre cercle le voit dès que vous commencez à partager.",
  "See who is here": "Voir qui est là",
  "Send": "Envoyer",
  "Send it through something you already trust, like Signal. Whoever opens it can ask to join; they are not in until you check their number and accept.": "Envoyez-le par un canal auquel vous faites déjà confiance, comme Signal. Quiconque l'ouvre peut demander à rejoindre le cercle ; la personne n'entre pas tant que vous n'avez pas vérifié son numéro et accepté.",
  "Send on the timer even when you have not moved. The relay cannot read a position either way, but a burst of updates while you walk and silence while you sit is a movement trail made of timing alone. This hides that, and costs a little battery.": "Envoie à intervalle régulier même si vous n'avez pas bougé. Le relais ne peut de toute façon pas lire une position, mais une rafale de mises à jour quand vous marchez et le silence quand vous restez sur place forment une trace de vos déplacements faite du rythme seul. Ceci la masque, et coûte un peu de batterie.",
  "Send the link": "Envoyer le lien",
  "Sends relay and map traffic through Orbot's Tor proxy on this device. Needs Orbot installed with Power User Mode on. Orbot's per-app VPN mode also covers Starling with this off.": "Envoie le trafic du relais et de la carte par le proxy Tor d'Orbot sur cet appareil. Nécessite Orbot installé avec le mode « Power User » activé. Le mode VPN par application d'Orbot couvre aussi Starling quand ceci est désactivé.",
  "Sent it to the wrong person?": "Envoyé à la mauvaise personne ?",
  "Session ended": "Session terminée",
  "Set a passcode": "Définir un code d'accès",
  "Set a status for your circle": "Définir un statut pour votre cercle",
  "Set status": "Définir un statut",
  "Settings": "Paramètres",
  "Show the demo on a real map? Tiles of its Central Park stage load from openstreetmap.org - the demo's only network use.": "Afficher la démo sur une vraie carte ? Les tuiles de sa scène de Central Park se chargent depuis openstreetmap.org, le seul accès réseau de la démo.",
  "Sharing (pretend)": "Partage (simulé)",
  "Sharing live": "Partage en direct",
  "Sharing{run}, and this screen has to stay on": "Partage{run}, et cet écran doit rester allumé",
  "Show recent paths on the map": "Afficher les trajets récents sur la carte",
  "Signal lost": "Signal perdu",
  "Somebody already in that circle has to accept your request. Read them your number: {digits}{jumped}": "Quelqu'un déjà dans ce cercle doit accepter votre demande. Lisez-lui votre numéro : {digits}{jumped}",
  "Somebody else is jamming that invite link, so it cannot be used any more. Nobody was let in. Make a new link and send it again.": "Quelqu'un d'autre brouille ce lien d'invitation, il ne peut donc plus servir. Personne n'a été admis. Créez un nouveau lien et renvoyez-le.",
  "Someone": "Quelqu'un",
  "Someone wants to join": "Quelqu'un veut rejoindre le cercle",
  "Starling cannot recover a forgotten passcode. Nothing about your circle leaves your device unencrypted, so there is no reset link. You can erase this device and rejoin your circle from a fresh invite. Hold the button to erase everything on this device.": "Starling ne peut pas récupérer un code d'accès oublié. Rien de votre cercle ne quitte votre appareil en clair, donc il n'y a pas de lien de réinitialisation. Vous pouvez effacer cet appareil et rejoindre votre cercle avec une nouvelle invitation. Maintenez le bouton pour tout effacer sur cet appareil.",
  "Starling hit a problem while starting.": "Starling a rencontré un problème au démarrage.",
  "Starling only gets good when your people are on the map. Send them your invite link.": "Starling ne devient vraiment utile que quand vos proches sont sur la carte. Envoyez-leur votre lien d'invitation.",
  "Starling throws a circle's keys away rather than carry them for weeks, and that circle passed the point where this device could still read it, so it was erased from this phone. {kept} Ask somebody in that circle for a fresh invite link if you want back in.": "Starling jette les clés d'un cercle plutôt que de les garder pendant des semaines, et ce cercle a dépassé le point où cet appareil pouvait encore le lire, donc il a été effacé de ce téléphone. {kept} Demandez à quelqu'un de ce cercle un nouveau lien d'invitation si vous voulez y revenir.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this device passed that point while it was away. Its keys are gone from memory and from storage, and so is this phone's own identity in that circle, so nothing you send arrives and nothing sent to you can be read. Ask somebody in the circle for a fresh invite link.": "Starling jette les clés d'un cercle plutôt que de les garder pendant des semaines, et cet appareil a dépassé ce point pendant son absence. Ses clés ont disparu de la mémoire et du stockage, tout comme l'identité de ce téléphone dans ce cercle, donc rien de ce que vous envoyez n'arrive et rien de ce qu'on vous envoie ne peut être lu. Demandez à quelqu'un du cercle un nouveau lien d'invitation.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this phone passed that point while it was away. The circle was erased from this device, and there was no other circle to fall back to.{lockLine} Ask somebody for a fresh invite link, or start a new circle.": "Starling jette les clés d'un cercle plutôt que de les garder pendant des semaines, et ce téléphone a dépassé ce point pendant son absence. Le cercle a été effacé de cet appareil, et il n'y avait pas d'autre cercle vers lequel se replier.{lockLine} Demandez un nouveau lien d'invitation à quelqu'un, ou créez un nouveau cercle.",
  "Starling trusts whoever first answers with keys that match their member id. Reading these numbers out to each other is what turns that into knowing who is on your map.": "Starling fait confiance à la première personne qui répond avec des clés correspondant à son identifiant de membre. Se lire ces numéros à voix haute, c'est ce qui transforme cette confiance en certitude sur qui est sur votre carte.",
  "Start a new circle": "Créer un nouveau cercle",
  "Start fresh": "Repartir de zéro",
  "Start sharing": "Commencer à partager",
  "Steady sending": "Envoi régulier",
  "Steady sending is on too, so the relay cannot read your movement from the timing.": "L'envoi régulier est aussi activé, donc le relais ne peut pas lire vos déplacements d'après le rythme.",
  "Still about {n} minutes out.": "L'horloge est toujours décalée d'environ {n} minutes.",
  "Stop sharing with helpers": "Arrêter le partage hors du cercle",
  "Stopped": "Arrêté",
  "Street maps load tiles from OpenStreetMap, which sees your map viewport. Off-grid loads nothing.": "La vraie carte charge ses tuiles depuis OpenStreetMap, qui voit la zone affichée de votre carte. Hors réseau ne charge rien.",
  "Switch circle": "Changer de cercle",
  "Switched to {name}.": "Cercle actuel : {name}.",
  "Tap the map where {name} is.": "Appuyez sur la carte là où se trouve {name}.",
  "Tell me when a member's phone drops under 15 percent, before their dot goes dark": "Me prévenir quand le téléphone d'un membre passe sous 15 pour cent, avant que son point ne s'éteigne",
  "Tell me when someone in the circle reaches a place or leaves one": "Me prévenir quand quelqu'un du cercle arrive à un lieu ou le quitte",
  "That circle expired, and this device could not erase all of it. Open Starling again to finish clearing it.": "Ce cercle a expiré, et cet appareil n'a pas pu tout effacer. Rouvrez Starling pour finir le nettoyage.",
  "That circle expired, and this phone could not erase it": "Ce cercle a expiré, et ce téléphone n'a pas pu l'effacer",
  "That does not look like a Starling invite link.": "Cela ne ressemble pas à un lien d'invitation Starling.",
  "That invitation arrived incomplete": "Cette invitation est arrivée incomplète",
  "That invitation expired. Make a new link.": "Cette invitation a expiré. Créez un nouveau lien.",
  "That is the lot: {n} places is the cap.": "C'est tout : la limite est de {n} lieux.",
  "That is your duress passcode. Pick a different one.": "C'est votre code de contrainte. Choisissez-en un autre.",
  "That is your own invite link.": "C'est votre propre lien d'invitation.",
  "That is your unlock passcode. A duress code has to be different.": "C'est votre code d'accès normal. Le code de contrainte doit être différent.",
  "That link is dead. The others still work.": "Ce lien est mort. Les autres fonctionnent toujours.",
  "That passcode is right, but this install's stored data will not open. Nothing was erased.": "Ce code d'accès est bon, mais les données enregistrées de cette installation ne s'ouvrent pas. Rien n'a été effacé.",
  "That phone is answering with keys this device has never seen. It is a reinstall, or somebody else in {who}'s place, and nothing here can tell you which. Their location stays off your map until you check the number with them and accept it.": "Ce téléphone répond avec des clés que cet appareil n'a jamais vues. C'est une réinstallation, ou quelqu'un d'autre à la place de {who}, et rien ici ne peut faire la différence. Sa position reste hors de votre carte tant que vous n'avez pas vérifié le numéro avec cette personne et accepté.",
  "That request's keys are malformed. Nobody was let in.": "Les clés de cette demande sont mal formées. Personne n'a été admis.",
  "The SOS is cleared.": "Le SOS est levé.",
  "The clock looks right now. Your circle can see you again.": "L'horloge semble juste maintenant. Votre cercle peut de nouveau vous voir.",
  "The demo has its own Real map button. Your choice here applies when you exit.": "La démo a son propre bouton Vraie carte. Votre choix ici s'applique quand vous la quittez.",
  "The label is for you. It is never sent anywhere.": "Ce nom est pour vous seulement. Il n'est jamais envoyé nulle part.",
  "The link stops working immediately, and any request already waiting on it is dropped. Open Invite again for a fresh one.": "Le lien cesse de fonctionner immédiatement, et toute demande déjà en attente dessus est abandonnée. Rouvrez « Inviter des proches » pour en obtenir un nouveau.",
  "The relay that passes your updates along stores only encrypted data it cannot read, and deletes it after 24 hours. The protocol is open, so anyone can check these claims against the code.": "Le relais qui transmet vos mises à jour ne stocke que des données chiffrées qu'il ne peut pas lire, et les supprime après 24 heures. Le protocole est ouvert, donc n'importe qui peut vérifier ces affirmations dans le code.",
  "Their dot may go dark soon.": "Son point risque de s'éteindre bientôt.",
  "Their number is {theirs}. Yours is {mine}. Read them to each other out loud, on a line you already trust. Nothing else in this circle has been checked by a person yet.": "Son numéro est {theirs}. Le vôtre est {mine}. Lisez-les l'un à l'autre à voix haute, sur une ligne à laquelle vous faites déjà confiance. Rien d'autre dans ce cercle n'a encore été vérifié par une personne.",
  "Theme": "Thème",
  "They": "Cette personne",
  "This browser is blocking storage. Starling runs, but nothing is saved after you close it.": "Ce navigateur bloque le stockage. Starling fonctionne, mais rien n'est enregistré après sa fermeture.",
  "This is taking a while. The person who invited you may not have seen the request yet, or the link may have expired. Reach them however you normally would; a fresh link takes a minute to make.": "Cela prend du temps. La personne qui vous a envoyé l'invitation n'a peut-être pas encore vu la demande, ou le lien a peut-être expiré. Contactez-la comme vous le feriez d'habitude ; un nouveau lien se crée en une minute.",
  "This is the number your circle should hear from you.": "C'est le numéro que votre cercle doit entendre de vous.",
  "This phone has been offline too long": "Ce téléphone est resté hors ligne trop longtemps",
  "This phone's clock is wrong": "L'horloge de ce téléphone est fausse",
  "This phone's clock is wrong, so your circle cannot see you.{off} Turn on automatic date and time.": "L'horloge de ce téléphone est fausse, donc votre cercle ne peut pas vous voir.{off} Activez la date et l'heure automatiques.",
  "This sends a request. Somebody already in the circle has to check your safety number and accept it before you can see anyone, or they you. That check is how they know the request really came from you and not from somebody who got hold of the link.": "Ceci envoie une demande. Quelqu'un déjà dans le cercle doit vérifier votre numéro de sécurité et l'accepter avant que vous puissiez voir qui que ce soit, ou qu'on vous voie. Cette vérification est ce qui lui permet de savoir que la demande vient vraiment de vous et non de quelqu'un qui a mis la main sur le lien.",
  "Those keys are gone": "Ces clés n'existent plus",
  "Those new keys are malformed. They were not accepted.": "Ces nouvelles clés sont mal formées. Elles n'ont pas été acceptées.",
  "Trail": "Trajet",
  "Trail history": "Historique des trajets",
  "Try again": "Réessayer",
  "Turn off app lock": "Désactiver le verrouillage de l'application",
  "Turn on app lock": "Activer le verrouillage de l'application",
  "Turned down. Your link still works for whoever it was meant for.": "Refusée. Votre lien fonctionne toujours pour la personne à qui il était destiné.",
  "Unlock": "Déverrouiller",
  "Unlock with biometrics": "Déverrouiller avec la biométrie",
  "Unlocking...": "Déverrouillage...",
  "Update Starling": "Mettre à jour Starling",
  "Use at least {n} characters.": "Utilisez au moins {n} caractères.",
  "Use this device's Face ID, fingerprint, or Windows Hello to unlock. Your passcode still works as backup.": "Utilisez Face ID, l'empreinte digitale ou Windows Hello de cet appareil pour déverrouiller. Votre code d'accès fonctionne toujours en secours.",
  "Waiting to be let into {name}": "En attente d'admission dans {name}",
  "Was": "Avant",
  "Watch the demo": "Voir la démo",
  "What Starling is and how it works &#8599;": "Ce qu'est Starling et comment ça marche &#8599;",
  "When you are safe": "Quand vous êtes en sécurité",
  "Wrong passcode. Try again.": "Code d'accès incorrect. Réessayez.",
  "You already asked to join. They still have to let you in.": "Vous avez déjà demandé à rejoindre le cercle. On doit encore vous laisser entrer.",
  "You have an invite to a circle. Set up how you will appear to the people in it.": "Vous avez une invitation pour un cercle. Choisissez comment vous apparaîtrez aux personnes qui en font partie.",
  "You have checked this number with {who}.": "Vous avez vérifié ce numéro avec {who}.",
  "You joined the circle.": "Vous avez rejoint le cercle.",
  "You left. Now in {name}.": "Vous avez quitté le cercle. Vous êtes maintenant dans {name}.",
  "You're in": "Vous êtes dans le cercle",
  "Your app lock and your other circles were not touched.": "Votre verrouillage de l'application et vos autres cercles n'ont pas été touchés.",
  "Your app lock is untouched and still protects whatever you set up next.": "Votre verrouillage de l'application est intact et protège toujours ce que vous configurerez ensuite.",
  "Your browser is blocking location for this site. Allow location in your browser's site settings, then tap Start sharing again.": "Votre navigateur bloque la localisation pour ce site. Autorisez la localisation dans les paramètres du site de votre navigateur, puis appuyez de nouveau sur Commencer à partager.",
  "Your circle cannot see you. The relay refuses anything stamped with a time that far out, so your position is not going anywhere.{off} Turn on automatic date and time, then check again.": "Votre cercle ne peut pas vous voir. Le relais refuse tout ce qui porte une heure aussi décalée, donc votre position ne part nulle part.{off} Activez la date et l'heure automatiques, puis revérifiez.",
  "Your circle has new keys, but they could not be saved. If Starling restarts you will need a fresh invitation.": "Votre cercle a de nouvelles clés, mais elles n'ont pas pu être enregistrées. Si Starling redémarre, il vous faudra une nouvelle invitation.",
  "Your circle has new keys.": "Votre cercle a de nouvelles clés.",
  "Your circle moved on without this phone": "Votre cercle a continué sans ce téléphone",
  "Your circle sees an alert at your live position. Tap the check mark above to cancel it and let everyone know you are okay.": "Votre cercle voit une alerte à votre position en direct. Appuyez sur la coche ci-dessus pour l'annuler et dire à tout le monde que vous allez bien.",
  "Your circles": "Vos cercles",
  "Your current circle stays. This adds a new one, and you can switch between them from the circle name at the top of the map.": "Votre cercle actuel reste. Ceci en ajoute un nouveau, et vous pouvez passer de l'un à l'autre depuis le nom du cercle en haut de la carte.",
  "Your list of members does not match": "Votre liste de membres ne correspond pas",
  "Your name": "Votre nom",
  "Your number": "Votre numéro",
  "Your other circles": "Vos autres cercles",
  "Your other circles could not be read and were dropped.": "Vos autres cercles n'ont pas pu être lus et ont été abandonnés.",
  "Your other circles were not touched.": "Vos autres cercles n'ont pas été touchés.",
  "Your people, on your map. Nobody else.": "Vos proches, sur votre carte. Personne d'autre.",
  "Your positions are encrypted on this device with a key only your circle holds. There are no accounts, no phone numbers, and no server that can read where you are. Sharing is off until you turn it on, and stopping is one tap.": "Vos positions sont chiffrées sur cet appareil avec une clé que seul votre cercle détient. Pas de compte, pas de numéro de téléphone, et aucun serveur capable de lire où vous êtes. Le partage est désactivé tant que vous ne l'activez pas, et l'arrêter ne prend qu'un geste.",
  "Your request is waiting on the relay. Somebody already in the circle has to check your number and accept it, and they do not have to be online right now.": "Votre demande attend sur le relais. Quelqu'un déjà dans le cercle doit vérifier votre numéro et l'accepter, et cette personne n'a pas besoin d'être en ligne en ce moment.",
  "Your request was accepted. Your circle is on the map.": "Votre demande a été acceptée. Votre cercle est sur la carte.",
  "Your status": "Votre statut",
  "a member": "ce membre",
  "ahead": "d'avance",
  "behind": "de retard",
  "for {t}": "pendant {t}",
  "not available": "indisponible",
  "not ready yet": "pas encore prêt",
  "now": "maintenant",
  "service error": "erreur de service",
  "starling": "starling",
  "the person who let you in": "la personne qui vous a laissé entrer",
  "them": "cette personne",
  "{failed} of {total} members did not get the new keys yet.": "{failed} membres sur {total} n'ont pas encore reçu les nouvelles clés.",
  "{name} radius": "Rayon de {name}",
  "{name} saved. Only this phone knows it exists.": "{name} enregistré. Seul ce téléphone sait que ce lieu existe.",
  "{n} members' keys changed": "Les clés de {n} membres ont changé",
  "{who} arrived at {place}": "Arrivée de {who} à {place}",
  "{who} can read nothing this circle sends from now on. Everyone still here got new keys.": "{who} ne peut plus rien lire de ce que ce cercle envoie à partir de maintenant. Tous ceux qui restent ont reçu de nouvelles clés.",
  "{who} changed the keys": "{who} a changé les clés",
  "{who} changed the keys.": "{who} a changé les clés.",
  "{who} checked in": "Tout va bien pour {who}",
  "{who} is now pinned to the new keys.": "Les nouvelles clés sont maintenant attachées à {who}.",
  "{who} is out. Everyone else has new keys.": "{who} ne fait plus partie du cercle. Tous les autres ont de nouvelles clés.",
  "{who} joined. Everyone got new keys.": "{who} a rejoint le cercle. Tout le monde a reçu de nouvelles clés.",
  "{who} left {place}": "{who} a quitté {place}",
  "{who} made new keys, but your list of members does not match theirs.": "{who} a généré de nouvelles clés, mais votre liste de membres ne correspond pas à la sienne.",
  "{who} removed {gone}": "{who} a retiré {gone}",
  "{who} removed {gone}.": "{who} a retiré {gone}.",
  "{who} removed {n} people": "{who} a retiré {n} personnes",
  "{who} removed {n} people from the circle.": "{who} a retiré {n} personnes du cercle.",
  "{who} wants to join": "{who} veut rejoindre le cercle",
  "{who} wants to join. Check their safety number.": "{who} veut rejoindre le cercle. Vérifiez son numéro de sécurité.",
  "{who}'s keys changed": "Les clés de {who} ont changé",
  "{who}'s keys changed. Their location is hidden until you accept it.": "Les clés de {who} ont changé. Sa position reste cachée tant que vous ne les acceptez pas.",
  "{who}'s phone is at {pct}%": "Le téléphone de {who} est à {pct} %",
  "{dist} to the {way} of you": "{dist} {way} de vous",
  "{n} sets of keys besides yours can decrypt what you send: {checked} checked by a person, {unchecked} trusted on first use.": "{n} jeux de clés en plus du vôtre peuvent déchiffrer ce que vous envoyez : {checked} vérifiés par une personne, {unchecked} acceptés sans vérification au premier contact.",
  "A newly admitted key can also read back {window} of history. That window is yours to set in Settings.": "Une clé nouvellement admise peut aussi relire {window} d'historique. Cette fenêtre, c'est vous qui la réglez dans les paramètres.",
  "A place with the privacy fence on shares only its center while you are inside it, never your exact spot within. Your circle still sees you are there; what they stop seeing is where in there. An SOS always sends your real position.": "Un lieu avec le périmètre privé activé ne partage que son centre tant que vous êtes dedans, jamais votre position exacte à l'intérieur. Votre cercle voit toujours que vous y êtes ; ce qu'il ne voit plus, c'est où exactement. Un SOS envoie toujours votre vraie position.",
  "Check-in delivered. Your circle sees it now.": "Message rassurant remis. Votre cercle le voit maintenant.",
  "Check-in not delivered yet. Starling keeps trying.": "Message rassurant pas encore remis. Starling réessaie.",
  "Check-in queued. Starling keeps trying...": "Message rassurant en attente. Starling réessaie...",
  "Copied. Paste it anywhere you keep your records.": "Copié. Collez-le là où vous gardez vos notes.",
  "Copy it all": "Tout copier",
  "Download as a file": "Télécharger sous forme de fichier",
  "east": "à l'est",
  "Everything Starling keeps about you, on this device and nowhere else. Positions are absent because they are never stored; keys are absent on purpose.": "Tout ce que Starling garde sur vous, sur cet appareil et nulle part ailleurs. Les positions sont absentes parce qu'elles ne sont jamais stockées ; les clés sont absentes volontairement.",
  "never": "jamais",
  "north": "au nord",
  "northeast": "au nord-est",
  "northwest": "au nord-ouest",
  "One readable file: profile, settings, places, circle names, who you trust. No positions, because Starling stores none, and no keys, ever.": "Un fichier lisible : profil, paramètres, lieux, noms des cercles, en qui vous avez confiance. Pas de positions, parce que Starling n'en stocke aucune, et pas de clés, jamais.",
  "Only your own keys can decrypt what you send. The relay stores ciphertext it cannot open.": "Seules vos propres clés peuvent déchiffrer ce que vous envoyez. Le relais stocke du texte chiffré qu'il ne peut pas ouvrir.",
  "Privacy fence": "Périmètre privé",
  "Privacy fence for {name}": "Périmètre privé pour {name}",
  "See everything Starling has": "Voir tout ce que Starling garde",
  "Share timer": "Minuteur de partage",
  "SOS delivered to your circle.": "SOS remis à votre cercle.",
  "SOS not delivered yet. Starling keeps trying.": "SOS pas encore remis. Starling réessaie.",
  "SOS queued. Starling keeps trying...": "SOS en attente. Starling réessaie...",
  "south": "au sud",
  "southeast": "au sud-est",
  "southwest": "au sud-ouest",
  "stops in {left}": "s'arrête dans {left}",
  "Stop by itself:": "Arrêt automatique :",
  "telling your circle...": "envoi à votre cercle...",
  "Sharing was on when the app closed, so it is back on.": "Le partage était actif quand l'application s'est fermée, il est donc de nouveau actif.",
  "Timed share ended. Your circle sees you stopped sharing.": "Le partage minuté est terminé. Votre cercle voit que vous avez arrêté de partager.",
  "west": "à l'ouest",
  "Who could read you": "Qui pourrait vous lire",
  "Your circle now sees you stopped sharing.": "Votre cercle voit maintenant que vous avez arrêté de partager.",
  "Your data": "Vos données",
  "Your last share was stopped outside the app": "Votre dernier partage a été arrêté hors de l'application",
  "Android shut down the part of Starling that sends your position, so the share stopped. Nobody did this by hand.": "Android a fermé la partie de Starling qui envoie votre position, donc le partage s'est arrêté. Personne ne l'a fait à la main.",
  "Someone tapped Stop on the sharing notification. If that was not you, check who has access to this phone.": "Quelqu'un a appuyé sur « Arrêter » dans la notification de partage. Si ce n'était pas vous, vérifiez qui a accès à ce téléphone.",
  "The app was closed while sharing was on, which stops it every time. If that was not you, check who has access to this phone.": "L'application a été fermée pendant un partage, ce qui l'arrête à chaque fois. Si ce n'était pas vous, vérifiez qui a accès à ce téléphone.",
  "The app was closed while sharing was on, which stopped it, and opening it again put it back on. If closing it was not you, check who has access to this phone.": "L'application a été fermée pendant un partage, ce qui l'a arrêté, et la rouvrir l'a relancé. Si ce n'est pas vous qui l'avez fermée, vérifiez qui a accès à ce téléphone.",
  "Keep sharing when the app is closed": "Continuer le partage quand l'application est fermée",
  "Sharing normally stops when you swipe Starling out of recents, because the keys that encrypt each position live in the app. With this on, Starling stays loaded in the background until the share ends, so closing it does not stop it. Anyone holding your unlocked phone can see the app is still running, and it is still holding your keys, so the app lock cannot protect them until the share ends.": "Normalement, le partage s'arrête quand vous balayez Starling hors des applications récentes, parce que les clés qui chiffrent chaque position vivent dans l'application. Avec cette option, Starling reste chargée en arrière-plan jusqu'à la fin du partage, donc la fermer ne l'arrête pas. Quiconque tient votre téléphone déverrouillé peut voir que l'application tourne encore, et elle garde encore vos clés, donc le verrouillage de l'application ne peut pas les protéger avant la fin du partage.",
  "Closing the app will not stop a share now.": "Fermer l'application n'arrête plus le partage.",
  "Closing the app stops a share again.": "Fermer l'application arrête de nouveau le partage.",
  "Could not change that setting.": "Impossible de changer ce réglage.",
  "Sharing was stopped from the notification.": "Le partage a été arrêté depuis la notification.",
  "Made by {name}": "Créé par {name}",
  "They chose the name {who}. Anyone can type any name, so the number below is the only part that proves who they are.": "Cette personne a choisi le nom {who}. N'importe qui peut taper n'importe quel nom, donc le numéro ci-dessous est la seule chose qui prouve qui elle est.",
  "Source code": "Code source",
  "Allow": "Autoriser",
  "Allow background running": "Autoriser l'exécution en arrière-plan",
  "Android had stopped your share in the background. It is back on.": "Android avait arrêté votre partage en arrière-plan. Il est de nouveau actif.",
  "Android kept Starling from running in the background, so your circle stopped getting your location and the share ended. Nobody did this by hand.": "Android a empêché Starling de tourner en arrière-plan, donc votre cercle a cessé de recevoir votre position et le partage s'est terminé. Personne ne l'a fait à la main.",
  "Android may pause Starling to save battery while your screen is off, and your circle would stop seeing you move. Letting Starling run in the background stops that. It only makes a difference while you share.": "Android peut mettre Starling en pause pour économiser la batterie quand votre écran est éteint, et votre cercle cesserait de vous voir bouger. Laisser Starling tourner en arrière-plan l'empêche. Cela ne change quelque chose que pendant un partage.",
  "Android stopped Starling in the background because its battery use is set to Restricted, and that ends every share a minute after you leave the app. Set it to Unrestricted in the app's settings.": "Android a arrêté Starling en arrière-plan parce que son utilisation de la batterie est réglée sur Limitée, ce qui met fin à chaque partage une minute après que vous quittez l'application. Réglez-la sur Sans restriction dans les paramètres de l'application.",
  "Android stopped Starling in the background, so the share ended. Nobody did this by hand.": "Android a arrêté Starling en arrière-plan, donc le partage s'est terminé. Personne ne l'a fait à la main.",
  "Android will stop this share when you leave the app": "Android arrêtera ce partage quand vous quitterez l'application",
  "Battery Saver is turning off your location": "L'économiseur de batterie coupe votre localisation",
  "Copy sharing report": "Copier le rapport de partage",
  "Could not copy the report.": "Impossible de copier le rapport.",
  "For a bug report: versions, permissions, battery settings and counts. It has no locations, no keys and no names in it.": "Pour signaler un bug : versions, autorisations, réglages de batterie et compteurs. Il ne contient ni position, ni clé, ni nom.",
  "It is back on now that the app is open.": "Il est de nouveau actif maintenant que l'application est ouverte.",
  "Keep sharing with the screen off": "Continuer le partage écran éteint",
  "Location is off on this phone. Turn it on to keep sharing.": "La localisation est désactivée sur ce téléphone. Activez-la pour continuer à partager.",
  "Not reaching your circle": "Votre cercle ne vous reçoit pas",
  "Optimized. Android may pause Starling to save battery while the screen is off, which can stop your circle seeing you move. Allowing it to run in the background prevents that.": "Optimisée. Android peut mettre Starling en pause pour économiser la batterie quand l'écran est éteint, ce qui peut empêcher votre cercle de vous voir bouger. L'autoriser à tourner en arrière-plan l'évite.",
  "Restricted. Android stops Starling about a minute after you leave it, and a share stops with it. Set battery use to Unrestricted in the app's settings.": "Limitée. Android arrête Starling environ une minute après que vous l'avez quittée, et le partage s'arrête avec. Réglez l'utilisation de la batterie sur Sans restriction dans les paramètres de l'application.",
  "Running in the background": "Exécution en arrière-plan",
  "Sharing report copied. It has no locations and no keys in it.": "Rapport de partage copié. Il ne contient ni position ni clé.",
  "SOS armed · Not reaching your circle": "SOS armé · Votre cercle ne vous reçoit pas",
  "Starling only has your approximate location": "Starling n'a que votre position approximative",
  "Starling's battery use is set to Restricted, so Android stops a share about a minute after the app leaves the screen. Set it to Unrestricted in the app's settings to keep sharing with the screen off.": "L'utilisation de la batterie de Starling est réglée sur Limitée, donc Android arrête un partage environ une minute après que l'application quitte l'écran. Réglez-la sur Sans restriction dans les paramètres de l'application pour continuer le partage écran éteint.",
  "Unrestricted. Android lets Starling keep a share going with the screen off.": "Sans restriction. Android laisse Starling poursuivre un partage écran éteint.",
  "With approximate location, Android updates your position roughly and only about every ten minutes, so your circle sees you jump. Allow precise location in the app's settings for a live share.": "Avec la position approximative, Android met votre position à jour grossièrement et seulement toutes les dix minutes environ, donc votre cercle vous voit sauter d'un point à l'autre. Autorisez la position précise dans les paramètres de l'application pour un partage en direct.",
  "With Battery Saver on, this phone turns location off while the screen is off, so your circle stops seeing you move. Turn Battery Saver off to keep sharing.": "Avec l'économiseur de batterie activé, ce téléphone coupe la localisation quand l'écran est éteint, donc votre cercle cesse de vous voir bouger. Désactivez l'économiseur de batterie pour continuer à partager.",
  "nothing sent yet": "rien d'envoyé pour l'instant",
  "last sent {ago} ago": "dernier envoi il y a {ago}",
  "Keep sharing": "Continuer le partage",
  "Shares now keep running while Starling is closed or locked.": "Les partages continuent maintenant quand Starling est fermée ou verrouillée.",
  "SOS armed · Location is off": "SOS armé · Localisation désactivée",
  "Starling locked itself while you were away, and a locked Starling holds no keys, so the lock ended your share.": "Starling s'est verrouillée pendant votre absence et, une fois verrouillée, ne garde aucune clé, donc le verrouillage a mis fin à votre partage.",
  "Starling locks itself after a while in the background, and a locked Starling holds no keys, so the lock would end this share.": "Starling se verrouille après un moment en arrière-plan et, une fois verrouillée, ne garde aucune clé, donc le verrouillage mettrait fin à ce partage.",
  "Tap Keep sharing to let shares run while Starling is closed or locked. The lock then waits until the share ends.": "Appuyez sur Continuer le partage pour laisser les partages tourner quand Starling est fermée ou verrouillée. Le verrouillage attend alors la fin du partage.",
  "The app lock ended your share": "Le verrouillage de l'application a mis fin à votre partage",
  "The app lock had ended your share. It is back on.": "Le verrouillage de l'application avait mis fin à votre partage. Il est de nouveau actif.",
  "The app lock will end this share": "Le verrouillage de l'application mettra fin à ce partage",
  "Unlocking put it back on.": "Le déverrouillage l'a relancé.",
  "also to {host}": "aussi vers {host}",
  "Changing where your position goes needs your passcode.": "Changer la destination de votre position demande votre code d'accès.",
  "Enter your passcode": "Saisissez votre code d'accès",
  "Paused while Tor mode is on, so nothing leaves this phone outside Tor.": "En pause tant que le mode Tor est activé, pour que rien ne quitte ce téléphone hors de Tor.",
  "Save": "Enregistrer",
  "Sends your own position in OwnTracks format to a server you run, like Reitti, Dawarich or Home Assistant, only while you share. It goes straight from this phone, never through the relay, and your circle's positions never go there. The server gets your precise position whatever the precision setting. With the app lock on, changing it needs your passcode.": "Envoie votre propre position au format OwnTracks à un serveur que vous gérez, comme Reitti, Dawarich ou Home Assistant, seulement pendant un partage. Elle part directement de ce téléphone, jamais par le relais, et les positions de votre cercle n'y vont jamais. Le serveur reçoit votre position précise quel que soit le réglage de précision. Avec le verrouillage de l'application activé, changer ceci demande votre code d'accès.",
  "Stop sending": "Arrêter l'envoi",
  "That address did not work. Use a full https address.": "Cette adresse n'a pas fonctionné. Utilisez une adresse https complète.",
  "That passcode is wrong.": "Ce code d'accès est incorrect.",
  "The last send failed: the server answered {code}.": "Le dernier envoi a échoué : le serveur a répondu {code}.",
  "The last send failed: the server did not answer.": "Le dernier envoi a échoué : le serveur n'a pas répondu.",
  "The last send worked.": "Le dernier envoi a fonctionné.",
  "Use a full https address, like https://your-server/owntracks": "Utilisez une adresse https complète, comme https://votre-serveur/owntracks",
  "While you share, your position also goes to {host}.": "Pendant un partage, votre position va aussi vers {host}.",
  "Your own server": "Votre propre serveur",
  "A tracker ID goes out as tid with each position, so a forwarder or Home Assistant can tell this phone apart.": "Un identifiant de traceur part comme tid avec chaque position, pour qu'un service de transfert ou Home Assistant puisse distinguer ce téléphone.",
  "Sent with the tracker ID {tid}.": "Envoyé avec l'identifiant de traceur {tid}.",
  "Set tracker ID": "Définir l'identifiant de traceur",
  "That tracker ID did not work.": "Cet identifiant de traceur n'a pas fonctionné.",
  "Tracker ID, like phone1 (optional)": "Identifiant de traceur, comme telephone1 (facultatif)",
  "Use up to 64 characters for the tracker ID, on one line.": "Utilisez jusqu'à 64 caractères pour l'identifiant de traceur, sur une seule ligne.",
  "Your position goes out as {tid}.": "Votre position part sous l'identifiant {tid}.",
  "Your position goes out with no tracker ID.": "Votre position part sans identifiant de traceur.",
  "Your position no longer goes to your own server.": "Votre position ne va plus vers votre propre serveur.",
  "This circle uses another relay": "Ce cercle utilise un autre relais",
  "This circle uses the relay at {host}. Asking to join switches Starling to it.": "Ce cercle utilise le relais {host}. Demander à le rejoindre fait basculer Starling dessus.",
  "This invitation is for a circle on {host}.": "Cette invitation est pour un cercle sur {host}.",
  "To join it, put {relay} in Settings, Advanced, Relay, restart Starling and open the link again. Your other circles stop updating while it is set.": "Pour le rejoindre, mettez {relay} dans Paramètres, Avancé, Relais, redémarrez Starling et rouvrez le lien. Vos autres cercles cessent de se mettre à jour tant que ce réglage est en place.",
  "Your circles use the default relay, and Starling talks to one relay at a time.": "Vos cercles utilisent le relais par défaut, et Starling ne parle qu'à un relais à la fois.",
  "Your circles use {host}, and Starling talks to one relay at a time.": "Vos cercles utilisent {host}, et Starling ne parle qu'à un relais à la fois.",
  "Use your own relay": "Utiliser votre propre relais",
  "Cancel your join request first.": "Annulez d'abord votre demande.",
  "Starling will use {host}.": "Starling utilisera {host}.",
  "Only if you run a relay yourself. Everyone in your circle has to use the same one, and the invite links you send carry it.": "Seulement si vous gérez vous-même un relais. Tout le monde dans votre cercle doit utiliser le même, et les liens d'invitation que vous envoyez le contiennent.",
  "This device could not run the lock's key stretching. Nothing was erased; try again, or free some memory.": "Cet appareil n'a pas pu exécuter la dérivation de clé du verrouillage. Rien n'a été effacé ; réessayez, ou libérez de la mémoire.",
  "Biometric unlock is on.": "Le déverrouillage biométrique est activé.",
  "coffee run": "pause café",
  "phone's dying": "batterie presque vide",
  "Press and hold to erase": "Maintenez appuyé pour effacer",
  "Press and hold to send SOS": "Maintenez appuyé pour envoyer un SOS",
  "Status cleared.": "Statut effacé.",
  "Status set.": "Statut enregistré.",
  "Tap once more to erase everything": "Touchez encore une fois pour tout effacer",
  "Tap once more to send SOS": "Touchez encore une fois pour envoyer le SOS",
  "You left the circle.": "Vous avez quitté le cercle.",
  "You left, but this device could not erase everything. Open Starling again to finish clearing it.": "Vous avez quitté le cercle, mais cet appareil n'a pas pu tout effacer. Rouvrez Starling pour finir le nettoyage.",
  "Your device or browser could not set up biometric unlock.": "Votre appareil ou votre navigateur n'a pas pu configurer le déverrouillage biométrique.",
  "{who} is already marked verified.": "{who} est déjà marqué comme vérifié.",
  "{who} is answering with different keys right now. Settle that on their card before marking anything.": "{who} répond avec d'autres clés en ce moment. Réglez cela sur sa fiche avant de marquer quoi que ce soit.",
  "{who} is verified.": "{who} est vérifié.",
  "15 s": "15 s",
  "Camera access was turned down. Allow it for Starling in system settings, then try again.": "L'accès à la caméra a été refusé. Autorisez-le pour Starling dans les réglages du système, puis réessayez.",
  "For {name}. Each circle keeps its own precision and timing.": "Pour {name}. Chaque cercle garde sa propre précision et son propre rythme.",
  "How often your circle hears from you while you stay put. Moving sends sooner unless Steady sending is on. Slower is easier on the battery. An SOS always goes every 15 seconds.": "La fréquence à laquelle votre cercle a de vos nouvelles quand vous ne bougez pas. Un déplacement envoie plus tôt, sauf si l'envoi régulier est activé. Plus lent ménage la batterie. Un SOS part toujours toutes les 15 secondes.",
  "Let the person checking you scan this with Starling. It holds your member id and your safety number, nothing else.": "Laissez la personne qui vous vérifie scanner ceci avec Starling. Il contient votre identifiant de membre et votre numéro de sécurité, rien d'autre.",
  "Mark {who} verified": "Marquer {who} comme vérifié",
  "No camera found on this device.": "Aucune caméra trouvée sur cet appareil.",
  "Point the camera at the code on their screen.": "Pointez la caméra vers le code sur son écran.",
  "Safety number QR code": "Code QR du numéro de sécurité",
  "Scan result": "Résultat du scan",
  "Scan their code": "Scanner son code",
  "Scan theirs": "Scanner le sien",
  "Scanning a code lives in the app. Here, compare the digits.": "Le scan d'un code se fait dans l'application. Ici, comparez les chiffres.",
  "Send every": "Envoyer toutes les",
  "Show as QR": "Afficher en QR",
  "That code belongs to nobody in this circle.": "Ce code n'appartient à personne dans ce cercle.",
  "That is not a Starling safety number code.": "Ce n'est pas un code de numéro de sécurité Starling.",
  "The camera could not start.": "La caméra n'a pas pu démarrer.",
  "The code does not match the keys this phone holds for {who}. That is a reinstall, or somebody in between, and this phone cannot tell which. Do not mark them verified. Read the digits out to each other, and if they still differ, remove them.": "Le code ne correspond pas aux clés que ce téléphone détient pour {who}. C'est une réinstallation, ou quelqu'un entre vous deux, et ce téléphone ne peut pas faire la différence. Ne le marquez pas comme vérifié. Lisez-vous les chiffres à voix haute, et s'ils diffèrent encore, retirez cette personne.",
  "The code matches the keys this phone holds for {who}. Nobody is in between.": "Le code correspond aux clés que ce téléphone détient pour {who}. Personne ne s'est glissé entre vous.",
  "Your number as a code": "Votre numéro sous forme de code",
  "Your number is not ready yet.": "Votre numéro n'est pas encore prêt.",
  "Check-in timer": "Minuteur de sécurité",
  "Get your circle told if you miss a check-in": "Votre cercle est prévenu si vous ne le rassurez pas à temps",
  "Pick how long you need. If you have not checked in when it runs out, your circle is told, even if this phone is off by then. Only checking in stops it.": "Choisissez le temps qu'il vous faut. Si vous n'avez pas rassuré votre cercle à la fin, il est prévenu, même si ce téléphone est éteint d'ici là. Seul un message rassurant l'arrête.",
  "Check in within": "Délai pour rassurer",
  "Start timer": "Lancer le minuteur",
  "Check in now": "Rassurer maintenant",
  "Check in by {time}": "Nouvelles attendues avant {time}",
  "Start sharing too": "Partager aussi",
  "Sharing is off, so your circle gets the timer and the last position this phone sent, not where you are now.": "Le partage est coupé, donc votre cercle reçoit le minuteur et la dernière position envoyée par ce téléphone, pas l'endroit où vous êtes maintenant.",
  "Timer set. Check in by {time}.": "Minuteur réglé. Nouvelles attendues avant {time}.",
  "Timer set, but your circle does not have it yet. Starling keeps trying.": "Minuteur réglé, mais votre cercle ne l'a pas encore reçu. Starling réessaie.",
  "Check in within 5 minutes, or your circle is told.": "Rassurez votre cercle dans les 5 minutes, sinon il sera prévenu.",
  "You missed your check-in": "Vous n'avez pas rassuré votre cercle à temps",
  "Your circle has been told. Check in now if you are okay.": "Votre cercle a été prévenu. Rassurez-le maintenant si tout va bien.",
  "{who} missed their check-in": "{who} n'a pas donné de nouvelles à temps",
  "Their timer ran out at {time}. Their last position is on the map.": "Son minuteur s'est terminé à {time}. Sa dernière position est sur la carte.",
  "Their last position is on the map.": "Sa dernière position est sur la carte.",
  "Show on map": "Voir sur la carte",
  "Missed check-in": "Sans nouvelles",
  "Your check-in timer is running in {circle}. Check in there before you switch?": "Votre minuteur de sécurité tourne dans {circle}. Rassurer ce cercle avant de changer ?",
  "Check in and switch": "Rassurer et changer",
  "Exit the demo to set a check-in timer.": "Quittez la démo pour régler un minuteur de sécurité.",
  "Their live position is on the map. It stays here until they check in.": "Sa position en direct est sur la carte. Cette alerte reste ici jusqu'à ce que la personne vous rassure.",
  "{who}'s phone stopped sending {ago} ago. The last position it sent is on the map.": "Le téléphone de {who} n'envoie plus rien depuis {ago}. La dernière position envoyée est sur la carte.",
  "{who}'s SOS went quiet": "Le SOS de {who} ne donne plus de signal",
  "Alerts": "Alertes",
  "{name} alerts": "Alertes pour {name}",
  "Both": "Les deux",
  "Arrive": "Arrivée",
  "Leave": "Départ",
  "Off": "Aucune",
  "Your battery is at {pct}%": "Votre batterie est à {pct} %",
  "Sending every 5 minutes instead of every 15 seconds makes it last longer. An SOS still goes out every 15 seconds.": "Envoyer toutes les 5 minutes au lieu de toutes les 15 secondes la fait durer plus longtemps. Un SOS part toujours toutes les 15 secondes.",
  "Every 5 minutes": "Toutes les 5 minutes",
  "Accurate to about {dist}": "Précis à {dist} près environ",
  "Phone battery {pct}%": "Batterie du téléphone : {pct} %",
  "Link works until {time}": "Lien valable jusqu'à {time}",
  "Open in a map app": "Ouvrir dans une app de cartes",
};
