#!/usr/bin/env node
// Hashes every file the site actually serves out of app/ and writes a
// deterministic manifest to dist/asset-hashes-<version>.txt. A third party
// can fetch the live site and compare its own hashes against this file to
// notice a targeted swap. See docs/WEB-INTEGRITY.md for what that does and
// does not buy.
//
// Usage:
//   node tools/asset-hashes.mjs          write dist/asset-hashes-<version>.txt
//   node tools/asset-hashes.mjs --check  recompute and diff against that file
//
// Stdlib only, no dependencies.

import { createHash } from 'node:crypto';
import {
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
  existsSync,
  mkdirSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const appDir = join(repoRoot, 'app');

// --- a small .gitignore matcher, just enough for this repo's patterns ---
// git's real matcher has more rules than this (negation, ** globs, and so
// on). The patterns in this repo's .gitignore are simple, so a simple
// matcher is honest about what it covers rather than pretending to be a
// full implementation.
function loadGitignorePatterns(root) {
  const p = join(root, '.gitignore');
  if (!existsSync(p)) return [];
  return readFileSync(p, 'utf8')
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#'));
}

function escapeRegExp(s) {
  return s.replace(/[.+^${}()|[\]\\]/g, '\\$&');
}

function patternToRegExp(pattern) {
  const isDir = pattern.endsWith('/');
  let body = isDir ? pattern.slice(0, -1) : pattern;
  const anchored = body.includes('/');
  body = escapeRegExp(body).replace(/\\\*/g, '[^/]*').replace(/\\\?/g, '[^/]');
  const tail = isDir ? '(/.*)?$' : '$';
  return anchored
    ? new RegExp('^' + body + tail)
    : new RegExp('(^|.*/)' + body + tail);
}

const gitignoreMatchers = loadGitignorePatterns(repoRoot).map(patternToRegExp);

function isGitignored(relPath) {
  return gitignoreMatchers.some((re) => re.test(relPath));
}

// app/vendor/ is entirely gitignored (it's generated locally by
// tools/sync-vendor.sh and never committed), but app/vendor/leaflet/*.js,
// *.css and its image assets are genuinely served in production and loaded
// by app/help.html. Hash them like any other served asset. The one file in
// that directory that is not served is the source map, which is excluded
// explicitly below.
function isServedVendorLeaflet(relPath) {
  return (
    relPath.startsWith('app/vendor/leaflet/') && !relPath.endsWith('.map')
  );
}

function shouldInclude(relPath) {
  if (relPath.startsWith('app/vendor/leaflet/') && relPath.endsWith('.map')) {
    return false;
  }
  if (isServedVendorLeaflet(relPath)) return true;
  return !isGitignored(relPath);
}

function walk(dir, out) {
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full, out);
    } else if (st.isFile()) {
      out.push(full);
    }
  }
}

function toPosix(relPath) {
  return relPath.split(process.platform === 'win32' ? '\\' : '/').join('/');
}

function sha256File(absPath) {
  const data = readFileSync(absPath);
  return createHash('sha256').update(data).digest('hex');
}

function gitCommit() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
  } catch {
    return 'unknown';
  }
}

function buildManifestLines() {
  const files = [];
  walk(appDir, files);
  const entries = [];
  for (const abs of files) {
    const rel = toPosix(abs.slice(repoRoot.length + 1));
    if (!shouldInclude(rel)) continue;
    entries.push({ rel, hash: sha256File(abs) });
  }
  entries.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return entries.map((e) => `${e.hash}  ${e.rel}`);
}

function readPackageVersion() {
  const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));
  return pkg.version;
}

function manifestHeader(version, commit) {
  return [
    `# Starling asset hashes - v${version}`,
    `# commit ${commit}`,
    '# generated by tools/asset-hashes.mjs, one SHA-256 per served file under app/',
    '#',
    '# To verify against the live site, fetch each path below and hash it:',
    '#   curl -s https://starlingmap.app/<path> | sha256sum',
    '# See docs/WEB-INTEGRITY.md for the full verification recipe and what',
    '# this manifest does and does not prove.',
  ];
}

function manifestPath(version) {
  return join(repoRoot, 'dist', `asset-hashes-${version}.txt`);
}

function writeManifest() {
  const version = readPackageVersion();
  const commit = gitCommit();
  const lines = [...manifestHeader(version, commit), ...buildManifestLines()];
  const content = lines.join('\n') + '\n';
  const distDir = join(repoRoot, 'dist');
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
  const out = manifestPath(version);
  writeFileSync(out, content);
  console.log(`wrote ${out}`);
  return out;
}

function checkManifest() {
  const version = readPackageVersion();
  const path = manifestPath(version);
  if (!existsSync(path)) {
    console.error(`no manifest at ${path}, run without --check first`);
    return 1;
  }
  const existingLines = readFileSync(path, 'utf8').split('\n');
  const existingEntries = new Map();
  for (const line of existingLines) {
    if (!line || line.startsWith('#')) continue;
    const sep = line.indexOf('  ');
    if (sep === -1) continue;
    existingEntries.set(line.slice(sep + 2), line.slice(0, sep));
  }

  const currentLines = buildManifestLines();
  const currentEntries = new Map();
  for (const line of currentLines) {
    const sep = line.indexOf('  ');
    currentEntries.set(line.slice(sep + 2), line.slice(0, sep));
  }

  let mismatch = false;
  for (const [rel, hash] of currentEntries) {
    const prior = existingEntries.get(rel);
    if (prior === undefined) {
      console.error(`new file not in manifest: ${rel}`);
      mismatch = true;
    } else if (prior !== hash) {
      console.error(`hash mismatch: ${rel}`);
      console.error(`  manifest: ${prior}`);
      console.error(`  actual:   ${hash}`);
      mismatch = true;
    }
  }
  for (const rel of existingEntries.keys()) {
    if (!currentEntries.has(rel)) {
      console.error(`file in manifest but no longer served: ${rel}`);
      mismatch = true;
    }
  }

  if (mismatch) {
    console.error(`FAIL: ${path} does not match the current tree`);
    return 1;
  }
  console.log(`OK: ${path} matches the current tree (${currentEntries.size} files)`);
  return 0;
}

const mode = process.argv.includes('--check') ? 'check' : 'write';
const code = mode === 'check' ? checkManifest() : (writeManifest(), 0);
process.exit(code);
